# pylint: disable=too-many-lines
COUNTRIES = [
    {
        'short_en': 'Afghanistan',
        'long_en': 'The Islamic Republic of Afghanistan',
        'short_ru': 'Афганистан',
        'long_ru': 'Переходное Исламское Государство Афганистан',
        'a2': 'AF',
        'a3': 'AFG',
        'num': 4,
        'tld': '.af',
    },
    {
        'short_en': 'Åland Islands',
        'long_en': 'Åland',
        'short_ru': 'Эландские Острова',
        'long_ru': 'Эландские Острова',
        'a2': 'AX',
        'a3': 'ALA',
        'num': 248,
        'tld': '.ax',
    },
    {
        'short_en': 'Albania',
        'long_en': 'The Republic of Albania',
        'short_ru': 'Албания',
        'long_ru': 'Республика Албания',
        'a2': 'AL',
        'a3': 'ALB',
        'num': 8,
        'tld': '.al',
    },
    {
        'short_en': 'Algeria',
        'long_en': "The People's Democratic Republic of Algeria",
        'short_ru': 'Алжир',
        'long_ru': 'Алжирская Народная Демократическая Республика',
        'a2': 'DZ',
        'a3': 'DZA',
        'num': 12,
        'tld': '.dz',
    },
    {
        'short_en': 'American Samoa',
        'long_en': 'The Territory of American Samoa',
        'short_ru': 'Американское Самоа',
        'long_ru': 'Американское Самоа',
        'a2': 'AS',
        'a3': 'ASM',
        'num': 16,
        'tld': '.as',
    },
    {
        'short_en': 'Andorra',
        'long_en': 'The Principality of Andorra',
        'short_ru': 'Андорра',
        'long_ru': 'Княжество Андорра',
        'a2': 'AD',
        'a3': 'AND',
        'num': 20,
        'tld': '.ad',
    },
    {
        'short_en': 'Angola',
        'long_en': 'The Republic of Angola',
        'short_ru': 'Ангола',
        'long_ru': 'Республика Ангола',
        'a2': 'AO',
        'a3': 'AGO',
        'num': 24,
        'tld': '.ao',
    },
    {
        'short_en': 'Anguilla',
        'long_en': 'Anguilla',
        'short_ru': 'Ангилья',
        'long_ru': 'Ангилья',
        'a2': 'AI',
        'a3': 'AIA',
        'num': 660,
        'tld': '.ai',
    },
    {
        'short_en': 'Antarctica',
        'long_en': (
            'Antarctica (all land and ice shelves south of the60th parallel south)'
        ),
        'short_ru': 'Антарктида',
        'long_ru': 'Антарктида',
        'a2': 'AQ',
        'a3': 'ATA',
        'num': 10,
        'tld': '.aq',
    },
    {
        'short_en': 'Antigua and Barbuda',
        'long_en': 'Antigua and Barbuda',
        'short_ru': 'Антигуа И Барбуда',
        'long_ru': 'Антигуа И Барбуда',
        'a2': 'AG',
        'a3': 'ATG',
        'num': 28,
        'tld': '.ag',
    },
    {
        'short_en': 'Argentina',
        'long_en': 'The Argentine Republic',
        'short_ru': 'Аргентина',
        'long_ru': 'Аргентинская Республика',
        'a2': 'AR',
        'a3': 'ARG',
        'num': 32,
        'tld': '.ar',
    },
    {
        'short_en': 'Armenia',
        'long_en': 'The Republic of Armenia',
        'short_ru': 'Армения',
        'long_ru': 'Республика Армения',
        'a2': 'AM',
        'a3': 'ARM',
        'num': 51,
        'tld': '.am',
    },
    {
        'short_en': 'Aruba',
        'long_en': 'Aruba',
        'short_ru': 'Аруба',
        'long_ru': 'Аруба',
        'a2': 'AW',
        'a3': 'ABW',
        'num': 533,
        'tld': '.aw',
    },
    {
        'short_en': 'Australia',
        'long_en': 'The Commonwealth of Australia',
        'short_ru': 'Австралия',
        'long_ru': 'Австралия',
        'a2': 'AU',
        'a3': 'AUS',
        'num': 36,
        'tld': '.au',
    },
    {
        'short_en': 'Austria',
        'long_en': 'The Republic of Austria',
        'short_ru': 'Австрия',
        'long_ru': 'Австрийская Республика',
        'a2': 'AT',
        'a3': 'AUT',
        'num': 40,
        'tld': '.at',
    },
    {
        'short_en': 'Azerbaijan',
        'long_en': 'The Republic of Azerbaijan',
        'short_ru': 'Азербайджан',
        'long_ru': 'Республика Азербайджан',
        'a2': 'AZ',
        'a3': 'AZE',
        'num': 31,
        'tld': '.az',
    },
    {
        'short_en': 'Bahamas',
        'long_en': 'The Commonwealth of The Bahamas',
        'short_ru': 'Багамы',
        'long_ru': 'Содружество Багамы',
        'a2': 'BS',
        'a3': 'BHS',
        'num': 44,
        'tld': '.bs',
    },
    {
        'short_en': 'Bahrain',
        'long_en': 'The Kingdom of Bahrain',
        'short_ru': 'Бахрейн',
        'long_ru': 'Королевство Бахрейн',
        'a2': 'BH',
        'a3': 'BHR',
        'num': 48,
        'tld': '.bh',
    },
    {
        'short_en': 'Bangladesh',
        'long_en': "The People's Republic of Bangladesh",
        'short_ru': 'Бангладеш',
        'long_ru': 'Народная Республика Бангладеш',
        'a2': 'BD',
        'a3': 'BGD',
        'num': 50,
        'tld': '.bd',
    },
    {
        'short_en': 'Barbados',
        'long_en': 'Barbados',
        'short_ru': 'Барбадос',
        'long_ru': 'Барбадос',
        'a2': 'BB',
        'a3': 'BRB',
        'num': 52,
        'tld': '.bb',
    },
    {
        'short_en': 'Belarus',
        'long_en': 'The Republic of Belarus',
        'short_ru': 'Беларусь',
        'long_ru': 'Республика Беларусь',
        'a2': 'BY',
        'a3': 'BLR',
        'num': 112,
        'tld': '.by',
    },
    {
        'short_en': 'Belgium',
        'long_en': 'The Kingdom of Belgium',
        'short_ru': 'Бельгия',
        'long_ru': 'Королевство Бельгия',
        'a2': 'BE',
        'a3': 'BEL',
        'num': 56,
        'tld': '.be',
    },
    {
        'short_en': 'Belize',
        'long_en': 'Belize',
        'short_ru': 'Белиз',
        'long_ru': 'Белиз',
        'a2': 'BZ',
        'a3': 'BLZ',
        'num': 84,
        'tld': '.bz',
    },
    {
        'short_en': 'Benin',
        'long_en': 'The Republic of Benin',
        'short_ru': 'Бенин',
        'long_ru': 'Республика Бенин',
        'a2': 'BJ',
        'a3': 'BEN',
        'num': 204,
        'tld': '.bj',
    },
    {
        'short_en': 'Bermuda',
        'long_en': 'Bermuda',
        'short_ru': 'Бермуды',
        'long_ru': 'Бермуды',
        'a2': 'BM',
        'a3': 'BMU',
        'num': 60,
        'tld': '.bm',
    },
    {
        'short_en': 'Bhutan',
        'long_en': 'The Kingdom of Bhutan',
        'short_ru': 'Бутан',
        'long_ru': 'Королевство Бутан',
        'a2': 'BT',
        'a3': 'BTN',
        'num': 64,
        'tld': '.bt',
    },
    {
        'short_en': 'Bolivia (Plurinational State of)',
        'long_en': 'The Plurinational State of Bolivia',
        'short_ru': 'Боливия, Многонациональное Государство',
        'long_ru': 'Многонациональное Государство Боливия',
        'a2': 'BO',
        'a3': 'BOL',
        'num': 68,
        'tld': '.bo',
    },
    {
        'short_en': 'Bonaire',
        'long_en': 'Bonaire, Sint Eustatius and Saba',
        'short_ru': 'Бонэйр, Синт-Эстатиус И Саба',
        'long_ru': 'Бонэйр, Синт-Эстатиус И Саба',
        'a2': 'BQ',
        'a3': 'BES',
        'num': 535,
        'tld': '.bq.nl',
    },
    {
        'short_en': 'Bosnia and Herzegovina',
        'long_en': 'Bosnia and Herzegovina',
        'short_ru': 'Босния И Герцеговина',
        'long_ru': 'Босния И Герцеговина',
        'a2': 'BA',
        'a3': 'BIH',
        'num': 70,
        'tld': '.ba',
    },
    {
        'short_en': 'Botswana',
        'long_en': 'The Republic of Botswana',
        'short_ru': 'Ботсвана',
        'long_ru': 'Республика Ботсвана',
        'a2': 'BW',
        'a3': 'BWA',
        'num': 72,
        'tld': '.bw',
    },
    {
        'short_en': 'Bouvet Island',
        'long_en': 'Bouvet Island',
        'short_ru': 'Остров Буве',
        'long_ru': 'Остров Буве',
        'a2': 'BV',
        'a3': 'BVT',
        'num': 74,
        'tld': '',
    },
    {
        'short_en': 'Brazil',
        'long_en': 'The Federative Republic of Brazil',
        'short_ru': 'Бразилия',
        'long_ru': 'Федеративная Республика Бразилия',
        'a2': 'BR',
        'a3': 'BRA',
        'num': 76,
        'tld': '.br',
    },
    {
        'short_en': 'British Indian Ocean Territory',
        'long_en': 'The British Indian Ocean Territory',
        'short_ru': 'Британская Территория В Индийском Океане',
        'long_ru': 'Британская Территория В Индийском Океане',
        'a2': 'IO',
        'a3': 'IOT',
        'num': 86,
        'tld': '.io',
    },
    {
        'short_en': 'Brunei Darussalam',
        'long_en': 'The Nation of Brunei, the Abode of Peace',
        'short_ru': 'Бруней-Даруссалам',
        'long_ru': 'Бруней-Даруссалам',
        'a2': 'BN',
        'a3': 'BRN',
        'num': 96,
        'tld': '.bn',
    },
    {
        'short_en': 'Bulgaria',
        'long_en': 'The Republic of Bulgaria',
        'short_ru': 'Болгария',
        'long_ru': 'Республика Болгария',
        'a2': 'BG',
        'a3': 'BGR',
        'num': 100,
        'tld': '.bg',
    },
    {
        'short_en': 'Burkina Faso',
        'long_en': 'Burkina Faso',
        'short_ru': 'Буркина-Фасо',
        'long_ru': 'Буркина-Фасо',
        'a2': 'BF',
        'a3': 'BFA',
        'num': 854,
        'tld': '.bf',
    },
    {
        'short_en': 'Burundi',
        'long_en': 'The Republic of Burundi',
        'short_ru': 'Бурунди',
        'long_ru': 'Республика Бурунди',
        'a2': 'BI',
        'a3': 'BDI',
        'num': 108,
        'tld': '.bi',
    },
    {
        'short_en': 'Cabo Verde',
        'long_en': 'The Republic of Cabo Verde',
        'short_ru': 'Кабо-Верде',
        'long_ru': 'Республика Кабо-Верде',
        'a2': 'CV',
        'a3': 'CPV',
        'num': 132,
        'tld': '.cv',
    },
    {
        'short_en': 'Cambodia',
        'long_en': 'The Kingdom of Cambodia',
        'short_ru': 'Камбоджа',
        'long_ru': 'Королевство Камбоджа',
        'a2': 'KH',
        'a3': 'KHM',
        'num': 116,
        'tld': '.kh',
    },
    {
        'short_en': 'Cameroon',
        'long_en': 'The Republic of Cameroon',
        'short_ru': 'Камерун',
        'long_ru': 'Республика Камерун',
        'a2': 'CM',
        'a3': 'CMR',
        'num': 120,
        'tld': '.cm',
    },
    {
        'short_en': 'Canada',
        'long_en': 'Canada',
        'short_ru': 'Канада',
        'long_ru': 'Канада',
        'a2': 'CA',
        'a3': 'CAN',
        'num': 124,
        'tld': '.ca',
    },
    {
        'short_en': 'Cayman Islands',
        'long_en': 'The Cayman Islands',
        'short_ru': 'Острова Кайман',
        'long_ru': 'Острова Кайман',
        'a2': 'KY',
        'a3': 'CYM',
        'num': 136,
        'tld': '.ky',
    },
    {
        'short_en': 'Central African Republic',
        'long_en': 'The Central African Republic',
        'short_ru': 'Центрально-Африканская Республика',
        'long_ru': 'Центрально-Африканская Республика',
        'a2': 'CF',
        'a3': 'CAF',
        'num': 140,
        'tld': '.cf',
    },
    {
        'short_en': 'Chad',
        'long_en': 'The Republic of Chad',
        'short_ru': 'Чад',
        'long_ru': 'Республика Чад',
        'a2': 'TD',
        'a3': 'TCD',
        'num': 148,
        'tld': '.td',
    },
    {
        'short_en': 'Chile',
        'long_en': 'The Republic of Chile',
        'short_ru': 'Чили',
        'long_ru': 'Республика Чили',
        'a2': 'CL',
        'a3': 'CHL',
        'num': 152,
        'tld': '.cl',
    },
    {
        'short_en': 'China',
        'long_en': "The People's Republic of China",
        'short_ru': 'Китай',
        'long_ru': 'Китайская Народная Республика',
        'a2': 'CN',
        'a3': 'CHN',
        'num': 156,
        'tld': '.cn',
    },
    {
        'short_en': 'Christmas Island',
        'long_en': 'The Territory of Christmas Island',
        'short_ru': 'Остров Рождества',
        'long_ru': 'Остров Рождества',
        'a2': 'CX',
        'a3': 'CXR',
        'num': 162,
        'tld': '.cx',
    },
    {
        'short_en': 'Cocos (Keeling) Islands',
        'long_en': 'The Territory of Cocos (Keeling) Islands',
        'short_ru': 'Кокосовые (Килинг) Острова',
        'long_ru': 'Кокосовые (Килинг) Острова',
        'a2': 'CC',
        'a3': 'CCK',
        'num': 166,
        'tld': '.cc',
    },
    {
        'short_en': 'Colombia',
        'long_en': 'The Republic of Colombia',
        'short_ru': 'Колумбия',
        'long_ru': 'Республика Колумбия',
        'a2': 'CO',
        'a3': 'COL',
        'num': 170,
        'tld': '.co',
    },
    {
        'short_en': 'Comoros',
        'long_en': 'The Union of the Comoros',
        'short_ru': 'Коморы',
        'long_ru': 'Союз Коморы',
        'a2': 'KM',
        'a3': 'COM',
        'num': 174,
        'tld': '.km',
    },
    {
        'short_en': 'Congo (the Democratic Republic of the)',
        'long_en': 'The Democratic Republic of the Congo',
        'short_ru': 'Конго, Демократическая Республика',
        'long_ru': 'Демократическая Республика Конго',
        'a2': 'CD',
        'a3': 'COD',
        'num': 180,
        'tld': '.cd',
    },
    {
        'short_en': 'Congo',
        'long_en': 'The Republic of the Congo',
        'short_ru': 'Конго',
        'long_ru': 'Республика Конго',
        'a2': 'CG',
        'a3': 'COG',
        'num': 178,
        'tld': '.cg',
    },
    {
        'short_en': 'Cook Islands',
        'long_en': 'The Cook Islands',
        'short_ru': 'Острова Кука',
        'long_ru': 'Острова Кука',
        'a2': 'CK',
        'a3': 'COK',
        'num': 184,
        'tld': '.ck',
    },
    {
        'short_en': 'Costa Rica',
        'long_en': 'The Republic of Costa Rica',
        'short_ru': 'Коста-Рика',
        'long_ru': 'Республика Коста-Рика',
        'a2': 'CR',
        'a3': 'CRI',
        'num': 188,
        'tld': '.cr',
    },
    {
        'short_en': "Côte d'Ivoire",
        'long_en': "The Republic of Côte d'Ivoire",
        'short_ru': "Кот Д'Ивуар",
        'long_ru': "Республика Кот Д'Ивуар",
        'a2': 'CI',
        'a3': 'CIV',
        'num': 384,
        'tld': '.ci',
    },
    {
        'short_en': 'Croatia',
        'long_en': 'The Republic of Croatia',
        'short_ru': 'Хорватия',
        'long_ru': 'Республика Хорватия',
        'a2': 'HR',
        'a3': 'HRV',
        'num': 191,
        'tld': '.hr',
    },
    {
        'short_en': 'Cuba',
        'long_en': 'The Republic of Cuba',
        'short_ru': 'Куба',
        'long_ru': 'Республика Куба',
        'a2': 'CU',
        'a3': 'CUB',
        'num': 192,
        'tld': '.cu',
    },
    {
        'short_en': 'Curaçao',
        'long_en': 'The Country of Curaçao',
        'short_ru': 'Кюрасао',
        'long_ru': 'Кюрасао',
        'a2': 'CW',
        'a3': 'CUW',
        'num': 531,
        'tld': '.cw',
    },
    {
        'short_en': 'Cyprus',
        'long_en': 'The Republic of Cyprus',
        'short_ru': 'Кипр',
        'long_ru': 'Республика Кипр',
        'a2': 'CY',
        'a3': 'CYP',
        'num': 196,
        'tld': '.cy',
    },
    {
        'short_en': 'Czechia',
        'long_en': 'The Czech Republic',
        'short_ru': 'Чехия',
        'long_ru': 'Чешская Республика',
        'a2': 'CZ',
        'a3': 'CZE',
        'num': 203,
        'tld': '.cz',
    },
    {
        'short_en': 'Denmark',
        'long_en': 'The Kingdom of Denmark',
        'short_ru': 'Дания',
        'long_ru': 'Королевство Дания',
        'a2': 'DK',
        'a3': 'DNK',
        'num': 208,
        'tld': '.dk',
    },
    {
        'short_en': 'Djibouti',
        'long_en': 'The Republic of Djibouti',
        'short_ru': 'Джибути',
        'long_ru': 'Республика Джибути',
        'a2': 'DJ',
        'a3': 'DJI',
        'num': 262,
        'tld': '.dj',
    },
    {
        'short_en': 'Dominica',
        'long_en': 'The Commonwealth of Dominica',
        'short_ru': 'Доминика',
        'long_ru': 'Содружество Доминики',
        'a2': 'DM',
        'a3': 'DMA',
        'num': 212,
        'tld': '.dm',
    },
    {
        'short_en': 'Dominican Republic',
        'long_en': 'The Dominican Republic',
        'short_ru': 'Доминиканская Республика',
        'long_ru': 'Доминиканская Республика',
        'a2': 'DO',
        'a3': 'DOM',
        'num': 214,
        'tld': '.do',
    },
    {
        'short_en': 'Ecuador',
        'long_en': 'The Republic of Ecuador',
        'short_ru': 'Эквадор',
        'long_ru': 'Республика Эквадор',
        'a2': 'EC',
        'a3': 'ECU',
        'num': 218,
        'tld': '.ec',
    },
    {
        'short_en': 'Egypt',
        'long_en': 'The Arab Republic of Egypt',
        'short_ru': 'Египет',
        'long_ru': 'Арабская Республика Египет',
        'a2': 'EG',
        'a3': 'EGY',
        'num': 818,
        'tld': '.eg',
    },
    {
        'short_en': 'El Salvador',
        'long_en': 'The Republic of El Salvador',
        'short_ru': 'Эль-Сальвадор',
        'long_ru': 'Республика Эль-Сальвадор',
        'a2': 'SV',
        'a3': 'SLV',
        'num': 222,
        'tld': '.sv',
    },
    {
        'short_en': 'Equatorial Guinea',
        'long_en': 'The Republic of Equatorial Guinea',
        'short_ru': 'Экваториальная Гвинея',
        'long_ru': 'Республика Экваториальная Гвинея',
        'a2': 'GQ',
        'a3': 'GNQ',
        'num': 226,
        'tld': '.gq',
    },
    {
        'short_en': 'Eritrea',
        'long_en': 'The State of Eritrea',
        'short_ru': 'Эритрея',
        'long_ru': 'Государство Эритрея',
        'a2': 'ER',
        'a3': 'ERI',
        'num': 232,
        'tld': '.er',
    },
    {
        'short_en': 'Estonia',
        'long_en': 'The Republic of Estonia',
        'short_ru': 'Эстония',
        'long_ru': 'Эстонская Республика',
        'a2': 'EE',
        'a3': 'EST',
        'num': 233,
        'tld': '.ee',
    },
    {
        'short_en': 'Eswatini',
        'long_en': 'The Kingdom of Eswatini',
        'short_ru': 'Эсватини',
        'long_ru': 'Королевство Эсватини',
        'a2': 'SZ',
        'a3': 'SWZ',
        'num': 748,
        'tld': '.sz',
    },
    {
        'short_en': 'Ethiopia',
        'long_en': 'The Federal Democratic Republic of Ethiopia',
        'short_ru': 'Эфиопия',
        'long_ru': 'Федеративная Демократическая Республика Эфиопия',
        'a2': 'ET',
        'a3': 'ETH',
        'num': 231,
        'tld': '.et',
    },
    {
        'short_en': 'Falkland Islands',
        'long_en': 'The Falkland Islands',
        'short_ru': 'Фолклендские Острова (Мальвинские)',
        'long_ru': 'Фолклендские Острова (Мальвинские)',
        'a2': 'FK',
        'a3': 'FLK',
        'num': 238,
        'tld': '.fk',
    },
    {
        'short_en': 'Faroe Islands',
        'long_en': 'The Faroe Islands',
        'short_ru': 'Фарерские Острова',
        'long_ru': 'Фарерские Острова',
        'a2': 'FO',
        'a3': 'FRO',
        'num': 234,
        'tld': '.fo',
    },
    {
        'short_en': 'Fiji',
        'long_en': 'The Republic of Fiji',
        'short_ru': 'Фиджи',
        'long_ru': 'Республика Фиджи',
        'a2': 'FJ',
        'a3': 'FJI',
        'num': 242,
        'tld': '.fj',
    },
    {
        'short_en': 'Finland',
        'long_en': 'The Republic of Finland',
        'short_ru': 'Финляндия',
        'long_ru': 'Финляндская Республика',
        'a2': 'FI',
        'a3': 'FIN',
        'num': 246,
        'tld': '.fi',
    },
    {
        'short_en': 'France',
        'long_en': 'The French Republic',
        'short_ru': 'Франция',
        'long_ru': 'Французская Республика',
        'a2': 'FR',
        'a3': 'FRA',
        'num': 250,
        'tld': '.fr',
    },
    {
        'short_en': 'French Guiana',
        'long_en': 'Guyane',
        'short_ru': 'Французская Гвиана',
        'long_ru': 'Французская Гвиана',
        'a2': 'GF',
        'a3': 'GUF',
        'num': 254,
        'tld': '.gf',
    },
    {
        'short_en': 'French Polynesia',
        'long_en': 'French Polynesia',
        'short_ru': 'Французская Полинезия',
        'long_ru': 'Французская Полинезия',
        'a2': 'PF',
        'a3': 'PYF',
        'num': 258,
        'tld': '.pf',
    },
    {
        'short_en': 'French Southern Territories',
        'long_en': 'The French Southern and Antarctic Lands',
        'short_ru': 'Французские Южные Территории',
        'long_ru': 'Французские Южные Территории',
        'a2': 'TF',
        'a3': 'ATF',
        'num': 260,
        'tld': '.tf',
    },
    {
        'short_en': 'Gabon',
        'long_en': 'The Gabonese Republic',
        'short_ru': 'Габон',
        'long_ru': 'Габонская Республика',
        'a2': 'GA',
        'a3': 'GAB',
        'num': 266,
        'tld': '.ga',
    },
    {
        'short_en': 'Gambia',
        'long_en': 'The Republic of The Gambia',
        'short_ru': 'Гамбия',
        'long_ru': 'Республика Гамбия',
        'a2': 'GM',
        'a3': 'GMB',
        'num': 270,
        'tld': '.gm',
    },
    {
        'short_en': 'Georgia',
        'long_en': 'Georgia',
        'short_ru': 'Грузия',
        'long_ru': 'Грузия',
        'a2': 'GE',
        'a3': 'GEO',
        'num': 268,
        'tld': '.ge',
    },
    {
        'short_en': 'Germany',
        'long_en': 'The Federal Republic of Germany',
        'short_ru': 'Германия',
        'long_ru': 'Федеративная Республика Германия',
        'a2': 'DE',
        'a3': 'DEU',
        'num': 276,
        'tld': '.de',
    },
    {
        'short_en': 'Ghana',
        'long_en': 'The Republic of Ghana',
        'short_ru': 'Гана',
        'long_ru': 'Республика Гана',
        'a2': 'GH',
        'a3': 'GHA',
        'num': 288,
        'tld': '.gh',
    },
    {
        'short_en': 'Gibraltar',
        'long_en': 'Gibraltar',
        'short_ru': 'Гибралтар',
        'long_ru': 'Гибралтар',
        'a2': 'GI',
        'a3': 'GIB',
        'num': 292,
        'tld': '.gi',
    },
    {
        'short_en': 'Greece',
        'long_en': 'The Hellenic Republic',
        'short_ru': 'Греция',
        'long_ru': 'Греческая Республика',
        'a2': 'GR',
        'a3': 'GRC',
        'num': 300,
        'tld': '.gr',
    },
    {
        'short_en': 'Greenland',
        'long_en': 'Kalaallit Nunaat',
        'short_ru': 'Гренландия',
        'long_ru': 'Гренландия',
        'a2': 'GL',
        'a3': 'GRL',
        'num': 304,
        'tld': '.gl',
    },
    {
        'short_en': 'Grenada',
        'long_en': 'Grenada',
        'short_ru': 'Гренада',
        'long_ru': 'Гренада',
        'a2': 'GD',
        'a3': 'GRD',
        'num': 308,
        'tld': '.gd',
    },
    {
        'short_en': 'Guadeloupe',
        'long_en': 'Guadeloupe',
        'short_ru': 'Гваделупа',
        'long_ru': 'Гваделупа',
        'a2': 'GP',
        'a3': 'GLP',
        'num': 312,
        'tld': '.gp',
    },
    {
        'short_en': 'Guam',
        'long_en': 'The Territory of Guam',
        'short_ru': 'Гуам',
        'long_ru': 'Гуам',
        'a2': 'GU',
        'a3': 'GUM',
        'num': 316,
        'tld': '.gu',
    },
    {
        'short_en': 'Guatemala',
        'long_en': 'The Republic of Guatemala',
        'short_ru': 'Гватемала',
        'long_ru': 'Республика Гватемала',
        'a2': 'GT',
        'a3': 'GTM',
        'num': 320,
        'tld': '.gt',
    },
    {
        'short_en': 'Guernsey',
        'long_en': 'The Bailiwick of Guernsey',
        'short_ru': 'Гернси',
        'long_ru': 'Гернси',
        'a2': 'GG',
        'a3': 'GGY',
        'num': 831,
        'tld': '.gg',
    },
    {
        'short_en': 'Guinea',
        'long_en': 'The Republic of Guinea',
        'short_ru': 'Гвинея',
        'long_ru': 'Гвинейская Республика',
        'a2': 'GN',
        'a3': 'GIN',
        'num': 324,
        'tld': '.gn',
    },
    {
        'short_en': 'Guinea-Bissau',
        'long_en': 'The Republic of Guinea-Bissau',
        'short_ru': 'Гвинея-Бисау',
        'long_ru': 'Республика Гвинея-Бисау',
        'a2': 'GW',
        'a3': 'GNB',
        'num': 624,
        'tld': '.gw',
    },
    {
        'short_en': 'Guyana',
        'long_en': 'The Co-operative Republic of Guyana',
        'short_ru': 'Гайана',
        'long_ru': 'Республика Гайана',
        'a2': 'GY',
        'a3': 'GUY',
        'num': 328,
        'tld': '.gy',
    },
    {
        'short_en': 'Haiti',
        'long_en': 'The Republic of Haiti',
        'short_ru': 'Гаити',
        'long_ru': 'Республика Гаити',
        'a2': 'HT',
        'a3': 'HTI',
        'num': 332,
        'tld': '.ht',
    },
    {
        'short_en': 'Heard Island and McDonald Islands',
        'long_en': 'The Territory of Heard Island and McDonald Islands',
        'short_ru': 'Остров Херд и Острова Макдональд',
        'long_ru': 'Остров Херд и Острова Макдональд',
        'a2': 'HM',
        'a3': 'HMD',
        'num': 334,
        'tld': '.hm',
    },
    {
        'short_en': 'Holy See',
        'long_en': 'The Holy See',
        'short_ru': 'Папский Престол (Государство - Город Ватикан)',
        'long_ru': 'Папский Престол (Государство - Город Ватикан)',
        'a2': 'VA',
        'a3': 'VAT',
        'num': 336,
        'tld': '.va',
    },
    {
        'short_en': 'Honduras',
        'long_en': 'The Republic of Honduras',
        'short_ru': 'Гондурас',
        'long_ru': 'Республика Гондурас',
        'a2': 'HN',
        'a3': 'HND',
        'num': 340,
        'tld': '.hn',
    },
    {
        'short_en': 'Hong Kong',
        'long_en': 'The Hong Kong Special Administrative Region of China',
        'short_ru': 'Гонконг',
        'long_ru': (
            'Специальный Административный Район Гонконг Китайской Народной Республики'
        ),
        'a2': 'HK',
        'a3': 'HKG',
        'num': 344,
        'tld': '.hk',
    },
    {
        'short_en': 'Hungary',
        'long_en': 'Hungary',
        'short_ru': 'Венгрия',
        'long_ru': 'Венгрия',
        'a2': 'HU',
        'a3': 'HUN',
        'num': 348,
        'tld': '.hu',
    },
    {
        'short_en': 'Iceland',
        'long_en': 'Iceland',
        'short_ru': 'Исландия',
        'long_ru': 'Республика Исландия',
        'a2': 'IS',
        'a3': 'ISL',
        'num': 352,
        'tld': '.is',
    },
    {
        'short_en': 'India',
        'long_en': 'The Republic of India',
        'short_ru': 'Индия',
        'long_ru': 'Республика Индия',
        'a2': 'IN',
        'a3': 'IND',
        'num': 356,
        'tld': '.in',
    },
    {
        'short_en': 'Indonesia',
        'long_en': 'The Republic of Indonesia',
        'short_ru': 'Индонезия',
        'long_ru': 'Республика Индонезия',
        'a2': 'ID',
        'a3': 'IDN',
        'num': 360,
        'tld': '.id',
    },
    {
        'short_en': 'Iran (Islamic Republic of)',
        'long_en': 'The Islamic Republic of Iran',
        'short_ru': 'Иран',
        'long_ru': 'Исламская республика Иран',
        'a2': 'IR',
        'a3': 'IRN',
        'num': 364,
        'tld': '.ir',
    },
    {
        'short_en': 'Iraq',
        'long_en': 'The Republic of Iraq',
        'short_ru': 'Ирак',
        'long_ru': 'Республика Ирак',
        'a2': 'IQ',
        'a3': 'IRQ',
        'num': 368,
        'tld': '.iq',
    },
    {
        'short_en': 'Ireland',
        'long_en': 'Ireland',
        'short_ru': 'Ирландия',
        'long_ru': 'Ирландия',
        'a2': 'IE',
        'a3': 'IRL',
        'num': 372,
        'tld': '.ie',
    },
    {
        'short_en': 'Isle of Man',
        'long_en': 'The Isle of Man',
        'short_ru': 'Остров Мэн',
        'long_ru': 'Остров Мэн',
        'a2': 'IM',
        'a3': 'IMN',
        'num': 833,
        'tld': '.im',
    },
    {
        'short_en': 'Israel',
        'long_en': 'The State of Israel',
        'short_ru': 'Израиль',
        'long_ru': 'Государство Израиль',
        'a2': 'IL',
        'a3': 'ISR',
        'num': 376,
        'tld': '.il',
    },
    {
        'short_en': 'Italy',
        'long_en': 'The Italian Republic',
        'short_ru': 'Италия',
        'long_ru': 'Итальянская Республика',
        'a2': 'IT',
        'a3': 'ITA',
        'num': 380,
        'tld': '.it',
    },
    {
        'short_en': 'Jamaica',
        'long_en': 'Jamaica',
        'short_ru': 'Ямайка',
        'long_ru': 'Ямайка',
        'a2': 'JM',
        'a3': 'JAM',
        'num': 388,
        'tld': '.jm',
    },
    {
        'short_en': 'Japan',
        'long_en': 'Japan',
        'short_ru': 'Япония',
        'long_ru': 'Япония',
        'a2': 'JP',
        'a3': 'JPN',
        'num': 392,
        'tld': '.jp',
    },
    {
        'short_en': 'Jersey',
        'long_en': 'The Bailiwick of Jersey',
        'short_ru': 'Джерси',
        'long_ru': 'Джерси',
        'a2': 'JE',
        'a3': 'JEY',
        'num': 832,
        'tld': '.je',
    },
    {
        'short_en': 'Jordan',
        'long_en': 'The Hashemite Kingdom of Jordan',
        'short_ru': 'Иордания',
        'long_ru': 'Иорданское Хашимитское Королевство',
        'a2': 'JO',
        'a3': 'JOR',
        'num': 400,
        'tld': '.jo',
    },
    {
        'short_en': 'Kazakhstan',
        'long_en': 'The Republic of Kazakhstan',
        'short_ru': 'Казахстан',
        'long_ru': 'Республика Казахстан',
        'a2': 'KZ',
        'a3': 'KAZ',
        'num': 398,
        'tld': '.kz',
    },
    {
        'short_en': 'Kenya',
        'long_en': 'The Republic of Kenya',
        'short_ru': 'Кения',
        'long_ru': 'Республика Кения',
        'a2': 'KE',
        'a3': 'KEN',
        'num': 404,
        'tld': '.ke',
    },
    {
        'short_en': 'Kiribati',
        'long_en': 'The Republic of Kiribati',
        'short_ru': 'Кирибати',
        'long_ru': 'Республика Кирибати',
        'a2': 'KI',
        'a3': 'KIR',
        'num': 296,
        'tld': '.ki',
    },
    {
        'short_en': "Korea (the Democratic People's Republic of)",
        'long_en': "The Democratic People's Republic of Korea",
        'short_ru': 'Корея, Народно-Демократическая Республика',
        'long_ru': 'Корейская Народно-Демократическая Республика',
        'a2': 'KP',
        'a3': 'PRK',
        'num': 408,
        'tld': '.kp',
    },
    {
        'short_en': 'Korea (the Republic of)',
        'long_en': 'The Republic of Korea',
        'short_ru': 'Корея, Республика',
        'long_ru': 'Республика Корея',
        'a2': 'KR',
        'a3': 'KOR',
        'num': 410,
        'tld': '.kr',
    },
    {
        'short_en': 'Kuwait',
        'long_en': 'The State of Kuwait',
        'short_ru': 'Кувейт',
        'long_ru': 'Государство Кувейт',
        'a2': 'KW',
        'a3': 'KWT',
        'num': 414,
        'tld': '.kw',
    },
    {
        'short_en': 'Kyrgyzstan',
        'long_en': 'The Kyrgyz Republic',
        'short_ru': 'Киргизия',
        'long_ru': 'Киргизская Республика',
        'a2': 'KG',
        'a3': 'KGZ',
        'num': 417,
        'tld': '.kg',
    },
    {
        'short_en': "Lao People's Democratic Republic",
        'long_en': "The Lao People's Democratic Republic",
        'short_ru': 'Лаос',
        'long_ru': 'Лаосская Народно-Демократическая Республика',
        'a2': 'LA',
        'a3': 'LAO',
        'num': 418,
        'tld': '.la',
    },
    {
        'short_en': 'Latvia',
        'long_en': 'The Republic of Latvia',
        'short_ru': 'Латвия',
        'long_ru': 'Латвийская Республика',
        'a2': 'LV',
        'a3': 'LVA',
        'num': 428,
        'tld': '.lv',
    },
    {
        'short_en': 'Lebanon',
        'long_en': 'The Lebanese Republic',
        'short_ru': 'Ливан',
        'long_ru': 'Ливанская Республика',
        'a2': 'LB',
        'a3': 'LBN',
        'num': 422,
        'tld': '.lb',
    },
    {
        'short_en': 'Lesotho',
        'long_en': 'The Kingdom of Lesotho',
        'short_ru': 'Лесото',
        'long_ru': 'Королевство Лесото',
        'a2': 'LS',
        'a3': 'LSO',
        'num': 426,
        'tld': '.ls',
    },
    {
        'short_en': 'Liberia',
        'long_en': 'The Republic of Liberia',
        'short_ru': 'Либерия',
        'long_ru': 'Республика Либерия',
        'a2': 'LR',
        'a3': 'LBR',
        'num': 430,
        'tld': '.lr',
    },
    {
        'short_en': 'Libya',
        'long_en': 'The State of Libya',
        'short_ru': 'Ливия',
        'long_ru': 'Государство Ливия',
        'a2': 'LY',
        'a3': 'LBY',
        'num': 434,
        'tld': '.ly',
    },
    {
        'short_en': 'Liechtenstein',
        'long_en': 'The Principality of Liechtenstein',
        'short_ru': 'Лихтенштейн',
        'long_ru': 'Княжество Лихтенштейн',
        'a2': 'LI',
        'a3': 'LIE',
        'num': 438,
        'tld': '.li',
    },
    {
        'short_en': 'Lithuania',
        'long_en': 'The Republic of Lithuania',
        'short_ru': 'Литва',
        'long_ru': 'Литовская Республика',
        'a2': 'LT',
        'a3': 'LTU',
        'num': 440,
        'tld': '.lt',
    },
    {
        'short_en': 'Luxembourg',
        'long_en': 'The Grand Duchy of Luxembourg',
        'short_ru': 'Люксембург',
        'long_ru': 'Великое Герцогство Люксембург',
        'a2': 'LU',
        'a3': 'LUX',
        'num': 442,
        'tld': '.lu',
    },
    {
        'short_en': 'Macao',
        'long_en': 'The Macao Special Administrative Region of China',
        'short_ru': 'Макао',
        'long_ru': (
            'Специальный Административный Район Макао Китайской Народной Республики'
        ),
        'a2': 'MO',
        'a3': 'MAC',
        'num': 446,
        'tld': '.mo',
    },
    {
        'short_en': 'Madagascar',
        'long_en': 'The Republic of Madagascar',
        'short_ru': 'Мадагаскар',
        'long_ru': 'Республика Мадагаскар',
        'a2': 'MG',
        'a3': 'MDG',
        'num': 450,
        'tld': '.mg',
    },
    {
        'short_en': 'Malawi',
        'long_en': 'The Republic of Malawi',
        'short_ru': 'Малави',
        'long_ru': 'Республика Малави',
        'a2': 'MW',
        'a3': 'MWI',
        'num': 454,
        'tld': '.mw',
    },
    {
        'short_en': 'Malaysia',
        'long_en': 'Malaysia',
        'short_ru': 'Малайзия',
        'long_ru': 'Малайзия',
        'a2': 'MY',
        'a3': 'MYS',
        'num': 458,
        'tld': '.my',
    },
    {
        'short_en': 'Maldives',
        'long_en': 'The Republic of Maldives',
        'short_ru': 'Мальдивы',
        'long_ru': 'Мальдивская Республика',
        'a2': 'MV',
        'a3': 'MDV',
        'num': 462,
        'tld': '.mv',
    },
    {
        'short_en': 'Mali',
        'long_en': 'The Republic of Mali',
        'short_ru': 'Мали',
        'long_ru': 'Республика Мали',
        'a2': 'ML',
        'a3': 'MLI',
        'num': 466,
        'tld': '.ml',
    },
    {
        'short_en': 'Malta',
        'long_en': 'The Republic of Malta',
        'short_ru': 'Мальта',
        'long_ru': 'Республика Мальта',
        'a2': 'MT',
        'a3': 'MLT',
        'num': 470,
        'tld': '.mt',
    },
    {
        'short_en': 'Marshall Islands',
        'long_en': 'The Republic of the Marshall Islands',
        'short_ru': 'Маршалловы Острова',
        'long_ru': 'Республика Маршалловы Острова',
        'a2': 'MH',
        'a3': 'MHL',
        'num': 584,
        'tld': '.mh',
    },
    {
        'short_en': 'Martinique',
        'long_en': 'Martinique',
        'short_ru': 'Мартиника',
        'long_ru': 'Мартиника',
        'a2': 'MQ',
        'a3': 'MTQ',
        'num': 474,
        'tld': '.mq',
    },
    {
        'short_en': 'Mauritania',
        'long_en': 'The Islamic Republic of Mauritania',
        'short_ru': 'Мавритания',
        'long_ru': 'Исламская Республика Мавритания',
        'a2': 'MR',
        'a3': 'MRT',
        'num': 478,
        'tld': '.mr',
    },
    {
        'short_en': 'Mauritius',
        'long_en': 'The Republic of Mauritius',
        'short_ru': 'Маврикий',
        'long_ru': 'Республика Маврикий',
        'a2': 'MU',
        'a3': 'MUS',
        'num': 480,
        'tld': '.mu',
    },
    {
        'short_en': 'Mayotte',
        'long_en': 'The Department of Mayotte',
        'short_ru': 'Майотта',
        'long_ru': 'Майотта',
        'a2': 'YT',
        'a3': 'MYT',
        'num': 175,
        'tld': '.yt',
    },
    {
        'short_en': 'Mexico',
        'long_en': 'The United Mexican States',
        'short_ru': 'Мексика',
        'long_ru': 'Мексиканские Соединенные Штаты',
        'a2': 'MX',
        'a3': 'MEX',
        'num': 484,
        'tld': '.mx',
    },
    {
        'short_en': 'Micronesia (Federated States of)',
        'long_en': 'The Federated States of Micronesia',
        'short_ru': 'Микронезия',
        'long_ru': 'Федеративные Штаты Микронезии',
        'a2': 'FM',
        'a3': 'FSM',
        'num': 583,
        'tld': '.fm',
    },
    {
        'short_en': 'Moldova (the Republic of)',
        'long_en': 'The Republic of Moldova',
        'short_ru': 'Молдова',
        'long_ru': 'Республика Молдова',
        'a2': 'MD',
        'a3': 'MDA',
        'num': 498,
        'tld': '.md',
    },
    {
        'short_en': 'Monaco',
        'long_en': 'The Principality of Monaco',
        'short_ru': 'Монако',
        'long_ru': 'Княжество Монако',
        'a2': 'MC',
        'a3': 'MCO',
        'num': 492,
        'tld': '.mc',
    },
    {
        'short_en': 'Mongolia',
        'long_en': 'Mongolia',
        'short_ru': 'Монголия',
        'long_ru': 'Монголия',
        'a2': 'MN',
        'a3': 'MNG',
        'num': 496,
        'tld': '.mn',
    },
    {
        'short_en': 'Montenegro',
        'long_en': 'Montenegro',
        'short_ru': 'Черногория',
        'long_ru': 'Черногория',
        'a2': 'ME',
        'a3': 'MNE',
        'num': 499,
        'tld': '.me',
    },
    {
        'short_en': 'Montserrat',
        'long_en': 'Montserrat',
        'short_ru': 'Монтсеррат',
        'long_ru': 'Монтсеррат',
        'a2': 'MS',
        'a3': 'MSR',
        'num': 500,
        'tld': '.ms',
    },
    {
        'short_en': 'Morocco',
        'long_en': 'The Kingdom of Morocco',
        'short_ru': 'Марокко',
        'long_ru': 'Королевство Марокко',
        'a2': 'MA',
        'a3': 'MAR',
        'num': 504,
        'tld': '.ma',
    },
    {
        'short_en': 'Mozambique',
        'long_en': 'The Republic of Mozambique',
        'short_ru': 'Мозамбик',
        'long_ru': 'Республика Мозамбик',
        'a2': 'MZ',
        'a3': 'MOZ',
        'num': 508,
        'tld': '.mz',
    },
    {
        'short_en': 'Myanmar',
        'long_en': 'The Republic of the Union of Myanmar',
        'short_ru': 'Мьянма',
        'long_ru': 'Республика Союза Мьянма',
        'a2': 'MM',
        'a3': 'MMR',
        'num': 104,
        'tld': '.mm',
    },
    {
        'short_en': 'Namibia',
        'long_en': 'The Republic of Namibia',
        'short_ru': 'Намибия',
        'long_ru': 'Республика Намибия',
        'a2': 'NA',
        'a3': 'NAM',
        'num': 516,
        'tld': '.na',
    },
    {
        'short_en': 'Nauru',
        'long_en': 'The Republic of Nauru',
        'short_ru': 'Науру',
        'long_ru': 'Республика Науру',
        'a2': 'NR',
        'a3': 'NRU',
        'num': 520,
        'tld': '.nr',
    },
    {
        'short_en': 'Nepal',
        'long_en': 'The Federal Democratic Republic of Nepal',
        'short_ru': 'Непал',
        'long_ru': 'Федеративная Демократическая Республика Непал',
        'a2': 'NP',
        'a3': 'NPL',
        'num': 524,
        'tld': '.np',
    },
    {
        'short_en': 'Netherlands, Kingdom of the',
        'long_en': 'The Kingdom of the Netherlands',
        'short_ru': 'Нидерланды',
        'long_ru': 'Королевство Нидерландов',
        'a2': 'NL',
        'a3': 'NLD',
        'num': 528,
        'tld': '.nl',
    },
    {
        'short_en': 'New Caledonia',
        'long_en': 'New Caledonia',
        'short_ru': 'Новая Каледония',
        'long_ru': 'Новая Каледония',
        'a2': 'NC',
        'a3': 'NCL',
        'num': 540,
        'tld': '.nc',
    },
    {
        'short_en': 'New Zealand',
        'long_en': 'New Zealand',
        'short_ru': 'Новая Зеландия',
        'long_ru': 'Новая Зеландия',
        'a2': 'NZ',
        'a3': 'NZL',
        'num': 554,
        'tld': '.nz',
    },
    {
        'short_en': 'Nicaragua',
        'long_en': 'The Republic of Nicaragua',
        'short_ru': 'Никарагуа',
        'long_ru': 'Республика Никарагуа',
        'a2': 'NI',
        'a3': 'NIC',
        'num': 558,
        'tld': '.ni',
    },
    {
        'short_en': 'Niger',
        'long_en': 'The Republic of the Niger',
        'short_ru': 'Нигер',
        'long_ru': 'Республика Нигер',
        'a2': 'NE',
        'a3': 'NER',
        'num': 562,
        'tld': '.ne',
    },
    {
        'short_en': 'Nigeria',
        'long_en': 'The Federal Republic of Nigeria',
        'short_ru': 'Нигерия',
        'long_ru': 'Федеративная Республика Нигерия',
        'a2': 'NG',
        'a3': 'NGA',
        'num': 566,
        'tld': '.ng',
    },
    {
        'short_en': 'Niue',
        'long_en': 'Niue',
        'short_ru': 'Ниуэ',
        'long_ru': 'Республика Ниуэ',
        'a2': 'NU',
        'a3': 'NIU',
        'num': 570,
        'tld': '.nu',
    },
    {
        'short_en': 'Norfolk Island',
        'long_en': 'The Territory of Norfolk Island',
        'short_ru': 'Остров Норфолк',
        'long_ru': 'Остров Норфолк',
        'a2': 'NF',
        'a3': 'NFK',
        'num': 574,
        'tld': '.nf',
    },
    {
        'short_en': 'North Macedonia',
        'long_en': 'The Republic of North Macedonia',
        'short_ru': 'Северная Македония',
        'long_ru': 'Республика Северная Македония',
        'a2': 'MK',
        'a3': 'MKD',
        'num': 807,
        'tld': '.mk',
    },
    {
        'short_en': 'Northern Mariana Islands',
        'long_en': 'The Commonwealth of the Northern Mariana Islands',
        'short_ru': 'Северные Марианские Острова',
        'long_ru': 'Содружество Северных Марианских Островов',
        'a2': 'MP',
        'a3': 'MNP',
        'num': 580,
        'tld': '.mp',
    },
    {
        'short_en': 'Norway',
        'long_en': 'The Kingdom of Norway',
        'short_ru': 'Норвегия',
        'long_ru': 'Королевство Норвегия',
        'a2': 'NO',
        'a3': 'NOR',
        'num': 578,
        'tld': '.no',
    },
    {
        'short_en': 'Oman',
        'long_en': 'The Sultanate of Oman',
        'short_ru': 'Оман',
        'long_ru': 'Султанат Оман',
        'a2': 'OM',
        'a3': 'OMN',
        'num': 512,
        'tld': '.om',
    },
    {
        'short_en': 'Pakistan',
        'long_en': 'The Islamic Republic of Pakistan',
        'short_ru': 'Пакистан',
        'long_ru': 'Исламская Республика Пакистан',
        'a2': 'PK',
        'a3': 'PAK',
        'num': 586,
        'tld': '.pk',
    },
    {
        'short_en': 'Palau',
        'long_en': 'The Republic of Palau',
        'short_ru': 'Палау',
        'long_ru': 'Республика Палау',
        'a2': 'PW',
        'a3': 'PLW',
        'num': 585,
        'tld': '.pw',
    },
    {
        'short_en': 'Palestine, State of',
        'long_en': 'The State of Palestine',
        'short_ru': 'Палестина',
        'long_ru': 'Государство Палестина',
        'a2': 'PS',
        'a3': 'PSE',
        'num': 275,
        'tld': '.ps',
    },
    {
        'short_en': 'Panama',
        'long_en': 'The Republic of Panamá',
        'short_ru': 'Панама',
        'long_ru': 'Республика Панама',
        'a2': 'PA',
        'a3': 'PAN',
        'num': 591,
        'tld': '.pa',
    },
    {
        'short_en': 'Papua New Guinea',
        'long_en': 'The Independent State of Papua New Guinea',
        'short_ru': 'Папуа-Новая Гвинея',
        'long_ru': 'Независимое Государство  Папуа Новая Гвинея',
        'a2': 'PG',
        'a3': 'PNG',
        'num': 598,
        'tld': '.pg',
    },
    {
        'short_en': 'Paraguay',
        'long_en': 'The Republic of Paraguay',
        'short_ru': 'Парагвай',
        'long_ru': 'Республика Парагвай',
        'a2': 'PY',
        'a3': 'PRY',
        'num': 600,
        'tld': '.py',
    },
    {
        'short_en': 'Peru',
        'long_en': 'The Republic of Perú',
        'short_ru': 'Перу',
        'long_ru': 'Республика Перу',
        'a2': 'PE',
        'a3': 'PER',
        'num': 604,
        'tld': '.pe',
    },
    {
        'short_en': 'Philippines',
        'long_en': 'The Republic of the Philippines',
        'short_ru': 'Филиппины',
        'long_ru': 'Республика Филиппины',
        'a2': 'PH',
        'a3': 'PHL',
        'num': 608,
        'tld': '.ph',
    },
    {
        'short_en': 'Pitcairn',
        'long_en': 'The Pitcairn, Henderson, Ducie and Oeno Islands',
        'short_ru': 'Питкерн',
        'long_ru': 'Питкерн',
        'a2': 'PN',
        'a3': 'PCN',
        'num': 612,
        'tld': '.pn',
    },
    {
        'short_en': 'Poland',
        'long_en': 'The Republic of Poland',
        'short_ru': 'Польша',
        'long_ru': 'Республика Польша',
        'a2': 'PL',
        'a3': 'POL',
        'num': 616,
        'tld': '.pl',
    },
    {
        'short_en': 'Portugal',
        'long_en': 'The Portuguese Republic',
        'short_ru': 'Португалия',
        'long_ru': 'Португальская Республика',
        'a2': 'PT',
        'a3': 'PRT',
        'num': 620,
        'tld': '.pt',
    },
    {
        'short_en': 'Puerto Rico',
        'long_en': 'The Commonwealth of Puerto Rico',
        'short_ru': 'Пуэрто-Рико',
        'long_ru': 'Пуэрто-Рико',
        'a2': 'PR',
        'a3': 'PRI',
        'num': 630,
        'tld': '.pr',
    },
    {
        'short_en': 'Qatar',
        'long_en': 'The State of Qatar',
        'short_ru': 'Катар',
        'long_ru': 'Государство Катар',
        'a2': 'QA',
        'a3': 'QAT',
        'num': 634,
        'tld': '.qa',
    },
    {
        'short_en': 'Réunion',
        'long_en': 'Réunion',
        'short_ru': 'Реюньон',
        'long_ru': 'Реюньон',
        'a2': 'RE',
        'a3': 'REU',
        'num': 638,
        'tld': '.re',
    },
    {
        'short_en': 'Romania',
        'long_en': 'Romania',
        'short_ru': 'Румыния',
        'long_ru': 'Румыния',
        'a2': 'RO',
        'a3': 'ROU',
        'num': 642,
        'tld': '.ro',
    },
    {
        'short_en': 'Russian Federation',
        'long_en': 'The Russian Federation',
        'short_ru': 'Россия',
        'long_ru': 'Российская Федерация',
        'a2': 'RU',
        'a3': 'RUS',
        'num': 643,
        'tld': '.ru',
    },
    {
        'short_en': 'Rwanda',
        'long_en': 'The Republic of Rwanda',
        'short_ru': 'Руанда',
        'long_ru': 'Руандийская Республика',
        'a2': 'RW',
        'a3': 'RWA',
        'num': 646,
        'tld': '.rw',
    },
    {
        'short_en': 'Saint Barthélemy',
        'long_en': 'The Collectivity of Saint-Barthélemy',
        'short_ru': 'Сен-Бартелеми',
        'long_ru': 'Сен-Бартелеми',
        'a2': 'BL',
        'a3': 'BLM',
        'num': 652,
        'tld': '.bl',
    },
    {
        'short_en': 'Saint Helena',
        'long_en': 'Saint Helena, Ascension and Tristan da Cunha',
        'short_ru': 'Святая Елена, Остров Вознесения, Тристан-Да-Кунья',
        'long_ru': 'Святая Елена, Остров Вознесения, Тристан-Да-Кунья',
        'a2': 'SH',
        'a3': 'SHN',
        'num': 654,
        'tld': '.sh',
    },
    {
        'short_en': 'Saint Kitts and Nevis',
        'long_en': 'Saint Kitts and Nevis',
        'short_ru': 'Сент-Китс и Невис',
        'long_ru': 'Сент-Китс и Невис',
        'a2': 'KN',
        'a3': 'KNA',
        'num': 659,
        'tld': '.kn',
    },
    {
        'short_en': 'Saint Lucia',
        'long_en': 'Saint Lucia',
        'short_ru': 'Сент-Люсия',
        'long_ru': 'Сент-Люсия',
        'a2': 'LC',
        'a3': 'LCA',
        'num': 662,
        'tld': '.lc',
    },
    {
        'short_en': 'Saint Martin (French part)',
        'long_en': 'The Collectivity of Saint-Martin',
        'short_ru': 'Сен-Мартен (Французская Часть)',
        'long_ru': 'Сен-Мартен (Французская Часть)',
        'a2': 'MF',
        'a3': 'MAF',
        'num': 663,
        'tld': '.mf',
    },
    {
        'short_en': 'Saint Pierre and Miquelon',
        'long_en': 'The Overseas Collectivity of Saint-Pierre and Miquelon',
        'short_ru': 'Сен-Пьер И Микелон',
        'long_ru': 'Сен-Пьер И Микелон',
        'a2': 'PM',
        'a3': 'SPM',
        'num': 666,
        'tld': '.pm',
    },
    {
        'short_en': 'Saint Vincent and the Grenadines',
        'long_en': 'Saint Vincent and the Grenadines',
        'short_ru': 'Сент-Винсент и Гренадины',
        'long_ru': 'Сент-Винсент и Гренадины',
        'a2': 'VC',
        'a3': 'VCT',
        'num': 670,
        'tld': '.vc',
    },
    {
        'short_en': 'Samoa',
        'long_en': 'The Independent State of Samoa',
        'short_ru': 'Самоа',
        'long_ru': 'Независимое Государство Самоа',
        'a2': 'WS',
        'a3': 'WSM',
        'num': 882,
        'tld': '.ws',
    },
    {
        'short_en': 'San Marino',
        'long_en': 'The Republic of San Marino',
        'short_ru': 'Сан-Марино',
        'long_ru': 'Республика Сан-Марино',
        'a2': 'SM',
        'a3': 'SMR',
        'num': 674,
        'tld': '.sm',
    },
    {
        'short_en': 'Sao Tome and Principe',
        'long_en': 'The Democratic Republic of São Tomé and Príncipe',
        'short_ru': 'Сан-Томе и Принсипи',
        'long_ru': 'Демократическая Республика Сан-Томе и Принсипи',
        'a2': 'ST',
        'a3': 'STP',
        'num': 678,
        'tld': '.st',
    },
    {
        'short_en': 'Saudi Arabia',
        'long_en': 'The Kingdom of Saudi Arabia',
        'short_ru': 'Саудовская Аравия',
        'long_ru': 'Королевство Саудовская Аравия',
        'a2': 'SA',
        'a3': 'SAU',
        'num': 682,
        'tld': '.sa',
    },
    {
        'short_en': 'Senegal',
        'long_en': 'The Republic of Senegal',
        'short_ru': 'Сенегал',
        'long_ru': 'Республика Сенегал',
        'a2': 'SN',
        'a3': 'SEN',
        'num': 686,
        'tld': '.sn',
    },
    {
        'short_en': 'Serbia',
        'long_en': 'The Republic of Serbia',
        'short_ru': 'Сербия',
        'long_ru': 'Республика Сербия',
        'a2': 'RS',
        'a3': 'SRB',
        'num': 688,
        'tld': '.rs',
    },
    {
        'short_en': 'Seychelles',
        'long_en': 'The Republic of Seychelles',
        'short_ru': 'Сейшелы',
        'long_ru': 'Республика Сейшелы',
        'a2': 'SC',
        'a3': 'SYC',
        'num': 690,
        'tld': '.sc',
    },
    {
        'short_en': 'Sierra Leone',
        'long_en': 'The Republic of Sierra Leone',
        'short_ru': 'Сьерра-Леоне',
        'long_ru': 'Республика Сьерра-Леоне',
        'a2': 'SL',
        'a3': 'SLE',
        'num': 694,
        'tld': '.sl',
    },
    {
        'short_en': 'Singapore',
        'long_en': 'The Republic of Singapore',
        'short_ru': 'Сингапур',
        'long_ru': 'Республика Сингапур',
        'a2': 'SG',
        'a3': 'SGP',
        'num': 702,
        'tld': '.sg',
    },
    {
        'short_en': 'Sint Maarten (Dutch part)',
        'long_en': 'Sint Maarten',
        'short_ru': 'Сен-Мартен (Нидерландская Часть)',
        'long_ru': 'Сен-Мартен (Нидерландская Часть)',
        'a2': 'SX',
        'a3': 'SXM',
        'num': 534,
        'tld': '.sx',
    },
    {
        'short_en': 'Slovakia',
        'long_en': 'The Slovak Republic',
        'short_ru': 'Словакия',
        'long_ru': 'Словацкая Республика',
        'a2': 'SK',
        'a3': 'SVK',
        'num': 703,
        'tld': '.sk',
    },
    {
        'short_en': 'Slovenia',
        'long_en': 'The Republic of Slovenia',
        'short_ru': 'Словения',
        'long_ru': 'Республика Словения',
        'a2': 'SI',
        'a3': 'SVN',
        'num': 705,
        'tld': '.si',
    },
    {
        'short_en': 'Solomon Islands',
        'long_en': 'The Solomon Islands',
        'short_ru': 'Соломоновы Острова',
        'long_ru': 'Соломоновы Острова',
        'a2': 'SB',
        'a3': 'SLB',
        'num': 90,
        'tld': '.sb',
    },
    {
        'short_en': 'Somalia',
        'long_en': 'The Federal Republic of Somalia',
        'short_ru': 'Сомали',
        'long_ru': 'Федеративная Республика Сомали',
        'a2': 'SO',
        'a3': 'SOM',
        'num': 706,
        'tld': '.so',
    },
    {
        'short_en': 'South Africa',
        'long_en': 'The Republic of South Africa',
        'short_ru': 'Южная Африка',
        'long_ru': 'Южно-Африканская Республика',
        'a2': 'ZA',
        'a3': 'ZAF',
        'num': 710,
        'tld': '.za',
    },
    {
        'short_en': 'South Georgia and the South Sandwich Islands',
        'long_en': 'South Georgia and the South Sandwich Islands',
        'short_ru': 'Южная Джорджия и Южные Сандвичевы Острова',
        'long_ru': 'Южная Джорджия и Южные Сандвичевы Острова',
        'a2': 'GS',
        'a3': 'SGS',
        'num': 239,
        'tld': '.gs',
    },
    {
        'short_en': 'South Sudan',
        'long_en': 'The Republic of South Sudan',
        'short_ru': 'Южный Судан',
        'long_ru': 'Республика Южный Судан',
        'a2': 'SS',
        'a3': 'SSD',
        'num': 728,
        'tld': '.ss',
    },
    {
        'short_en': 'Spain',
        'long_en': 'The Kingdom of Spain',
        'short_ru': 'Испания',
        'long_ru': 'Королевство Испания',
        'a2': 'ES',
        'a3': 'ESP',
        'num': 724,
        'tld': '.es',
    },
    {
        'short_en': 'Sri Lanka',
        'long_en': 'The Democratic Socialist Republic of Sri Lanka',
        'short_ru': 'Шри-Ланка',
        'long_ru': 'Демократическая Социалистическая Республика Шри-Ланка',
        'a2': 'LK',
        'a3': 'LKA',
        'num': 144,
        'tld': '.lk',
    },
    {
        'short_en': 'Sudan',
        'long_en': 'The Republic of the Sudan',
        'short_ru': 'Судан',
        'long_ru': 'Республика Судан',
        'a2': 'SD',
        'a3': 'SDN',
        'num': 729,
        'tld': '.sd',
    },
    {
        'short_en': 'Suriname',
        'long_en': 'The Republic of Suriname',
        'short_ru': 'Суринам',
        'long_ru': 'Республика Суринам',
        'a2': 'SR',
        'a3': 'SUR',
        'num': 740,
        'tld': '.sr',
    },
    {
        'short_en': 'Svalbard',
        'long_en': 'Svalbard and Jan Mayen',
        'short_ru': 'Шпицберген и Ян Майен',
        'long_ru': 'Шпицберген и Ян Майен',
        'a2': 'SJ',
        'a3': 'SJM',
        'num': 744,
        'tld': '',
    },
    {
        'short_en': 'Sweden',
        'long_en': 'The Kingdom of Sweden',
        'short_ru': 'Швеция',
        'long_ru': 'Королевство Швеция',
        'a2': 'SE',
        'a3': 'SWE',
        'num': 752,
        'tld': '.se',
    },
    {
        'short_en': 'Switzerland',
        'long_en': 'The Swiss Confederation',
        'short_ru': 'Швейцария',
        'long_ru': 'Швейцарская Конфедерация',
        'a2': 'CH',
        'a3': 'CHE',
        'num': 756,
        'tld': '.ch',
    },
    {
        'short_en': 'Syrian Arab Republic',
        'long_en': 'The Syrian Arab Republic',
        'short_ru': 'Сирийская Арабская Республика',
        'long_ru': 'Сирийская Арабская Республика',
        'a2': 'SY',
        'a3': 'SYR',
        'num': 760,
        'tld': '.sy',
    },
    {
        'short_en': 'Taiwan (Province of China)',
        'long_en': 'The Republic of China',
        'short_ru': 'Тайвань (Китай)',
        'long_ru': 'Тайвань (Китай)',
        'a2': 'TW',
        'a3': 'TWN',
        'num': 158,
        'tld': '.tw',
    },
    {
        'short_en': 'Tajikistan',
        'long_en': 'The Republic of Tajikistan',
        'short_ru': 'Таджикистан',
        'long_ru': 'Республика Таджикистан',
        'a2': 'TJ',
        'a3': 'TJK',
        'num': 762,
        'tld': '.tj',
    },
    {
        'short_en': 'Tanzania, the United Republic of',
        'long_en': 'The United Republic of Tanzania',
        'short_ru': 'Танзания, Объединенная Республика',
        'long_ru': 'Объединенная Республика Танзания',
        'a2': 'TZ',
        'a3': 'TZA',
        'num': 834,
        'tld': '.tz',
    },
    {
        'short_en': 'Thailand',
        'long_en': 'The Kingdom of Thailand',
        'short_ru': 'Таиланд',
        'long_ru': 'Королевство Таиланд',
        'a2': 'TH',
        'a3': 'THA',
        'num': 764,
        'tld': '.th',
    },
    {
        'short_en': 'Timor-Leste',
        'long_en': 'The Democratic Republic of Timor-Leste',
        'short_ru': 'Тимор-Лесте',
        'long_ru': 'Демократическая Республика Тимор-Лесте',
        'a2': 'TL',
        'a3': 'TLS',
        'num': 626,
        'tld': '.tl',
    },
    {
        'short_en': 'Togo',
        'long_en': 'The Togolese Republic',
        'short_ru': 'Того',
        'long_ru': 'Тоголезская Республика',
        'a2': 'TG',
        'a3': 'TGO',
        'num': 768,
        'tld': '.tg',
    },
    {
        'short_en': 'Tokelau',
        'long_en': 'Tokelau',
        'short_ru': 'Токелау',
        'long_ru': 'Токелау',
        'a2': 'TK',
        'a3': 'TKL',
        'num': 772,
        'tld': '.tk',
    },
    {
        'short_en': 'Tonga',
        'long_en': 'The Kingdom of Tonga',
        'short_ru': 'Тонга',
        'long_ru': 'Королевство Тонга',
        'a2': 'TO',
        'a3': 'TON',
        'num': 776,
        'tld': '.to',
    },
    {
        'short_en': 'Trinidad and Tobago',
        'long_en': 'The Republic of Trinidad and Tobago',
        'short_ru': 'Тринидад и Тобаго',
        'long_ru': 'Республика Тринидад и Тобаго',
        'a2': 'TT',
        'a3': 'TTO',
        'num': 780,
        'tld': '.tt',
    },
    {
        'short_en': 'Tunisia',
        'long_en': 'The Republic of Tunisia',
        'short_ru': 'Тунис',
        'long_ru': 'Тунисская Республика',
        'a2': 'TN',
        'a3': 'TUN',
        'num': 788,
        'tld': '.tn',
    },
    {
        'short_en': 'Türkiye',
        'long_en': 'The Republic of Türkiye',
        'short_ru': 'Турция',
        'long_ru': 'Турецкая Республика',
        'a2': 'TR',
        'a3': 'TUR',
        'num': 792,
        'tld': '.tr',
    },
    {
        'short_en': 'Turkmenistan',
        'long_en': 'Turkmenistan',
        'short_ru': 'Туркменистан',
        'long_ru': 'Туркменистан',
        'a2': 'TM',
        'a3': 'TKM',
        'num': 795,
        'tld': '.tm',
    },
    {
        'short_en': 'Turks and Caicos Islands',
        'long_en': 'The Turks and Caicos Islands',
        'short_ru': 'Острова Теркс и Кайкос',
        'long_ru': 'Острова Теркс и Кайкос',
        'a2': 'TC',
        'a3': 'TCA',
        'num': 796,
        'tld': '.tc',
    },
    {
        'short_en': 'Tuvalu',
        'long_en': 'Tuvalu',
        'short_ru': 'Тувалу',
        'long_ru': 'Тувалу',
        'a2': 'TV',
        'a3': 'TUV',
        'num': 798,
        'tld': '.tv',
    },
    {
        'short_en': 'Uganda',
        'long_en': 'The Republic of Uganda',
        'short_ru': 'Уганда',
        'long_ru': 'Республика Уганда',
        'a2': 'UG',
        'a3': 'UGA',
        'num': 800,
        'tld': '.ug',
    },
    {
        'short_en': 'Ukraine',
        'long_en': 'Ukraine',
        'short_ru': 'Украина',
        'long_ru': 'Украина',
        'a2': 'UA',
        'a3': 'UKR',
        'num': 804,
        'tld': '.ua',
    },
    {
        'short_en': 'United Arab Emirates',
        'long_en': 'The United Arab Emirates',
        'short_ru': 'Объединенные Арабские Эмираты',
        'long_ru': 'Объединенные Арабские Эмираты',
        'a2': 'AE',
        'a3': 'ARE',
        'num': 784,
        'tld': '.ae',
    },
    {
        'short_en': 'United Kingdom of Great Britain and Northern Ireland',
        'long_en': 'The United Kingdom of Great Britain and Northern Ireland',
        'short_ru': 'Соединенное Королевство',
        'long_ru': 'Соединенное Королевство Великобритании И Северной Ирландии',
        'a2': 'GB',
        'a3': 'GBR',
        'num': 826,
        'tld': '.gb.uk',
    },
    {
        'short_en': 'United States Minor Outlying Islands',
        'long_en': (
            'BakerIsland, HowlandIsland,JarvisIsland, JohnstonAtoll, KingmanReef, '
            'MidwayAtoll, NavassaIsland, PalmyraAtoll, andWakeIsland'
        ),
        'short_ru': 'Малые Тихоокеанские Отдаленные Острова Соединенных Штатов',
        'long_ru': 'Малые Тихоокеанские Отдаленные Острова Соединенных Штатов',
        'a2': 'UM',
        'a3': 'UMI',
        'num': 581,
        'tld': '',
    },
    {
        'short_en': 'United States of America',
        'long_en': 'The United States of America',
        'short_ru': 'США',
        'long_ru': 'Соединенные Штаты Америки',
        'a2': 'US',
        'a3': 'USA',
        'num': 840,
        'tld': '.us',
    },
    {
        'short_en': 'Uruguay',
        'long_en': 'The Oriental Republic of Uruguay',
        'short_ru': 'Уругвай',
        'long_ru': 'Восточная Республика Уругвай',
        'a2': 'UY',
        'a3': 'URY',
        'num': 858,
        'tld': '.uy',
    },
    {
        'short_en': 'Uzbekistan',
        'long_en': 'The Republic of Uzbekistan',
        'short_ru': 'Узбекистан',
        'long_ru': 'Республика Узбекистан',
        'a2': 'UZ',
        'a3': 'UZB',
        'num': 860,
        'tld': '.uz',
    },
    {
        'short_en': 'Vanuatu',
        'long_en': 'The Republic of Vanuatu',
        'short_ru': 'Вануату',
        'long_ru': 'Республика Вануату',
        'a2': 'VU',
        'a3': 'VUT',
        'num': 548,
        'tld': '.vu',
    },
    {
        'short_en': 'Venezuela (Bolivarian Republic of)',
        'long_en': 'The Bolivarian Republic of Venezuela',
        'short_ru': 'Венесуэла',
        'long_ru': 'Боливарианская Республика Венесуэла',
        'a2': 'VE',
        'a3': 'VEN',
        'num': 862,
        'tld': '.ve',
    },
    {
        'short_en': 'Viet Nam',
        'long_en': 'The Socialist Republic of Viet Nam',
        'short_ru': 'Вьетнам',
        'long_ru': 'Социалистическая Республика Вьетнам',
        'a2': 'VN',
        'a3': 'VNM',
        'num': 704,
        'tld': '.vn',
    },
    {
        'short_en': 'Virgin Islands (British)',
        'long_en': 'The Virgin Islands',
        'short_ru': 'Виргинские Острова (Британские)',
        'long_ru': 'Британские Виргинские Острова',
        'a2': 'VG',
        'a3': 'VGB',
        'num': 92,
        'tld': '.vg',
    },
    {
        'short_en': 'Virgin Islands (U.S.)',
        'long_en': 'The Virgin Islands of the United States',
        'short_ru': 'Виргинские Острова (США)',
        'long_ru': 'Виргинские Острова Соединенных Штатов',
        'a2': 'VI',
        'a3': 'VIR',
        'num': 850,
        'tld': '.vi',
    },
    {
        'short_en': 'Wallis and Futuna',
        'long_en': 'The Territory of the Wallis and Futuna Islands',
        'short_ru': 'Уоллис и Футуна',
        'long_ru': 'Уоллис и Футуна',
        'a2': 'WF',
        'a3': 'WLF',
        'num': 876,
        'tld': '.wf',
    },
    {
        'short_en': 'Western Sahara',
        'long_en': 'The Sahrawi Arab Democratic Republic',
        'short_ru': 'Западная Сахара',
        'long_ru': 'Западная Сахара',
        'a2': 'EH',
        'a3': 'ESH',
        'num': 732,
        'tld': '',
    },
    {
        'short_en': 'Yemen',
        'long_en': 'The Republic of Yemen',
        'short_ru': 'Йемен',
        'long_ru': 'Йеменская Республика',
        'a2': 'YE',
        'a3': 'YEM',
        'num': 887,
        'tld': '.ye',
    },
    {
        'short_en': 'Zambia',
        'long_en': 'The Republic of Zambia',
        'short_ru': 'Замбия',
        'long_ru': 'Республика Замбия',
        'a2': 'ZM',
        'a3': 'ZMB',
        'num': 894,
        'tld': '.zm',
    },
    {
        'short_en': 'Zimbabwe',
        'long_en': 'The Republic of Zimbabwe',
        'short_ru': 'Зимбабве',
        'long_ru': 'Республика Зимбабве',
        'a2': 'ZW',
        'a3': 'ZWE',
        'num': 716,
        'tld': '.zw',
    },
]
