# pylint: disable=too-many-lines
COUNTRYKEYS = ('short_en', 'long_en', 'short_ru', 'long_ru', 'a2', 'a3', 'num', 'tld')
COUNTRYTUPLES = (
    (
        'Afghanistan',
        'The Islamic Republic of Afghanistan',
        'Афганистан',
        'Переходное Исламское Государство Афганистан',
        'AF',
        'AFG',
        4,
        '.af',
    ),
    (
        'Åland Islands',
        'Åland',
        'Эландские Острова',
        'Эландские Острова',
        'AX',
        'ALA',
        248,
        '.ax',
    ),
    (
        'Albania',
        'The Republic of Albania',
        'Албания',
        'Республика Албания',
        'AL',
        'ALB',
        8,
        '.al',
    ),
    (
        'Algeria',
        "The People's Democratic Republic of Algeria",
        'Алжир',
        'Алжирская Народная Демократическая Республика',
        'DZ',
        'DZA',
        12,
        '.dz',
    ),
    (
        'American Samoa',
        'The Territory of American Samoa',
        'Американское Самоа',
        'Американское Самоа',
        'AS',
        'ASM',
        16,
        '.as',
    ),
    (
        'Andorra',
        'The Principality of Andorra',
        'Андорра',
        'Княжество Андорра',
        'AD',
        'AND',
        20,
        '.ad',
    ),
    (
        'Angola',
        'The Republic of Angola',
        'Ангола',
        'Республика Ангола',
        'AO',
        'AGO',
        24,
        '.ao',
    ),
    ('Anguilla', 'Anguilla', 'Ангилья', 'Ангилья', 'AI', 'AIA', 660, '.ai'),
    (
        'Antarctica',
        'Antarctica (all land and ice shelves south of the60th parallel south)',
        'Антарктида',
        'Антарктида',
        'AQ',
        'ATA',
        10,
        '.aq',
    ),
    (
        'Antigua and Barbuda',
        'Antigua and Barbuda',
        'Антигуа И Барбуда',
        'Антигуа И Барбуда',
        'AG',
        'ATG',
        28,
        '.ag',
    ),
    (
        'Argentina',
        'The Argentine Republic',
        'Аргентина',
        'Аргентинская Республика',
        'AR',
        'ARG',
        32,
        '.ar',
    ),
    (
        'Armenia',
        'The Republic of Armenia',
        'Армения',
        'Республика Армения',
        'AM',
        'ARM',
        51,
        '.am',
    ),
    ('Aruba', 'Aruba', 'Аруба', 'Аруба', 'AW', 'ABW', 533, '.aw'),
    (
        'Australia',
        'The Commonwealth of Australia',
        'Австралия',
        'Австралия',
        'AU',
        'AUS',
        36,
        '.au',
    ),
    (
        'Austria',
        'The Republic of Austria',
        'Австрия',
        'Австрийская Республика',
        'AT',
        'AUT',
        40,
        '.at',
    ),
    (
        'Azerbaijan',
        'The Republic of Azerbaijan',
        'Азербайджан',
        'Республика Азербайджан',
        'AZ',
        'AZE',
        31,
        '.az',
    ),
    (
        'Bahamas',
        'The Commonwealth of The Bahamas',
        'Багамы',
        'Содружество Багамы',
        'BS',
        'BHS',
        44,
        '.bs',
    ),
    (
        'Bahrain',
        'The Kingdom of Bahrain',
        'Бахрейн',
        'Королевство Бахрейн',
        'BH',
        'BHR',
        48,
        '.bh',
    ),
    (
        'Bangladesh',
        "The People's Republic of Bangladesh",
        'Бангладеш',
        'Народная Республика Бангладеш',
        'BD',
        'BGD',
        50,
        '.bd',
    ),
    ('Barbados', 'Barbados', 'Барбадос', 'Барбадос', 'BB', 'BRB', 52, '.bb'),
    (
        'Belarus',
        'The Republic of Belarus',
        'Беларусь',
        'Республика Беларусь',
        'BY',
        'BLR',
        112,
        '.by',
    ),
    (
        'Belgium',
        'The Kingdom of Belgium',
        'Бельгия',
        'Королевство Бельгия',
        'BE',
        'BEL',
        56,
        '.be',
    ),
    ('Belize', 'Belize', 'Белиз', 'Белиз', 'BZ', 'BLZ', 84, '.bz'),
    (
        'Benin',
        'The Republic of Benin',
        'Бенин',
        'Республика Бенин',
        'BJ',
        'BEN',
        204,
        '.bj',
    ),
    ('Bermuda', 'Bermuda', 'Бермуды', 'Бермуды', 'BM', 'BMU', 60, '.bm'),
    (
        'Bhutan',
        'The Kingdom of Bhutan',
        'Бутан',
        'Королевство Бутан',
        'BT',
        'BTN',
        64,
        '.bt',
    ),
    (
        'Bolivia (Plurinational State of)',
        'The Plurinational State of Bolivia',
        'Боливия, Многонациональное Государство',
        'Многонациональное Государство Боливия',
        'BO',
        'BOL',
        68,
        '.bo',
    ),
    (
        'Bonaire',
        'Bonaire, Sint Eustatius and Saba',
        'Бонэйр, Синт-Эстатиус И Саба',
        'Бонэйр, Синт-Эстатиус И Саба',
        'BQ',
        'BES',
        535,
        '.bq.nl',
    ),
    (
        'Bosnia and Herzegovina',
        'Bosnia and Herzegovina',
        'Босния И Герцеговина',
        'Босния И Герцеговина',
        'BA',
        'BIH',
        70,
        '.ba',
    ),
    (
        'Botswana',
        'The Republic of Botswana',
        'Ботсвана',
        'Республика Ботсвана',
        'BW',
        'BWA',
        72,
        '.bw',
    ),
    (
        'Bouvet Island',
        'Bouvet Island',
        'Остров Буве',
        'Остров Буве',
        'BV',
        'BVT',
        74,
        '',
    ),
    (
        'Brazil',
        'The Federative Republic of Brazil',
        'Бразилия',
        'Федеративная Республика Бразилия',
        'BR',
        'BRA',
        76,
        '.br',
    ),
    (
        'British Indian Ocean Territory',
        'The British Indian Ocean Territory',
        'Британская Территория В Индийском Океане',
        'Британская Территория В Индийском Океане',
        'IO',
        'IOT',
        86,
        '.io',
    ),
    (
        'Brunei Darussalam',
        'The Nation of Brunei, the Abode of Peace',
        'Бруней-Даруссалам',
        'Бруней-Даруссалам',
        'BN',
        'BRN',
        96,
        '.bn',
    ),
    (
        'Bulgaria',
        'The Republic of Bulgaria',
        'Болгария',
        'Республика Болгария',
        'BG',
        'BGR',
        100,
        '.bg',
    ),
    (
        'Burkina Faso',
        'Burkina Faso',
        'Буркина-Фасо',
        'Буркина-Фасо',
        'BF',
        'BFA',
        854,
        '.bf',
    ),
    (
        'Burundi',
        'The Republic of Burundi',
        'Бурунди',
        'Республика Бурунди',
        'BI',
        'BDI',
        108,
        '.bi',
    ),
    (
        'Cabo Verde',
        'The Republic of Cabo Verde',
        'Кабо-Верде',
        'Республика Кабо-Верде',
        'CV',
        'CPV',
        132,
        '.cv',
    ),
    (
        'Cambodia',
        'The Kingdom of Cambodia',
        'Камбоджа',
        'Королевство Камбоджа',
        'KH',
        'KHM',
        116,
        '.kh',
    ),
    (
        'Cameroon',
        'The Republic of Cameroon',
        'Камерун',
        'Республика Камерун',
        'CM',
        'CMR',
        120,
        '.cm',
    ),
    ('Canada', 'Canada', 'Канада', 'Канада', 'CA', 'CAN', 124, '.ca'),
    (
        'Cayman Islands',
        'The Cayman Islands',
        'Острова Кайман',
        'Острова Кайман',
        'KY',
        'CYM',
        136,
        '.ky',
    ),
    (
        'Central African Republic',
        'The Central African Republic',
        'Центрально-Африканская Республика',
        'Центрально-Африканская Республика',
        'CF',
        'CAF',
        140,
        '.cf',
    ),
    ('Chad', 'The Republic of Chad', 'Чад', 'Республика Чад', 'TD', 'TCD', 148, '.td'),
    (
        'Chile',
        'The Republic of Chile',
        'Чили',
        'Республика Чили',
        'CL',
        'CHL',
        152,
        '.cl',
    ),
    (
        'China',
        "The People's Republic of China",
        'Китай',
        'Китайская Народная Республика',
        'CN',
        'CHN',
        156,
        '.cn',
    ),
    (
        'Christmas Island',
        'The Territory of Christmas Island',
        'Остров Рождества',
        'Остров Рождества',
        'CX',
        'CXR',
        162,
        '.cx',
    ),
    (
        'Cocos (Keeling) Islands',
        'The Territory of Cocos (Keeling) Islands',
        'Кокосовые (Килинг) Острова',
        'Кокосовые (Килинг) Острова',
        'CC',
        'CCK',
        166,
        '.cc',
    ),
    (
        'Colombia',
        'The Republic of Colombia',
        'Колумбия',
        'Республика Колумбия',
        'CO',
        'COL',
        170,
        '.co',
    ),
    (
        'Comoros',
        'The Union of the Comoros',
        'Коморы',
        'Союз Коморы',
        'KM',
        'COM',
        174,
        '.km',
    ),
    (
        'Congo (the Democratic Republic of the)',
        'The Democratic Republic of the Congo',
        'Конго, Демократическая Республика',
        'Демократическая Республика Конго',
        'CD',
        'COD',
        180,
        '.cd',
    ),
    (
        'Congo',
        'The Republic of the Congo',
        'Конго',
        'Республика Конго',
        'CG',
        'COG',
        178,
        '.cg',
    ),
    (
        'Cook Islands',
        'The Cook Islands',
        'Острова Кука',
        'Острова Кука',
        'CK',
        'COK',
        184,
        '.ck',
    ),
    (
        'Costa Rica',
        'The Republic of Costa Rica',
        'Коста-Рика',
        'Республика Коста-Рика',
        'CR',
        'CRI',
        188,
        '.cr',
    ),
    (
        "Côte d'Ivoire",
        "The Republic of Côte d'Ivoire",
        "Кот Д'Ивуар",
        "Республика Кот Д'Ивуар",
        'CI',
        'CIV',
        384,
        '.ci',
    ),
    (
        'Croatia',
        'The Republic of Croatia',
        'Хорватия',
        'Республика Хорватия',
        'HR',
        'HRV',
        191,
        '.hr',
    ),
    (
        'Cuba',
        'The Republic of Cuba',
        'Куба',
        'Республика Куба',
        'CU',
        'CUB',
        192,
        '.cu',
    ),
    (
        'Curaçao',
        'The Country of Curaçao',
        'Кюрасао',
        'Кюрасао',
        'CW',
        'CUW',
        531,
        '.cw',
    ),
    (
        'Cyprus',
        'The Republic of Cyprus',
        'Кипр',
        'Республика Кипр',
        'CY',
        'CYP',
        196,
        '.cy',
    ),
    (
        'Czechia',
        'The Czech Republic',
        'Чехия',
        'Чешская Республика',
        'CZ',
        'CZE',
        203,
        '.cz',
    ),
    (
        'Denmark',
        'The Kingdom of Denmark',
        'Дания',
        'Королевство Дания',
        'DK',
        'DNK',
        208,
        '.dk',
    ),
    (
        'Djibouti',
        'The Republic of Djibouti',
        'Джибути',
        'Республика Джибути',
        'DJ',
        'DJI',
        262,
        '.dj',
    ),
    (
        'Dominica',
        'The Commonwealth of Dominica',
        'Доминика',
        'Содружество Доминики',
        'DM',
        'DMA',
        212,
        '.dm',
    ),
    (
        'Dominican Republic',
        'The Dominican Republic',
        'Доминиканская Республика',
        'Доминиканская Республика',
        'DO',
        'DOM',
        214,
        '.do',
    ),
    (
        'Ecuador',
        'The Republic of Ecuador',
        'Эквадор',
        'Республика Эквадор',
        'EC',
        'ECU',
        218,
        '.ec',
    ),
    (
        'Egypt',
        'The Arab Republic of Egypt',
        'Египет',
        'Арабская Республика Египет',
        'EG',
        'EGY',
        818,
        '.eg',
    ),
    (
        'El Salvador',
        'The Republic of El Salvador',
        'Эль-Сальвадор',
        'Республика Эль-Сальвадор',
        'SV',
        'SLV',
        222,
        '.sv',
    ),
    (
        'Equatorial Guinea',
        'The Republic of Equatorial Guinea',
        'Экваториальная Гвинея',
        'Республика Экваториальная Гвинея',
        'GQ',
        'GNQ',
        226,
        '.gq',
    ),
    (
        'Eritrea',
        'The State of Eritrea',
        'Эритрея',
        'Государство Эритрея',
        'ER',
        'ERI',
        232,
        '.er',
    ),
    (
        'Estonia',
        'The Republic of Estonia',
        'Эстония',
        'Эстонская Республика',
        'EE',
        'EST',
        233,
        '.ee',
    ),
    (
        'Eswatini',
        'The Kingdom of Eswatini',
        'Эсватини',
        'Королевство Эсватини',
        'SZ',
        'SWZ',
        748,
        '.sz',
    ),
    (
        'Ethiopia',
        'The Federal Democratic Republic of Ethiopia',
        'Эфиопия',
        'Федеративная Демократическая Республика Эфиопия',
        'ET',
        'ETH',
        231,
        '.et',
    ),
    (
        'Falkland Islands',
        'The Falkland Islands',
        'Фолклендские Острова (Мальвинские)',
        'Фолклендские Острова (Мальвинские)',
        'FK',
        'FLK',
        238,
        '.fk',
    ),
    (
        'Faroe Islands',
        'The Faroe Islands',
        'Фарерские Острова',
        'Фарерские Острова',
        'FO',
        'FRO',
        234,
        '.fo',
    ),
    (
        'Fiji',
        'The Republic of Fiji',
        'Фиджи',
        'Республика Фиджи',
        'FJ',
        'FJI',
        242,
        '.fj',
    ),
    (
        'Finland',
        'The Republic of Finland',
        'Финляндия',
        'Финляндская Республика',
        'FI',
        'FIN',
        246,
        '.fi',
    ),
    (
        'France',
        'The French Republic',
        'Франция',
        'Французская Республика',
        'FR',
        'FRA',
        250,
        '.fr',
    ),
    (
        'French Guiana',
        'Guyane',
        'Французская Гвиана',
        'Французская Гвиана',
        'GF',
        'GUF',
        254,
        '.gf',
    ),
    (
        'French Polynesia',
        'French Polynesia',
        'Французская Полинезия',
        'Французская Полинезия',
        'PF',
        'PYF',
        258,
        '.pf',
    ),
    (
        'French Southern Territories',
        'The French Southern and Antarctic Lands',
        'Французские Южные Территории',
        'Французские Южные Территории',
        'TF',
        'ATF',
        260,
        '.tf',
    ),
    (
        'Gabon',
        'The Gabonese Republic',
        'Габон',
        'Габонская Республика',
        'GA',
        'GAB',
        266,
        '.ga',
    ),
    (
        'Gambia',
        'The Republic of The Gambia',
        'Гамбия',
        'Республика Гамбия',
        'GM',
        'GMB',
        270,
        '.gm',
    ),
    ('Georgia', 'Georgia', 'Грузия', 'Грузия', 'GE', 'GEO', 268, '.ge'),
    (
        'Germany',
        'The Federal Republic of Germany',
        'Германия',
        'Федеративная Республика Германия',
        'DE',
        'DEU',
        276,
        '.de',
    ),
    (
        'Ghana',
        'The Republic of Ghana',
        'Гана',
        'Республика Гана',
        'GH',
        'GHA',
        288,
        '.gh',
    ),
    ('Gibraltar', 'Gibraltar', 'Гибралтар', 'Гибралтар', 'GI', 'GIB', 292, '.gi'),
    (
        'Greece',
        'The Hellenic Republic',
        'Греция',
        'Греческая Республика',
        'GR',
        'GRC',
        300,
        '.gr',
    ),
    (
        'Greenland',
        'Kalaallit Nunaat',
        'Гренландия',
        'Гренландия',
        'GL',
        'GRL',
        304,
        '.gl',
    ),
    ('Grenada', 'Grenada', 'Гренада', 'Гренада', 'GD', 'GRD', 308, '.gd'),
    ('Guadeloupe', 'Guadeloupe', 'Гваделупа', 'Гваделупа', 'GP', 'GLP', 312, '.gp'),
    ('Guam', 'The Territory of Guam', 'Гуам', 'Гуам', 'GU', 'GUM', 316, '.gu'),
    (
        'Guatemala',
        'The Republic of Guatemala',
        'Гватемала',
        'Республика Гватемала',
        'GT',
        'GTM',
        320,
        '.gt',
    ),
    (
        'Guernsey',
        'The Bailiwick of Guernsey',
        'Гернси',
        'Гернси',
        'GG',
        'GGY',
        831,
        '.gg',
    ),
    (
        'Guinea',
        'The Republic of Guinea',
        'Гвинея',
        'Гвинейская Республика',
        'GN',
        'GIN',
        324,
        '.gn',
    ),
    (
        'Guinea-Bissau',
        'The Republic of Guinea-Bissau',
        'Гвинея-Бисау',
        'Республика Гвинея-Бисау',
        'GW',
        'GNB',
        624,
        '.gw',
    ),
    (
        'Guyana',
        'The Co-operative Republic of Guyana',
        'Гайана',
        'Республика Гайана',
        'GY',
        'GUY',
        328,
        '.gy',
    ),
    (
        'Haiti',
        'The Republic of Haiti',
        'Гаити',
        'Республика Гаити',
        'HT',
        'HTI',
        332,
        '.ht',
    ),
    (
        'Heard Island and McDonald Islands',
        'The Territory of Heard Island and McDonald Islands',
        'Остров Херд и Острова Макдональд',
        'Остров Херд и Острова Макдональд',
        'HM',
        'HMD',
        334,
        '.hm',
    ),
    (
        'Holy See',
        'The Holy See',
        'Папский Престол (Государство - Город Ватикан)',
        'Папский Престол (Государство - Город Ватикан)',
        'VA',
        'VAT',
        336,
        '.va',
    ),
    (
        'Honduras',
        'The Republic of Honduras',
        'Гондурас',
        'Республика Гондурас',
        'HN',
        'HND',
        340,
        '.hn',
    ),
    (
        'Hong Kong',
        'The Hong Kong Special Administrative Region of China',
        'Гонконг',
        'Специальный Административный Район Гонконг Китайской Народной Республики',
        'HK',
        'HKG',
        344,
        '.hk',
    ),
    ('Hungary', 'Hungary', 'Венгрия', 'Венгрия', 'HU', 'HUN', 348, '.hu'),
    ('Iceland', 'Iceland', 'Исландия', 'Республика Исландия', 'IS', 'ISL', 352, '.is'),
    (
        'India',
        'The Republic of India',
        'Индия',
        'Республика Индия',
        'IN',
        'IND',
        356,
        '.in',
    ),
    (
        'Indonesia',
        'The Republic of Indonesia',
        'Индонезия',
        'Республика Индонезия',
        'ID',
        'IDN',
        360,
        '.id',
    ),
    (
        'Iran (Islamic Republic of)',
        'The Islamic Republic of Iran',
        'Иран',
        'Исламская республика Иран',
        'IR',
        'IRN',
        364,
        '.ir',
    ),
    (
        'Iraq',
        'The Republic of Iraq',
        'Ирак',
        'Республика Ирак',
        'IQ',
        'IRQ',
        368,
        '.iq',
    ),
    ('Ireland', 'Ireland', 'Ирландия', 'Ирландия', 'IE', 'IRL', 372, '.ie'),
    (
        'Isle of Man',
        'The Isle of Man',
        'Остров Мэн',
        'Остров Мэн',
        'IM',
        'IMN',
        833,
        '.im',
    ),
    (
        'Israel',
        'The State of Israel',
        'Израиль',
        'Государство Израиль',
        'IL',
        'ISR',
        376,
        '.il',
    ),
    (
        'Italy',
        'The Italian Republic',
        'Италия',
        'Итальянская Республика',
        'IT',
        'ITA',
        380,
        '.it',
    ),
    ('Jamaica', 'Jamaica', 'Ямайка', 'Ямайка', 'JM', 'JAM', 388, '.jm'),
    ('Japan', 'Japan', 'Япония', 'Япония', 'JP', 'JPN', 392, '.jp'),
    ('Jersey', 'The Bailiwick of Jersey', 'Джерси', 'Джерси', 'JE', 'JEY', 832, '.je'),
    (
        'Jordan',
        'The Hashemite Kingdom of Jordan',
        'Иордания',
        'Иорданское Хашимитское Королевство',
        'JO',
        'JOR',
        400,
        '.jo',
    ),
    (
        'Kazakhstan',
        'The Republic of Kazakhstan',
        'Казахстан',
        'Республика Казахстан',
        'KZ',
        'KAZ',
        398,
        '.kz',
    ),
    (
        'Kenya',
        'The Republic of Kenya',
        'Кения',
        'Республика Кения',
        'KE',
        'KEN',
        404,
        '.ke',
    ),
    (
        'Kiribati',
        'The Republic of Kiribati',
        'Кирибати',
        'Республика Кирибати',
        'KI',
        'KIR',
        296,
        '.ki',
    ),
    (
        "Korea (the Democratic People's Republic of)",
        "The Democratic People's Republic of Korea",
        'Корея, Народно-Демократическая Республика',
        'Корейская Народно-Демократическая Республика',
        'KP',
        'PRK',
        408,
        '.kp',
    ),
    (
        'Korea (the Republic of)',
        'The Republic of Korea',
        'Корея, Республика',
        'Республика Корея',
        'KR',
        'KOR',
        410,
        '.kr',
    ),
    (
        'Kuwait',
        'The State of Kuwait',
        'Кувейт',
        'Государство Кувейт',
        'KW',
        'KWT',
        414,
        '.kw',
    ),
    (
        'Kyrgyzstan',
        'The Kyrgyz Republic',
        'Киргизия',
        'Киргизская Республика',
        'KG',
        'KGZ',
        417,
        '.kg',
    ),
    (
        "Lao People's Democratic Republic",
        "The Lao People's Democratic Republic",
        'Лаос',
        'Лаосская Народно-Демократическая Республика',
        'LA',
        'LAO',
        418,
        '.la',
    ),
    (
        'Latvia',
        'The Republic of Latvia',
        'Латвия',
        'Латвийская Республика',
        'LV',
        'LVA',
        428,
        '.lv',
    ),
    (
        'Lebanon',
        'The Lebanese Republic',
        'Ливан',
        'Ливанская Республика',
        'LB',
        'LBN',
        422,
        '.lb',
    ),
    (
        'Lesotho',
        'The Kingdom of Lesotho',
        'Лесото',
        'Королевство Лесото',
        'LS',
        'LSO',
        426,
        '.ls',
    ),
    (
        'Liberia',
        'The Republic of Liberia',
        'Либерия',
        'Республика Либерия',
        'LR',
        'LBR',
        430,
        '.lr',
    ),
    (
        'Libya',
        'The State of Libya',
        'Ливия',
        'Государство Ливия',
        'LY',
        'LBY',
        434,
        '.ly',
    ),
    (
        'Liechtenstein',
        'The Principality of Liechtenstein',
        'Лихтенштейн',
        'Княжество Лихтенштейн',
        'LI',
        'LIE',
        438,
        '.li',
    ),
    (
        'Lithuania',
        'The Republic of Lithuania',
        'Литва',
        'Литовская Республика',
        'LT',
        'LTU',
        440,
        '.lt',
    ),
    (
        'Luxembourg',
        'The Grand Duchy of Luxembourg',
        'Люксембург',
        'Великое Герцогство Люксембург',
        'LU',
        'LUX',
        442,
        '.lu',
    ),
    (
        'Macao',
        'The Macao Special Administrative Region of China',
        'Макао',
        'Специальный Административный Район Макао Китайской Народной Республики',
        'MO',
        'MAC',
        446,
        '.mo',
    ),
    (
        'Madagascar',
        'The Republic of Madagascar',
        'Мадагаскар',
        'Республика Мадагаскар',
        'MG',
        'MDG',
        450,
        '.mg',
    ),
    (
        'Malawi',
        'The Republic of Malawi',
        'Малави',
        'Республика Малави',
        'MW',
        'MWI',
        454,
        '.mw',
    ),
    ('Malaysia', 'Malaysia', 'Малайзия', 'Малайзия', 'MY', 'MYS', 458, '.my'),
    (
        'Maldives',
        'The Republic of Maldives',
        'Мальдивы',
        'Мальдивская Республика',
        'MV',
        'MDV',
        462,
        '.mv',
    ),
    (
        'Mali',
        'The Republic of Mali',
        'Мали',
        'Республика Мали',
        'ML',
        'MLI',
        466,
        '.ml',
    ),
    (
        'Malta',
        'The Republic of Malta',
        'Мальта',
        'Республика Мальта',
        'MT',
        'MLT',
        470,
        '.mt',
    ),
    (
        'Marshall Islands',
        'The Republic of the Marshall Islands',
        'Маршалловы Острова',
        'Республика Маршалловы Острова',
        'MH',
        'MHL',
        584,
        '.mh',
    ),
    ('Martinique', 'Martinique', 'Мартиника', 'Мартиника', 'MQ', 'MTQ', 474, '.mq'),
    (
        'Mauritania',
        'The Islamic Republic of Mauritania',
        'Мавритания',
        'Исламская Республика Мавритания',
        'MR',
        'MRT',
        478,
        '.mr',
    ),
    (
        'Mauritius',
        'The Republic of Mauritius',
        'Маврикий',
        'Республика Маврикий',
        'MU',
        'MUS',
        480,
        '.mu',
    ),
    (
        'Mayotte',
        'The Department of Mayotte',
        'Майотта',
        'Майотта',
        'YT',
        'MYT',
        175,
        '.yt',
    ),
    (
        'Mexico',
        'The United Mexican States',
        'Мексика',
        'Мексиканские Соединенные Штаты',
        'MX',
        'MEX',
        484,
        '.mx',
    ),
    (
        'Micronesia (Federated States of)',
        'The Federated States of Micronesia',
        'Микронезия',
        'Федеративные Штаты Микронезии',
        'FM',
        'FSM',
        583,
        '.fm',
    ),
    (
        'Moldova (the Republic of)',
        'The Republic of Moldova',
        'Молдова',
        'Республика Молдова',
        'MD',
        'MDA',
        498,
        '.md',
    ),
    (
        'Monaco',
        'The Principality of Monaco',
        'Монако',
        'Княжество Монако',
        'MC',
        'MCO',
        492,
        '.mc',
    ),
    ('Mongolia', 'Mongolia', 'Монголия', 'Монголия', 'MN', 'MNG', 496, '.mn'),
    ('Montenegro', 'Montenegro', 'Черногория', 'Черногория', 'ME', 'MNE', 499, '.me'),
    ('Montserrat', 'Montserrat', 'Монтсеррат', 'Монтсеррат', 'MS', 'MSR', 500, '.ms'),
    (
        'Morocco',
        'The Kingdom of Morocco',
        'Марокко',
        'Королевство Марокко',
        'MA',
        'MAR',
        504,
        '.ma',
    ),
    (
        'Mozambique',
        'The Republic of Mozambique',
        'Мозамбик',
        'Республика Мозамбик',
        'MZ',
        'MOZ',
        508,
        '.mz',
    ),
    (
        'Myanmar',
        'The Republic of the Union of Myanmar',
        'Мьянма',
        'Республика Союза Мьянма',
        'MM',
        'MMR',
        104,
        '.mm',
    ),
    (
        'Namibia',
        'The Republic of Namibia',
        'Намибия',
        'Республика Намибия',
        'NA',
        'NAM',
        516,
        '.na',
    ),
    (
        'Nauru',
        'The Republic of Nauru',
        'Науру',
        'Республика Науру',
        'NR',
        'NRU',
        520,
        '.nr',
    ),
    (
        'Nepal',
        'The Federal Democratic Republic of Nepal',
        'Непал',
        'Федеративная Демократическая Республика Непал',
        'NP',
        'NPL',
        524,
        '.np',
    ),
    (
        'Netherlands, Kingdom of the',
        'The Kingdom of the Netherlands',
        'Нидерланды',
        'Королевство Нидерландов',
        'NL',
        'NLD',
        528,
        '.nl',
    ),
    (
        'New Caledonia',
        'New Caledonia',
        'Новая Каледония',
        'Новая Каледония',
        'NC',
        'NCL',
        540,
        '.nc',
    ),
    (
        'New Zealand',
        'New Zealand',
        'Новая Зеландия',
        'Новая Зеландия',
        'NZ',
        'NZL',
        554,
        '.nz',
    ),
    (
        'Nicaragua',
        'The Republic of Nicaragua',
        'Никарагуа',
        'Республика Никарагуа',
        'NI',
        'NIC',
        558,
        '.ni',
    ),
    (
        'Niger',
        'The Republic of the Niger',
        'Нигер',
        'Республика Нигер',
        'NE',
        'NER',
        562,
        '.ne',
    ),
    (
        'Nigeria',
        'The Federal Republic of Nigeria',
        'Нигерия',
        'Федеративная Республика Нигерия',
        'NG',
        'NGA',
        566,
        '.ng',
    ),
    ('Niue', 'Niue', 'Ниуэ', 'Республика Ниуэ', 'NU', 'NIU', 570, '.nu'),
    (
        'Norfolk Island',
        'The Territory of Norfolk Island',
        'Остров Норфолк',
        'Остров Норфолк',
        'NF',
        'NFK',
        574,
        '.nf',
    ),
    (
        'North Macedonia',
        'The Republic of North Macedonia',
        'Северная Македония',
        'Республика Северная Македония',
        'MK',
        'MKD',
        807,
        '.mk',
    ),
    (
        'Northern Mariana Islands',
        'The Commonwealth of the Northern Mariana Islands',
        'Северные Марианские Острова',
        'Содружество Северных Марианских Островов',
        'MP',
        'MNP',
        580,
        '.mp',
    ),
    (
        'Norway',
        'The Kingdom of Norway',
        'Норвегия',
        'Королевство Норвегия',
        'NO',
        'NOR',
        578,
        '.no',
    ),
    (
        'Oman',
        'The Sultanate of Oman',
        'Оман',
        'Султанат Оман',
        'OM',
        'OMN',
        512,
        '.om',
    ),
    (
        'Pakistan',
        'The Islamic Republic of Pakistan',
        'Пакистан',
        'Исламская Республика Пакистан',
        'PK',
        'PAK',
        586,
        '.pk',
    ),
    (
        'Palau',
        'The Republic of Palau',
        'Палау',
        'Республика Палау',
        'PW',
        'PLW',
        585,
        '.pw',
    ),
    (
        'Palestine, State of',
        'The State of Palestine',
        'Палестина',
        'Государство Палестина',
        'PS',
        'PSE',
        275,
        '.ps',
    ),
    (
        'Panama',
        'The Republic of Panamá',
        'Панама',
        'Республика Панама',
        'PA',
        'PAN',
        591,
        '.pa',
    ),
    (
        'Papua New Guinea',
        'The Independent State of Papua New Guinea',
        'Папуа-Новая Гвинея',
        'Независимое Государство  Папуа Новая Гвинея',
        'PG',
        'PNG',
        598,
        '.pg',
    ),
    (
        'Paraguay',
        'The Republic of Paraguay',
        'Парагвай',
        'Республика Парагвай',
        'PY',
        'PRY',
        600,
        '.py',
    ),
    (
        'Peru',
        'The Republic of Perú',
        'Перу',
        'Республика Перу',
        'PE',
        'PER',
        604,
        '.pe',
    ),
    (
        'Philippines',
        'The Republic of the Philippines',
        'Филиппины',
        'Республика Филиппины',
        'PH',
        'PHL',
        608,
        '.ph',
    ),
    (
        'Pitcairn',
        'The Pitcairn, Henderson, Ducie and Oeno Islands',
        'Питкерн',
        'Питкерн',
        'PN',
        'PCN',
        612,
        '.pn',
    ),
    (
        'Poland',
        'The Republic of Poland',
        'Польша',
        'Республика Польша',
        'PL',
        'POL',
        616,
        '.pl',
    ),
    (
        'Portugal',
        'The Portuguese Republic',
        'Португалия',
        'Португальская Республика',
        'PT',
        'PRT',
        620,
        '.pt',
    ),
    (
        'Puerto Rico',
        'The Commonwealth of Puerto Rico',
        'Пуэрто-Рико',
        'Пуэрто-Рико',
        'PR',
        'PRI',
        630,
        '.pr',
    ),
    (
        'Qatar',
        'The State of Qatar',
        'Катар',
        'Государство Катар',
        'QA',
        'QAT',
        634,
        '.qa',
    ),
    ('Réunion', 'Réunion', 'Реюньон', 'Реюньон', 'RE', 'REU', 638, '.re'),
    ('Romania', 'Romania', 'Румыния', 'Румыния', 'RO', 'ROU', 642, '.ro'),
    (
        'Russian Federation',
        'The Russian Federation',
        'Россия',
        'Российская Федерация',
        'RU',
        'RUS',
        643,
        '.ru',
    ),
    (
        'Rwanda',
        'The Republic of Rwanda',
        'Руанда',
        'Руандийская Республика',
        'RW',
        'RWA',
        646,
        '.rw',
    ),
    (
        'Saint Barthélemy',
        'The Collectivity of Saint-Barthélemy',
        'Сен-Бартелеми',
        'Сен-Бартелеми',
        'BL',
        'BLM',
        652,
        '.bl',
    ),
    (
        'Saint Helena',
        'Saint Helena, Ascension and Tristan da Cunha',
        'Святая Елена, Остров Вознесения, Тристан-Да-Кунья',
        'Святая Елена, Остров Вознесения, Тристан-Да-Кунья',
        'SH',
        'SHN',
        654,
        '.sh',
    ),
    (
        'Saint Kitts and Nevis',
        'Saint Kitts and Nevis',
        'Сент-Китс и Невис',
        'Сент-Китс и Невис',
        'KN',
        'KNA',
        659,
        '.kn',
    ),
    (
        'Saint Lucia',
        'Saint Lucia',
        'Сент-Люсия',
        'Сент-Люсия',
        'LC',
        'LCA',
        662,
        '.lc',
    ),
    (
        'Saint Martin (French part)',
        'The Collectivity of Saint-Martin',
        'Сен-Мартен (Французская Часть)',
        'Сен-Мартен (Французская Часть)',
        'MF',
        'MAF',
        663,
        '.mf',
    ),
    (
        'Saint Pierre and Miquelon',
        'The Overseas Collectivity of Saint-Pierre and Miquelon',
        'Сен-Пьер И Микелон',
        'Сен-Пьер И Микелон',
        'PM',
        'SPM',
        666,
        '.pm',
    ),
    (
        'Saint Vincent and the Grenadines',
        'Saint Vincent and the Grenadines',
        'Сент-Винсент и Гренадины',
        'Сент-Винсент и Гренадины',
        'VC',
        'VCT',
        670,
        '.vc',
    ),
    (
        'Samoa',
        'The Independent State of Samoa',
        'Самоа',
        'Независимое Государство Самоа',
        'WS',
        'WSM',
        882,
        '.ws',
    ),
    (
        'San Marino',
        'The Republic of San Marino',
        'Сан-Марино',
        'Республика Сан-Марино',
        'SM',
        'SMR',
        674,
        '.sm',
    ),
    (
        'Sao Tome and Principe',
        'The Democratic Republic of São Tomé and Príncipe',
        'Сан-Томе и Принсипи',
        'Демократическая Республика Сан-Томе и Принсипи',
        'ST',
        'STP',
        678,
        '.st',
    ),
    (
        'Saudi Arabia',
        'The Kingdom of Saudi Arabia',
        'Саудовская Аравия',
        'Королевство Саудовская Аравия',
        'SA',
        'SAU',
        682,
        '.sa',
    ),
    (
        'Senegal',
        'The Republic of Senegal',
        'Сенегал',
        'Республика Сенегал',
        'SN',
        'SEN',
        686,
        '.sn',
    ),
    (
        'Serbia',
        'The Republic of Serbia',
        'Сербия',
        'Республика Сербия',
        'RS',
        'SRB',
        688,
        '.rs',
    ),
    (
        'Seychelles',
        'The Republic of Seychelles',
        'Сейшелы',
        'Республика Сейшелы',
        'SC',
        'SYC',
        690,
        '.sc',
    ),
    (
        'Sierra Leone',
        'The Republic of Sierra Leone',
        'Сьерра-Леоне',
        'Республика Сьерра-Леоне',
        'SL',
        'SLE',
        694,
        '.sl',
    ),
    (
        'Singapore',
        'The Republic of Singapore',
        'Сингапур',
        'Республика Сингапур',
        'SG',
        'SGP',
        702,
        '.sg',
    ),
    (
        'Sint Maarten (Dutch part)',
        'Sint Maarten',
        'Сен-Мартен (Нидерландская Часть)',
        'Сен-Мартен (Нидерландская Часть)',
        'SX',
        'SXM',
        534,
        '.sx',
    ),
    (
        'Slovakia',
        'The Slovak Republic',
        'Словакия',
        'Словацкая Республика',
        'SK',
        'SVK',
        703,
        '.sk',
    ),
    (
        'Slovenia',
        'The Republic of Slovenia',
        'Словения',
        'Республика Словения',
        'SI',
        'SVN',
        705,
        '.si',
    ),
    (
        'Solomon Islands',
        'The Solomon Islands',
        'Соломоновы Острова',
        'Соломоновы Острова',
        'SB',
        'SLB',
        90,
        '.sb',
    ),
    (
        'Somalia',
        'The Federal Republic of Somalia',
        'Сомали',
        'Федеративная Республика Сомали',
        'SO',
        'SOM',
        706,
        '.so',
    ),
    (
        'South Africa',
        'The Republic of South Africa',
        'Южная Африка',
        'Южно-Африканская Республика',
        'ZA',
        'ZAF',
        710,
        '.za',
    ),
    (
        'South Georgia and the South Sandwich Islands',
        'South Georgia and the South Sandwich Islands',
        'Южная Джорджия и Южные Сандвичевы Острова',
        'Южная Джорджия и Южные Сандвичевы Острова',
        'GS',
        'SGS',
        239,
        '.gs',
    ),
    (
        'South Sudan',
        'The Republic of South Sudan',
        'Южный Судан',
        'Республика Южный Судан',
        'SS',
        'SSD',
        728,
        '.ss',
    ),
    (
        'Spain',
        'The Kingdom of Spain',
        'Испания',
        'Королевство Испания',
        'ES',
        'ESP',
        724,
        '.es',
    ),
    (
        'Sri Lanka',
        'The Democratic Socialist Republic of Sri Lanka',
        'Шри-Ланка',
        'Демократическая Социалистическая Республика Шри-Ланка',
        'LK',
        'LKA',
        144,
        '.lk',
    ),
    (
        'Sudan',
        'The Republic of the Sudan',
        'Судан',
        'Республика Судан',
        'SD',
        'SDN',
        729,
        '.sd',
    ),
    (
        'Suriname',
        'The Republic of Suriname',
        'Суринам',
        'Республика Суринам',
        'SR',
        'SUR',
        740,
        '.sr',
    ),
    (
        'Svalbard',
        'Svalbard and Jan Mayen',
        'Шпицберген и Ян Майен',
        'Шпицберген и Ян Майен',
        'SJ',
        'SJM',
        744,
        '',
    ),
    (
        'Sweden',
        'The Kingdom of Sweden',
        'Швеция',
        'Королевство Швеция',
        'SE',
        'SWE',
        752,
        '.se',
    ),
    (
        'Switzerland',
        'The Swiss Confederation',
        'Швейцария',
        'Швейцарская Конфедерация',
        'CH',
        'CHE',
        756,
        '.ch',
    ),
    (
        'Syrian Arab Republic',
        'The Syrian Arab Republic',
        'Сирийская Арабская Республика',
        'Сирийская Арабская Республика',
        'SY',
        'SYR',
        760,
        '.sy',
    ),
    (
        'Taiwan (Province of China)',
        'The Republic of China',
        'Тайвань (Китай)',
        'Тайвань (Китай)',
        'TW',
        'TWN',
        158,
        '.tw',
    ),
    (
        'Tajikistan',
        'The Republic of Tajikistan',
        'Таджикистан',
        'Республика Таджикистан',
        'TJ',
        'TJK',
        762,
        '.tj',
    ),
    (
        'Tanzania, the United Republic of',
        'The United Republic of Tanzania',
        'Танзания, Объединенная Республика',
        'Объединенная Республика Танзания',
        'TZ',
        'TZA',
        834,
        '.tz',
    ),
    (
        'Thailand',
        'The Kingdom of Thailand',
        'Таиланд',
        'Королевство Таиланд',
        'TH',
        'THA',
        764,
        '.th',
    ),
    (
        'Timor-Leste',
        'The Democratic Republic of Timor-Leste',
        'Тимор-Лесте',
        'Демократическая Республика Тимор-Лесте',
        'TL',
        'TLS',
        626,
        '.tl',
    ),
    (
        'Togo',
        'The Togolese Republic',
        'Того',
        'Тоголезская Республика',
        'TG',
        'TGO',
        768,
        '.tg',
    ),
    ('Tokelau', 'Tokelau', 'Токелау', 'Токелау', 'TK', 'TKL', 772, '.tk'),
    (
        'Tonga',
        'The Kingdom of Tonga',
        'Тонга',
        'Королевство Тонга',
        'TO',
        'TON',
        776,
        '.to',
    ),
    (
        'Trinidad and Tobago',
        'The Republic of Trinidad and Tobago',
        'Тринидад и Тобаго',
        'Республика Тринидад и Тобаго',
        'TT',
        'TTO',
        780,
        '.tt',
    ),
    (
        'Tunisia',
        'The Republic of Tunisia',
        'Тунис',
        'Тунисская Республика',
        'TN',
        'TUN',
        788,
        '.tn',
    ),
    (
        'Türkiye',
        'The Republic of Türkiye',
        'Турция',
        'Турецкая Республика',
        'TR',
        'TUR',
        792,
        '.tr',
    ),
    (
        'Turkmenistan',
        'Turkmenistan',
        'Туркменистан',
        'Туркменистан',
        'TM',
        'TKM',
        795,
        '.tm',
    ),
    (
        'Turks and Caicos Islands',
        'The Turks and Caicos Islands',
        'Острова Теркс и Кайкос',
        'Острова Теркс и Кайкос',
        'TC',
        'TCA',
        796,
        '.tc',
    ),
    ('Tuvalu', 'Tuvalu', 'Тувалу', 'Тувалу', 'TV', 'TUV', 798, '.tv'),
    (
        'Uganda',
        'The Republic of Uganda',
        'Уганда',
        'Республика Уганда',
        'UG',
        'UGA',
        800,
        '.ug',
    ),
    ('Ukraine', 'Ukraine', 'Украина', 'Украина', 'UA', 'UKR', 804, '.ua'),
    (
        'United Arab Emirates',
        'The United Arab Emirates',
        'Объединенные Арабские Эмираты',
        'Объединенные Арабские Эмираты',
        'AE',
        'ARE',
        784,
        '.ae',
    ),
    (
        'United Kingdom of Great Britain and Northern Ireland',
        'The United Kingdom of Great Britain and Northern Ireland',
        'Соединенное Королевство',
        'Соединенное Королевство Великобритании И Северной Ирландии',
        'GB',
        'GBR',
        826,
        '.gb.uk',
    ),
    (
        'United States Minor Outlying Islands',
        'BakerIsland, HowlandIsland,JarvisIsland, JohnstonAtoll, KingmanReef, '
        'MidwayAtoll, NavassaIsland, PalmyraAtoll, and WakeIsland',
        'Малые Тихоокеанские Отдаленные Острова Соединенных Штатов',
        'Малые Тихоокеанские Отдаленные Острова Соединенных Штатов',
        'UM',
        'UMI',
        581,
        '',
    ),
    (
        'United States of America',
        'The United States of America',
        'США',
        'Соединенные Штаты Америки',
        'US',
        'USA',
        840,
        '.us',
    ),
    (
        'Uruguay',
        'The Oriental Republic of Uruguay',
        'Уругвай',
        'Восточная Республика Уругвай',
        'UY',
        'URY',
        858,
        '.uy',
    ),
    (
        'Uzbekistan',
        'The Republic of Uzbekistan',
        'Узбекистан',
        'Республика Узбекистан',
        'UZ',
        'UZB',
        860,
        '.uz',
    ),
    (
        'Vanuatu',
        'The Republic of Vanuatu',
        'Вануату',
        'Республика Вануату',
        'VU',
        'VUT',
        548,
        '.vu',
    ),
    (
        'Venezuela (Bolivarian Republic of)',
        'The Bolivarian Republic of Venezuela',
        'Венесуэла',
        'Боливарианская Республика Венесуэла',
        'VE',
        'VEN',
        862,
        '.ve',
    ),
    (
        'Viet Nam',
        'The Socialist Republic of Viet Nam',
        'Вьетнам',
        'Социалистическая Республика Вьетнам',
        'VN',
        'VNM',
        704,
        '.vn',
    ),
    (
        'Virgin Islands (British)',
        'The Virgin Islands',
        'Виргинские Острова (Британские)',
        'Британские Виргинские Острова',
        'VG',
        'VGB',
        92,
        '.vg',
    ),
    (
        'Virgin Islands (U.S.)',
        'The Virgin Islands of the United States',
        'Виргинские Острова (США)',
        'Виргинские Острова Соединенных Штатов',
        'VI',
        'VIR',
        850,
        '.vi',
    ),
    (
        'Wallis and Futuna',
        'The Territory of the Wallis and Futuna Islands',
        'Уоллис и Футуна',
        'Уоллис и Футуна',
        'WF',
        'WLF',
        876,
        '.wf',
    ),
    (
        'Western Sahara',
        'The Sahrawi Arab Democratic Republic',
        'Западная Сахара',
        'Западная Сахара',
        'EH',
        'ESH',
        732,
        '',
    ),
    (
        'Yemen',
        'The Republic of Yemen',
        'Йемен',
        'Йеменская Республика',
        'YE',
        'YEM',
        887,
        '.ye',
    ),
    (
        'Zambia',
        'The Republic of Zambia',
        'Замбия',
        'Республика Замбия',
        'ZM',
        'ZMB',
        894,
        '.zm',
    ),
    (
        'Zimbabwe',
        'The Republic of Zimbabwe',
        'Зимбабве',
        'Республика Зимбабве',
        'ZW',
        'ZWE',
        716,
        '.zw',
    ),
)
