CURRENCYKEYS = ('entuty', 'currency', 'code', 'num', 'minors', 'fund')
CURRENCYTUPLES = (
    ('Afghanistan', 'Afghani', 'AFN', 971, 2, False),
    ('Albania', 'Lek', 'ALL', 8, 2, False),
    ('Algeria', 'Algerian Dinar', 'DZD', 12, 2, False),
    ('American Samoa', 'US Dollar', 'USD', 840, 2, False),
    ('Andorra', 'Euro', 'EUR', 978, 2, False),
    ('Angola', 'Kwanza', 'AOA', 973, 2, False),
    ('Anguilla', 'East Caribbean Dollar', 'XCD', 951, 2, False),
    ('Antarctica', 'No universal currency', '', None, 0, False),
    ('Antigua And Barbuda', 'East Caribbean Dollar', 'XCD', 951, 2, False),
    ('Argentina', 'Argentine Peso', 'ARS', 32, 2, False),
    ('Armenia', 'Armenian Dram', 'AMD', 51, 2, False),
    ('Aruba', 'Aruban Florin', 'AWG', 533, 2, False),
    ('Australia', 'Australian Dollar', 'AUD', 36, 2, False),
    ('Austria', 'Euro', 'EUR', 978, 2, False),
    ('Azerbaijan', 'Azerbaijan Manat', 'AZN', 944, 2, False),
    ('Bahamas (The)', 'Bahamian Dollar', 'BSD', 44, 2, False),
    ('Bahrain', 'Bahraini Dinar', 'BHD', 48, 3, False),
    ('Bangladesh', 'Taka', 'BDT', 50, 2, False),
    ('Barbados', 'Barbados Dollar', 'BBD', 52, 2, False),
    ('Belarus', 'Belarusian Ruble', 'BYN', 933, 2, False),
    ('Belgium', 'Euro', 'EUR', 978, 2, False),
    ('Belize', 'Belize Dollar', 'BZD', 84, 2, False),
    ('Benin', 'CFA Franc BCEAO', 'XOF', 952, 0, False),
    ('Bermuda', 'Bermudian Dollar', 'BMD', 60, 2, False),
    ('Bhutan', 'Indian Rupee', 'INR', 356, 2, False),
    ('Bhutan', 'Ngultrum', 'BTN', 64, 2, False),
    ('Bolivia (Plurinational State Of)', 'Boliviano', 'BOB', 68, 2, False),
    ('Bolivia (Plurinational State Of)', 'Mvdol', 'BOV', 984, 2, True),
    ('Bonaire, Sint Eustatius And Saba', 'US Dollar', 'USD', 840, 2, False),
    ('Bosnia And Herzegovina', 'Convertible Mark', 'BAM', 977, 2, False),
    ('Botswana', 'Pula', 'BWP', 72, 2, False),
    ('Bouvet Island', 'Norwegian Krone', 'NOK', 578, 2, False),
    ('Brazil', 'Brazilian Real', 'BRL', 986, 2, False),
    ('British Indian Ocean Territory (The)', 'US Dollar', 'USD', 840, 2, False),
    ('Brunei Darussalam', 'Brunei Dollar', 'BND', 96, 2, False),
    ('Bulgaria', 'Bulgarian Lev', 'BGN', 975, 2, False),
    ('Burkina Faso', 'CFA Franc BCEAO', 'XOF', 952, 0, False),
    ('Burundi', 'Burundi Franc', 'BIF', 108, 0, False),
    ('Cabo Verde', 'Cabo Verde Escudo', 'CVE', 132, 2, False),
    ('Cambodia', 'Riel', 'KHR', 116, 2, False),
    ('Cameroon', 'CFA Franc BEAC', 'XAF', 950, 0, False),
    ('Canada', 'Canadian Dollar', 'CAD', 124, 2, False),
    ('Cayman Islands (The)', 'Cayman Islands Dollar', 'KYD', 136, 2, False),
    ('Central African Republic (The)', 'CFA Franc BEAC', 'XAF', 950, 0, False),
    ('Chad', 'CFA Franc BEAC', 'XAF', 950, 0, False),
    ('Chile', 'Chilean Peso', 'CLP', 152, 0, False),
    ('Chile', 'Unidad de Fomento', 'CLF', 990, 4, True),
    ('China', 'Yuan Renminbi', 'CNY', 156, 2, False),
    ('Christmas Island', 'Australian Dollar', 'AUD', 36, 2, False),
    ('Cocos (Keeling) Islands (The)', 'Australian Dollar', 'AUD', 36, 2, False),
    ('Colombia', 'Colombian Peso', 'COP', 170, 2, False),
    ('Colombia', 'Unidad de Valor Real', 'COU', 970, 2, True),
    ('Comoros (The)', 'Comorian Franc ', 'KMF', 174, 0, False),
    (
        'Congo (The Democratic Republic Of The)',
        'Congolese Franc',
        'CDF',
        976,
        2,
        False,
    ),
    ('Congo (The)', 'CFA Franc BEAC', 'XAF', 950, 0, False),
    ('Cook Islands (The)', 'New Zealand Dollar', 'NZD', 554, 2, False),
    ('Costa Rica', 'Costa Rican Colon', 'CRC', 188, 2, False),
    ('Croatia', 'Kuna', 'HRK', 191, 2, False),
    ('Cuba', 'Cuban Peso', 'CUP', 192, 2, False),
    ('Cuba', 'Peso Convertible', 'CUC', 931, 2, False),
    ('Curaçao', 'Netherlands Antillean Guilder', 'ANG', 532, 2, False),
    ('Cyprus', 'Euro', 'EUR', 978, 2, False),
    ('Czechia', 'Czech Koruna', 'CZK', 203, 2, False),
    ("Côte D'ivoire", 'CFA Franc BCEAO', 'XOF', 952, 0, False),
    ('Denmark', 'Danish Krone', 'DKK', 208, 2, False),
    ('Djibouti', 'Djibouti Franc', 'DJF', 262, 0, False),
    ('Dominica', 'East Caribbean Dollar', 'XCD', 951, 2, False),
    ('Dominican Republic (The)', 'Dominican Peso', 'DOP', 214, 2, False),
    ('Ecuador', 'US Dollar', 'USD', 840, 2, False),
    ('Egypt', 'Egyptian Pound', 'EGP', 818, 2, False),
    ('El Salvador', 'El Salvador Colon', 'SVC', 222, 2, False),
    ('El Salvador', 'US Dollar', 'USD', 840, 2, False),
    ('Equatorial Guinea', 'CFA Franc BEAC', 'XAF', 950, 0, False),
    ('Eritrea', 'Nakfa', 'ERN', 232, 2, False),
    ('Estonia', 'Euro', 'EUR', 978, 2, False),
    ('Eswatini', 'Lilangeni', 'SZL', 748, 2, False),
    ('Ethiopia', 'Ethiopian Birr', 'ETB', 230, 2, False),
    ('European Union', 'Euro', 'EUR', 978, 2, False),
    (
        'Falkland Islands (The) [Malvinas]',
        'Falkland Islands Pound',
        'FKP',
        238,
        2,
        False,
    ),
    ('Faroe Islands (The)', 'Danish Krone', 'DKK', 208, 2, False),
    ('Fiji', 'Fiji Dollar', 'FJD', 242, 2, False),
    ('Finland', 'Euro', 'EUR', 978, 2, False),
    ('France', 'Euro', 'EUR', 978, 2, False),
    ('French Guiana', 'Euro', 'EUR', 978, 2, False),
    ('French Polynesia', 'CFP Franc', 'XPF', 953, 0, False),
    ('French Southern Territories (The)', 'Euro', 'EUR', 978, 2, False),
    ('Gabon', 'CFA Franc BEAC', 'XAF', 950, 0, False),
    ('Gambia (The)', 'Dalasi', 'GMD', 270, 2, False),
    ('Georgia', 'Lari', 'GEL', 981, 2, False),
    ('Germany', 'Euro', 'EUR', 978, 2, False),
    ('Ghana', 'Ghana Cedi', 'GHS', 936, 2, False),
    ('Gibraltar', 'Gibraltar Pound', 'GIP', 292, 2, False),
    ('Greece', 'Euro', 'EUR', 978, 2, False),
    ('Greenland', 'Danish Krone', 'DKK', 208, 2, False),
    ('Grenada', 'East Caribbean Dollar', 'XCD', 951, 2, False),
    ('Guadeloupe', 'Euro', 'EUR', 978, 2, False),
    ('Guam', 'US Dollar', 'USD', 840, 2, False),
    ('Guatemala', 'Quetzal', 'GTQ', 320, 2, False),
    ('Guernsey', 'Pound Sterling', 'GBP', 826, 2, False),
    ('Guinea', 'Guinean Franc', 'GNF', 324, 0, False),
    ('Guinea-bissau', 'CFA Franc BCEAO', 'XOF', 952, 0, False),
    ('Guyana', 'Guyana Dollar', 'GYD', 328, 2, False),
    ('Haiti', 'Gourde', 'HTG', 332, 2, False),
    ('Haiti', 'US Dollar', 'USD', 840, 2, False),
    ('Heard Island And Mcdonald Islands', 'Australian Dollar', 'AUD', 36, 2, False),
    ('Holy See (The)', 'Euro', 'EUR', 978, 2, False),
    ('Honduras', 'Lempira', 'HNL', 340, 2, False),
    ('Hong Kong', 'Hong Kong Dollar', 'HKD', 344, 2, False),
    ('Hungary', 'Forint', 'HUF', 348, 2, False),
    ('Iceland', 'Iceland Krona', 'ISK', 352, 0, False),
    ('India', 'Indian Rupee', 'INR', 356, 2, False),
    ('Indonesia', 'Rupiah', 'IDR', 360, 2, False),
    (
        'International Monetary Fund (Imf)',
        'SDR (Special Drawing Right)',
        'XDR',
        960,
        0,
        False,
    ),
    ('Iran (Islamic Republic Of)', 'Iranian Rial', 'IRR', 364, 2, False),
    ('Iraq', 'Iraqi Dinar', 'IQD', 368, 3, False),
    ('Ireland', 'Euro', 'EUR', 978, 2, False),
    ('Isle Of Man', 'Pound Sterling', 'GBP', 826, 2, False),
    ('Israel', 'New Israeli Sheqel', 'ILS', 376, 2, False),
    ('Italy', 'Euro', 'EUR', 978, 2, False),
    ('Jamaica', 'Jamaican Dollar', 'JMD', 388, 2, False),
    ('Japan', 'Yen', 'JPY', 392, 0, False),
    ('Jersey', 'Pound Sterling', 'GBP', 826, 2, False),
    ('Jordan', 'Jordanian Dinar', 'JOD', 400, 3, False),
    ('Kazakhstan', 'Tenge', 'KZT', 398, 2, False),
    ('Kenya', 'Kenyan Shilling', 'KES', 404, 2, False),
    ('Kiribati', 'Australian Dollar', 'AUD', 36, 2, False),
    (
        'Korea (The Democratic People’s Republic Of)',
        'North Korean Won',
        'KPW',
        408,
        2,
        False,
    ),
    ('Korea (The Republic Of)', 'Won', 'KRW', 410, 0, False),
    ('Kuwait', 'Kuwaiti Dinar', 'KWD', 414, 3, False),
    ('Kyrgyzstan', 'Som', 'KGS', 417, 2, False),
    ('Lao People’s Democratic Republic (The)', 'Lao Kip', 'LAK', 418, 2, False),
    ('Latvia', 'Euro', 'EUR', 978, 2, False),
    ('Lebanon', 'Lebanese Pound', 'LBP', 422, 2, False),
    ('Lesotho', 'Loti', 'LSL', 426, 2, False),
    ('Lesotho', 'Rand', 'ZAR', 710, 2, False),
    ('Liberia', 'Liberian Dollar', 'LRD', 430, 2, False),
    ('Libya', 'Libyan Dinar', 'LYD', 434, 3, False),
    ('Liechtenstein', 'Swiss Franc', 'CHF', 756, 2, False),
    ('Lithuania', 'Euro', 'EUR', 978, 2, False),
    ('Luxembourg', 'Euro', 'EUR', 978, 2, False),
    ('Macao', 'Pataca', 'MOP', 446, 2, False),
    ('Madagascar', 'Malagasy Ariary', 'MGA', 969, 2, False),
    ('Malawi', 'Malawi Kwacha', 'MWK', 454, 2, False),
    ('Malaysia', 'Malaysian Ringgit', 'MYR', 458, 2, False),
    ('Maldives', 'Rufiyaa', 'MVR', 462, 2, False),
    ('Mali', 'CFA Franc BCEAO', 'XOF', 952, 0, False),
    ('Malta', 'Euro', 'EUR', 978, 2, False),
    ('Marshall Islands (The)', 'US Dollar', 'USD', 840, 2, False),
    ('Martinique', 'Euro', 'EUR', 978, 2, False),
    ('Mauritania', 'Ouguiya', 'MRU', 929, 2, False),
    ('Mauritius', 'Mauritius Rupee', 'MUR', 480, 2, False),
    ('Mayotte', 'Euro', 'EUR', 978, 2, False),
    (
        'Member Countries Of The African Development Bank Group',
        'ADB Unit of Account',
        'XUA',
        965,
        0,
        False,
    ),
    ('Mexico', 'Mexican Peso', 'MXN', 484, 2, False),
    ('Mexico', 'Mexican Unidad de Inversion (UDI)', 'MXV', 979, 2, True),
    ('Micronesia (Federated States Of)', 'US Dollar', 'USD', 840, 2, False),
    ('Moldova (The Republic Of)', 'Moldovan Leu', 'MDL', 498, 2, False),
    ('Monaco', 'Euro', 'EUR', 978, 2, False),
    ('Mongolia', 'Tugrik', 'MNT', 496, 2, False),
    ('Montenegro', 'Euro', 'EUR', 978, 2, False),
    ('Montserrat', 'East Caribbean Dollar', 'XCD', 951, 2, False),
    ('Morocco', 'Moroccan Dirham', 'MAD', 504, 2, False),
    ('Mozambique', 'Mozambique Metical', 'MZN', 943, 2, False),
    ('Myanmar', 'Kyat', 'MMK', 104, 2, False),
    ('Namibia', 'Namibia Dollar', 'NAD', 516, 2, False),
    ('Namibia', 'Rand', 'ZAR', 710, 2, False),
    ('Nauru', 'Australian Dollar', 'AUD', 36, 2, False),
    ('Nepal', 'Nepalese Rupee', 'NPR', 524, 2, False),
    ('Netherlands (The)', 'Euro', 'EUR', 978, 2, False),
    ('New Caledonia', 'CFP Franc', 'XPF', 953, 0, False),
    ('New Zealand', 'New Zealand Dollar', 'NZD', 554, 2, False),
    ('Nicaragua', 'Cordoba Oro', 'NIO', 558, 2, False),
    ('Niger (The)', 'CFA Franc BCEAO', 'XOF', 952, 0, False),
    ('Nigeria', 'Naira', 'NGN', 566, 2, False),
    ('Niue', 'New Zealand Dollar', 'NZD', 554, 2, False),
    ('Norfolk Island', 'Australian Dollar', 'AUD', 36, 2, False),
    ('North Macedonia', 'Denar', 'MKD', 807, 2, False),
    ('Northern Mariana Islands (The)', 'US Dollar', 'USD', 840, 2, False),
    ('Norway', 'Norwegian Krone', 'NOK', 578, 2, False),
    ('Oman', 'Rial Omani', 'OMR', 512, 3, False),
    ('Pakistan', 'Pakistan Rupee', 'PKR', 586, 2, False),
    ('Palau', 'US Dollar', 'USD', 840, 2, False),
    ('Palestine, State Of', 'No universal currency', '', None, 0, False),
    ('Panama', 'Balboa', 'PAB', 590, 2, False),
    ('Panama', 'US Dollar', 'USD', 840, 2, False),
    ('Papua New Guinea', 'Kina', 'PGK', 598, 2, False),
    ('Paraguay', 'Guarani', 'PYG', 600, 0, False),
    ('Peru', 'Sol', 'PEN', 604, 2, False),
    ('Philippines (The)', 'Philippine Peso', 'PHP', 608, 2, False),
    ('Pitcairn', 'New Zealand Dollar', 'NZD', 554, 2, False),
    ('Poland', 'Zloty', 'PLN', 985, 2, False),
    ('Portugal', 'Euro', 'EUR', 978, 2, False),
    ('Puerto Rico', 'US Dollar', 'USD', 840, 2, False),
    ('Qatar', 'Qatari Rial', 'QAR', 634, 2, False),
    ('Romania', 'Romanian Leu', 'RON', 946, 2, False),
    ('Russian Federation (The)', 'Russian Ruble', 'RUB', 643, 2, False),
    ('Rwanda', 'Rwanda Franc', 'RWF', 646, 0, False),
    ('Réunion', 'Euro', 'EUR', 978, 2, False),
    ('Saint Barthélemy', 'Euro', 'EUR', 978, 2, False),
    (
        'Saint Helena, Ascension And Tristan Da Cunha',
        'Saint Helena Pound',
        'SHP',
        654,
        2,
        False,
    ),
    ('Saint Kitts And Nevis', 'East Caribbean Dollar', 'XCD', 951, 2, False),
    ('Saint Lucia', 'East Caribbean Dollar', 'XCD', 951, 2, False),
    ('Saint Martin (French Part)', 'Euro', 'EUR', 978, 2, False),
    ('Saint Pierre And Miquelon', 'Euro', 'EUR', 978, 2, False),
    (
        'Saint Vincent And The Grenadines',
        'East Caribbean Dollar',
        'XCD',
        951,
        2,
        False,
    ),
    ('Samoa', 'Tala', 'WST', 882, 2, False),
    ('San Marino', 'Euro', 'EUR', 978, 2, False),
    ('Sao Tome And Principe', 'Dobra', 'STN', 930, 2, False),
    ('Saudi Arabia', 'Saudi Riyal', 'SAR', 682, 2, False),
    ('Senegal', 'CFA Franc BCEAO', 'XOF', 952, 0, False),
    ('Serbia', 'Serbian Dinar', 'RSD', 941, 2, False),
    ('Seychelles', 'Seychelles Rupee', 'SCR', 690, 2, False),
    ('Sierra Leone', 'Leone', 'SLL', 694, 2, False),
    ('Singapore', 'Singapore Dollar', 'SGD', 702, 2, False),
    (
        'Sint Maarten (Dutch Part)',
        'Netherlands Antillean Guilder',
        'ANG',
        532,
        2,
        False,
    ),
    (
        "Sistema Unitario De Compensacion Regional De Pagos 'Sucre'",
        'Sucre',
        'XSU',
        994,
        0,
        False,
    ),
    ('Slovakia', 'Euro', 'EUR', 978, 2, False),
    ('Slovenia', 'Euro', 'EUR', 978, 2, False),
    ('Solomon Islands', 'Solomon Islands Dollar', 'SBD', 90, 2, False),
    ('Somalia', 'Somali Shilling', 'SOS', 706, 2, False),
    ('South Africa', 'Rand', 'ZAR', 710, 2, False),
    (
        'South Georgia And The South Sandwich Islands',
        'No universal currency',
        '',
        None,
        0,
        False,
    ),
    ('South Sudan', 'South Sudanese Pound', 'SSP', 728, 2, False),
    ('Spain', 'Euro', 'EUR', 978, 2, False),
    ('Sri Lanka', 'Sri Lanka Rupee', 'LKR', 144, 2, False),
    ('Sudan (The)', 'Sudanese Pound', 'SDG', 938, 2, False),
    ('Suriname', 'Surinam Dollar', 'SRD', 968, 2, False),
    ('Svalbard And Jan Mayen', 'Norwegian Krone', 'NOK', 578, 2, False),
    ('Sweden', 'Swedish Krona', 'SEK', 752, 2, False),
    ('Switzerland', 'Swiss Franc', 'CHF', 756, 2, False),
    ('Switzerland', 'WIR Euro', 'CHE', 947, 2, True),
    ('Switzerland', 'WIR Franc', 'CHW', 948, 2, True),
    ('Syrian Arab Republic', 'Syrian Pound', 'SYP', 760, 2, False),
    ('Taiwan (Province Of China)', 'New Taiwan Dollar', 'TWD', 901, 2, False),
    ('Tajikistan', 'Somoni', 'TJS', 972, 2, False),
    ('Tanzania, United Republic Of', 'Tanzanian Shilling', 'TZS', 834, 2, False),
    ('Thailand', 'Baht', 'THB', 764, 2, False),
    ('Timor-leste', 'US Dollar', 'USD', 840, 2, False),
    ('Togo', 'CFA Franc BCEAO', 'XOF', 952, 0, False),
    ('Tokelau', 'New Zealand Dollar', 'NZD', 554, 2, False),
    ('Tonga', 'Pa’anga', 'TOP', 776, 2, False),
    ('Trinidad And Tobago', 'Trinidad and Tobago Dollar', 'TTD', 780, 2, False),
    ('Tunisia', 'Tunisian Dinar', 'TND', 788, 3, False),
    ('Turkey', 'Turkish Lira', 'TRY', 949, 2, False),
    ('Turkmenistan', 'Turkmenistan New Manat', 'TMT', 934, 2, False),
    ('Turks And Caicos Islands (The)', 'US Dollar', 'USD', 840, 2, False),
    ('Tuvalu', 'Australian Dollar', 'AUD', 36, 2, False),
    ('Uganda', 'Uganda Shilling', 'UGX', 800, 0, False),
    ('Ukraine', 'Hryvnia', 'UAH', 980, 2, False),
    ('United Arab Emirates (The)', 'UAE Dirham', 'AED', 784, 2, False),
    (
        'United Kingdom Of Great Britain And Northern Ireland (The)',
        'Pound Sterling',
        'GBP',
        826,
        2,
        False,
    ),
    ('United States Minor Outlying Islands (The)', 'US Dollar', 'USD', 840, 2, False),
    ('United States Of America (The)', 'US Dollar', 'USD', 840, 2, False),
    ('United States Of America (The)', 'US Dollar (Next day)', 'USN', 997, 2, True),
    ('Uruguay', 'Peso Uruguayo', 'UYU', 858, 2, False),
    ('Uruguay', 'Uruguay Peso en Unidades Indexadas (UI)', 'UYI', 940, 0, True),
    ('Uruguay', 'Unidad Previsional', 'UYW', 927, 4, False),
    ('Uzbekistan', 'Uzbekistan Sum', 'UZS', 860, 2, False),
    ('Vanuatu', 'Vatu', 'VUV', 548, 0, False),
    ('Venezuela (Bolivarian Republic Of)', 'Bolívar Soberano', 'VES', 928, 2, False),
    ('Venezuela (Bolivarian Republic Of)', 'Bolívar Soberano', 'VED', 926, 2, False),
    ('Viet Nam', 'Dong', 'VND', 704, 0, False),
    ('Virgin Islands (British)', 'US Dollar', 'USD', 840, 2, False),
    ('Virgin Islands (U.s.)', 'US Dollar', 'USD', 840, 2, False),
    ('Wallis And Futuna', 'CFP Franc', 'XPF', 953, 0, False),
    ('Western Sahara', 'Moroccan Dirham', 'MAD', 504, 2, False),
    ('Yemen', 'Yemeni Rial', 'YER', 886, 2, False),
    ('Zambia', 'Zambian Kwacha', 'ZMW', 967, 2, False),
    ('Zimbabwe', 'Zimbabwe Dollar', 'ZWL', 932, 2, False),
    (
        'Zz01_bond Markets Unit European_eurco',
        'Bond Markets Unit European Composite Unit (EURCO)',
        'XBA',
        955,
        0,
        False,
    ),
    (
        'Zz02_bond Markets Unit European_emu-6',
        'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
        'XBB',
        956,
        0,
        False,
    ),
    (
        'Zz03_bond Markets Unit European_eua-9',
        'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
        'XBC',
        957,
        0,
        False,
    ),
    (
        'Zz04_bond Markets Unit European_eua-17',
        'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
        'XBD',
        958,
        0,
        False,
    ),
    (
        'Zz06_testing_code',
        'Codes specifically reserved for testing purposes',
        'XTS',
        963,
        0,
        False,
    ),
    (
        'Zz07_no_currency',
        'The codes assigned for transactions where no currency is involved',
        'XXX',
        999,
        0,
        False,
    ),
    ('Zz08_gold', 'Gold', 'XAU', 959, 0, False),
    ('Zz09_palladium', 'Palladium', 'XPD', 964, 0, False),
    ('Zz10_platinum', 'Platinum', 'XPT', 962, 0, False),
    ('Zz11_silver', 'Silver', 'XAG', 961, 0, False),
    ('ÅLand Islands', 'Euro', 'EUR', 978, 2, False),
)
