# pylint: disable=too-many-lines
CURRENCIES = [
    {
        'entity': 'Afghanistan',
        'currency': 'Afghani',
        'code': 'AFN',
        'num': 971,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Albania',
        'currency': 'Lek',
        'code': 'ALL',
        'num': 8,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Algeria',
        'currency': 'Algerian Dinar',
        'code': 'DZD',
        'num': 12,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'American Samoa',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Andorra',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Angola',
        'currency': 'Kwanza',
        'code': 'AOA',
        'num': 973,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Anguilla',
        'currency': 'East Caribbean Dollar',
        'code': 'XCD',
        'num': 951,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Antarctica',
        'currency': 'No universal currency',
        'code': '',
        'num': None,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Antigua And Barbuda',
        'currency': 'East Caribbean Dollar',
        'code': 'XCD',
        'num': 951,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Argentina',
        'currency': 'Argentine Peso',
        'code': 'ARS',
        'num': 32,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Armenia',
        'currency': 'Armenian Dram',
        'code': 'AMD',
        'num': 51,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Aruba',
        'currency': 'Aruban Florin',
        'code': 'AWG',
        'num': 533,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Australia',
        'currency': 'Australian Dollar',
        'code': 'AUD',
        'num': 36,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Austria',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Azerbaijan',
        'currency': 'Azerbaijan Manat',
        'code': 'AZN',
        'num': 944,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Bahamas (The)',
        'currency': 'Bahamian Dollar',
        'code': 'BSD',
        'num': 44,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Bahrain',
        'currency': 'Bahraini Dinar',
        'code': 'BHD',
        'num': 48,
        'minors': 3,
        'fund': False,
    },
    {
        'entity': 'Bangladesh',
        'currency': 'Taka',
        'code': 'BDT',
        'num': 50,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Barbados',
        'currency': 'Barbados Dollar',
        'code': 'BBD',
        'num': 52,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Belarus',
        'currency': 'Belarusian Ruble',
        'code': 'BYN',
        'num': 933,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Belgium',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Belize',
        'currency': 'Belize Dollar',
        'code': 'BZD',
        'num': 84,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Benin',
        'currency': 'CFA Franc BCEAO',
        'code': 'XOF',
        'num': 952,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Bermuda',
        'currency': 'Bermudian Dollar',
        'code': 'BMD',
        'num': 60,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Bhutan',
        'currency': 'Indian Rupee',
        'code': 'INR',
        'num': 356,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Bhutan',
        'currency': 'Ngultrum',
        'code': 'BTN',
        'num': 64,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Bolivia (Plurinational State Of)',
        'currency': 'Boliviano',
        'code': 'BOB',
        'num': 68,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Bolivia (Plurinational State Of)',
        'currency': 'Mvdol',
        'code': 'BOV',
        'num': 984,
        'minors': 2,
        'fund': True,
    },
    {
        'entity': 'Bonaire, Sint Eustatius And Saba',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Bosnia And Herzegovina',
        'currency': 'Convertible Mark',
        'code': 'BAM',
        'num': 977,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Botswana',
        'currency': 'Pula',
        'code': 'BWP',
        'num': 72,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Bouvet Island',
        'currency': 'Norwegian Krone',
        'code': 'NOK',
        'num': 578,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Brazil',
        'currency': 'Brazilian Real',
        'code': 'BRL',
        'num': 986,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'British Indian Ocean Territory (The)',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Brunei Darussalam',
        'currency': 'Brunei Dollar',
        'code': 'BND',
        'num': 96,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Bulgaria',
        'currency': 'Bulgarian Lev',
        'code': 'BGN',
        'num': 975,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Burkina Faso',
        'currency': 'CFA Franc BCEAO',
        'code': 'XOF',
        'num': 952,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Burundi',
        'currency': 'Burundi Franc',
        'code': 'BIF',
        'num': 108,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Cabo Verde',
        'currency': 'Cabo Verde Escudo',
        'code': 'CVE',
        'num': 132,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Cambodia',
        'currency': 'Riel',
        'code': 'KHR',
        'num': 116,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Cameroon',
        'currency': 'CFA Franc BEAC',
        'code': 'XAF',
        'num': 950,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Canada',
        'currency': 'Canadian Dollar',
        'code': 'CAD',
        'num': 124,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Cayman Islands (The)',
        'currency': 'Cayman Islands Dollar',
        'code': 'KYD',
        'num': 136,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Central African Republic (The)',
        'currency': 'CFA Franc BEAC',
        'code': 'XAF',
        'num': 950,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Chad',
        'currency': 'CFA Franc BEAC',
        'code': 'XAF',
        'num': 950,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Chile',
        'currency': 'Chilean Peso',
        'code': 'CLP',
        'num': 152,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Chile',
        'currency': 'Unidad de Fomento',
        'code': 'CLF',
        'num': 990,
        'minors': 4,
        'fund': True,
    },
    {
        'entity': 'China',
        'currency': 'Yuan Renminbi',
        'code': 'CNY',
        'num': 156,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Christmas Island',
        'currency': 'Australian Dollar',
        'code': 'AUD',
        'num': 36,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Cocos (Keeling) Islands (The)',
        'currency': 'Australian Dollar',
        'code': 'AUD',
        'num': 36,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Colombia',
        'currency': 'Colombian Peso',
        'code': 'COP',
        'num': 170,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Colombia',
        'currency': 'Unidad de Valor Real',
        'code': 'COU',
        'num': 970,
        'minors': 2,
        'fund': True,
    },
    {
        'entity': 'Comoros (The)',
        'currency': 'Comorian Franc ',
        'code': 'KMF',
        'num': 174,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Congo (The Democratic Republic Of The)',
        'currency': 'Congolese Franc',
        'code': 'CDF',
        'num': 976,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Congo (The)',
        'currency': 'CFA Franc BEAC',
        'code': 'XAF',
        'num': 950,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Cook Islands (The)',
        'currency': 'New Zealand Dollar',
        'code': 'NZD',
        'num': 554,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Costa Rica',
        'currency': 'Costa Rican Colon',
        'code': 'CRC',
        'num': 188,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Croatia',
        'currency': 'Kuna',
        'code': 'HRK',
        'num': 191,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Cuba',
        'currency': 'Cuban Peso',
        'code': 'CUP',
        'num': 192,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Cuba',
        'currency': 'Peso Convertible',
        'code': 'CUC',
        'num': 931,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Curaçao',
        'currency': 'Netherlands Antillean Guilder',
        'code': 'ANG',
        'num': 532,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Cyprus',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Czechia',
        'currency': 'Czech Koruna',
        'code': 'CZK',
        'num': 203,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': "Côte D'ivoire",
        'currency': 'CFA Franc BCEAO',
        'code': 'XOF',
        'num': 952,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Denmark',
        'currency': 'Danish Krone',
        'code': 'DKK',
        'num': 208,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Djibouti',
        'currency': 'Djibouti Franc',
        'code': 'DJF',
        'num': 262,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Dominica',
        'currency': 'East Caribbean Dollar',
        'code': 'XCD',
        'num': 951,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Dominican Republic (The)',
        'currency': 'Dominican Peso',
        'code': 'DOP',
        'num': 214,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Ecuador',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Egypt',
        'currency': 'Egyptian Pound',
        'code': 'EGP',
        'num': 818,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'El Salvador',
        'currency': 'El Salvador Colon',
        'code': 'SVC',
        'num': 222,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'El Salvador',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Equatorial Guinea',
        'currency': 'CFA Franc BEAC',
        'code': 'XAF',
        'num': 950,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Eritrea',
        'currency': 'Nakfa',
        'code': 'ERN',
        'num': 232,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Estonia',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Eswatini',
        'currency': 'Lilangeni',
        'code': 'SZL',
        'num': 748,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Ethiopia',
        'currency': 'Ethiopian Birr',
        'code': 'ETB',
        'num': 230,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'European Union',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Falkland Islands (The) [Malvinas]',
        'currency': 'Falkland Islands Pound',
        'code': 'FKP',
        'num': 238,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Faroe Islands (The)',
        'currency': 'Danish Krone',
        'code': 'DKK',
        'num': 208,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Fiji',
        'currency': 'Fiji Dollar',
        'code': 'FJD',
        'num': 242,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Finland',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'France',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'French Guiana',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'French Polynesia',
        'currency': 'CFP Franc',
        'code': 'XPF',
        'num': 953,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'French Southern Territories (The)',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Gabon',
        'currency': 'CFA Franc BEAC',
        'code': 'XAF',
        'num': 950,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Gambia (The)',
        'currency': 'Dalasi',
        'code': 'GMD',
        'num': 270,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Georgia',
        'currency': 'Lari',
        'code': 'GEL',
        'num': 981,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Germany',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Ghana',
        'currency': 'Ghana Cedi',
        'code': 'GHS',
        'num': 936,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Gibraltar',
        'currency': 'Gibraltar Pound',
        'code': 'GIP',
        'num': 292,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Greece',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Greenland',
        'currency': 'Danish Krone',
        'code': 'DKK',
        'num': 208,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Grenada',
        'currency': 'East Caribbean Dollar',
        'code': 'XCD',
        'num': 951,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Guadeloupe',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Guam',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Guatemala',
        'currency': 'Quetzal',
        'code': 'GTQ',
        'num': 320,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Guernsey',
        'currency': 'Pound Sterling',
        'code': 'GBP',
        'num': 826,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Guinea',
        'currency': 'Guinean Franc',
        'code': 'GNF',
        'num': 324,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Guinea-bissau',
        'currency': 'CFA Franc BCEAO',
        'code': 'XOF',
        'num': 952,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Guyana',
        'currency': 'Guyana Dollar',
        'code': 'GYD',
        'num': 328,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Haiti',
        'currency': 'Gourde',
        'code': 'HTG',
        'num': 332,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Haiti',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Heard Island And Mcdonald Islands',
        'currency': 'Australian Dollar',
        'code': 'AUD',
        'num': 36,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Holy See (The)',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Honduras',
        'currency': 'Lempira',
        'code': 'HNL',
        'num': 340,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Hong Kong',
        'currency': 'Hong Kong Dollar',
        'code': 'HKD',
        'num': 344,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Hungary',
        'currency': 'Forint',
        'code': 'HUF',
        'num': 348,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Iceland',
        'currency': 'Iceland Krona',
        'code': 'ISK',
        'num': 352,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'India',
        'currency': 'Indian Rupee',
        'code': 'INR',
        'num': 356,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Indonesia',
        'currency': 'Rupiah',
        'code': 'IDR',
        'num': 360,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'International Monetary Fund (Imf)',
        'currency': 'SDR (Special Drawing Right)',
        'code': 'XDR',
        'num': 960,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Iran (Islamic Republic Of)',
        'currency': 'Iranian Rial',
        'code': 'IRR',
        'num': 364,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Iraq',
        'currency': 'Iraqi Dinar',
        'code': 'IQD',
        'num': 368,
        'minors': 3,
        'fund': False,
    },
    {
        'entity': 'Ireland',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Isle Of Man',
        'currency': 'Pound Sterling',
        'code': 'GBP',
        'num': 826,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Israel',
        'currency': 'New Israeli Sheqel',
        'code': 'ILS',
        'num': 376,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Italy',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Jamaica',
        'currency': 'Jamaican Dollar',
        'code': 'JMD',
        'num': 388,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Japan',
        'currency': 'Yen',
        'code': 'JPY',
        'num': 392,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Jersey',
        'currency': 'Pound Sterling',
        'code': 'GBP',
        'num': 826,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Jordan',
        'currency': 'Jordanian Dinar',
        'code': 'JOD',
        'num': 400,
        'minors': 3,
        'fund': False,
    },
    {
        'entity': 'Kazakhstan',
        'currency': 'Tenge',
        'code': 'KZT',
        'num': 398,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Kenya',
        'currency': 'Kenyan Shilling',
        'code': 'KES',
        'num': 404,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Kiribati',
        'currency': 'Australian Dollar',
        'code': 'AUD',
        'num': 36,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Korea (The Democratic People’s Republic Of)',
        'currency': 'North Korean Won',
        'code': 'KPW',
        'num': 408,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Korea (The Republic Of)',
        'currency': 'Won',
        'code': 'KRW',
        'num': 410,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Kuwait',
        'currency': 'Kuwaiti Dinar',
        'code': 'KWD',
        'num': 414,
        'minors': 3,
        'fund': False,
    },
    {
        'entity': 'Kyrgyzstan',
        'currency': 'Som',
        'code': 'KGS',
        'num': 417,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Lao People’s Democratic Republic (The)',
        'currency': 'Lao Kip',
        'code': 'LAK',
        'num': 418,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Latvia',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Lebanon',
        'currency': 'Lebanese Pound',
        'code': 'LBP',
        'num': 422,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Lesotho',
        'currency': 'Loti',
        'code': 'LSL',
        'num': 426,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Lesotho',
        'currency': 'Rand',
        'code': 'ZAR',
        'num': 710,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Liberia',
        'currency': 'Liberian Dollar',
        'code': 'LRD',
        'num': 430,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Libya',
        'currency': 'Libyan Dinar',
        'code': 'LYD',
        'num': 434,
        'minors': 3,
        'fund': False,
    },
    {
        'entity': 'Liechtenstein',
        'currency': 'Swiss Franc',
        'code': 'CHF',
        'num': 756,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Lithuania',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Luxembourg',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Macao',
        'currency': 'Pataca',
        'code': 'MOP',
        'num': 446,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Madagascar',
        'currency': 'Malagasy Ariary',
        'code': 'MGA',
        'num': 969,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Malawi',
        'currency': 'Malawi Kwacha',
        'code': 'MWK',
        'num': 454,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Malaysia',
        'currency': 'Malaysian Ringgit',
        'code': 'MYR',
        'num': 458,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Maldives',
        'currency': 'Rufiyaa',
        'code': 'MVR',
        'num': 462,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Mali',
        'currency': 'CFA Franc BCEAO',
        'code': 'XOF',
        'num': 952,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Malta',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Marshall Islands (The)',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Martinique',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Mauritania',
        'currency': 'Ouguiya',
        'code': 'MRU',
        'num': 929,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Mauritius',
        'currency': 'Mauritius Rupee',
        'code': 'MUR',
        'num': 480,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Mayotte',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Member Countries Of The African Development Bank Group',
        'currency': 'ADB Unit of Account',
        'code': 'XUA',
        'num': 965,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Mexico',
        'currency': 'Mexican Peso',
        'code': 'MXN',
        'num': 484,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Mexico',
        'currency': 'Mexican Unidad de Inversion (UDI)',
        'code': 'MXV',
        'num': 979,
        'minors': 2,
        'fund': True,
    },
    {
        'entity': 'Micronesia (Federated States Of)',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Moldova (The Republic Of)',
        'currency': 'Moldovan Leu',
        'code': 'MDL',
        'num': 498,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Monaco',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Mongolia',
        'currency': 'Tugrik',
        'code': 'MNT',
        'num': 496,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Montenegro',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Montserrat',
        'currency': 'East Caribbean Dollar',
        'code': 'XCD',
        'num': 951,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Morocco',
        'currency': 'Moroccan Dirham',
        'code': 'MAD',
        'num': 504,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Mozambique',
        'currency': 'Mozambique Metical',
        'code': 'MZN',
        'num': 943,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Myanmar',
        'currency': 'Kyat',
        'code': 'MMK',
        'num': 104,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Namibia',
        'currency': 'Namibia Dollar',
        'code': 'NAD',
        'num': 516,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Namibia',
        'currency': 'Rand',
        'code': 'ZAR',
        'num': 710,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Nauru',
        'currency': 'Australian Dollar',
        'code': 'AUD',
        'num': 36,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Nepal',
        'currency': 'Nepalese Rupee',
        'code': 'NPR',
        'num': 524,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Netherlands (The)',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'New Caledonia',
        'currency': 'CFP Franc',
        'code': 'XPF',
        'num': 953,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'New Zealand',
        'currency': 'New Zealand Dollar',
        'code': 'NZD',
        'num': 554,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Nicaragua',
        'currency': 'Cordoba Oro',
        'code': 'NIO',
        'num': 558,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Niger (The)',
        'currency': 'CFA Franc BCEAO',
        'code': 'XOF',
        'num': 952,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Nigeria',
        'currency': 'Naira',
        'code': 'NGN',
        'num': 566,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Niue',
        'currency': 'New Zealand Dollar',
        'code': 'NZD',
        'num': 554,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Norfolk Island',
        'currency': 'Australian Dollar',
        'code': 'AUD',
        'num': 36,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'North Macedonia',
        'currency': 'Denar',
        'code': 'MKD',
        'num': 807,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Northern Mariana Islands (The)',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Norway',
        'currency': 'Norwegian Krone',
        'code': 'NOK',
        'num': 578,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Oman',
        'currency': 'Rial Omani',
        'code': 'OMR',
        'num': 512,
        'minors': 3,
        'fund': False,
    },
    {
        'entity': 'Pakistan',
        'currency': 'Pakistan Rupee',
        'code': 'PKR',
        'num': 586,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Palau',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Palestine, State Of',
        'currency': 'No universal currency',
        'code': '',
        'num': None,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Panama',
        'currency': 'Balboa',
        'code': 'PAB',
        'num': 590,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Panama',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Papua New Guinea',
        'currency': 'Kina',
        'code': 'PGK',
        'num': 598,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Paraguay',
        'currency': 'Guarani',
        'code': 'PYG',
        'num': 600,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Peru',
        'currency': 'Sol',
        'code': 'PEN',
        'num': 604,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Philippines (The)',
        'currency': 'Philippine Peso',
        'code': 'PHP',
        'num': 608,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Pitcairn',
        'currency': 'New Zealand Dollar',
        'code': 'NZD',
        'num': 554,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Poland',
        'currency': 'Zloty',
        'code': 'PLN',
        'num': 985,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Portugal',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Puerto Rico',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Qatar',
        'currency': 'Qatari Rial',
        'code': 'QAR',
        'num': 634,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Romania',
        'currency': 'Romanian Leu',
        'code': 'RON',
        'num': 946,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Russian Federation (The)',
        'currency': 'Russian Ruble',
        'code': 'RUB',
        'num': 643,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Rwanda',
        'currency': 'Rwanda Franc',
        'code': 'RWF',
        'num': 646,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Réunion',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Saint Barthélemy',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Saint Helena, Ascension And Tristan Da Cunha',
        'currency': 'Saint Helena Pound',
        'code': 'SHP',
        'num': 654,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Saint Kitts And Nevis',
        'currency': 'East Caribbean Dollar',
        'code': 'XCD',
        'num': 951,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Saint Lucia',
        'currency': 'East Caribbean Dollar',
        'code': 'XCD',
        'num': 951,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Saint Martin (French Part)',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Saint Pierre And Miquelon',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Saint Vincent And The Grenadines',
        'currency': 'East Caribbean Dollar',
        'code': 'XCD',
        'num': 951,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Samoa',
        'currency': 'Tala',
        'code': 'WST',
        'num': 882,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'San Marino',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Sao Tome And Principe',
        'currency': 'Dobra',
        'code': 'STN',
        'num': 930,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Saudi Arabia',
        'currency': 'Saudi Riyal',
        'code': 'SAR',
        'num': 682,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Senegal',
        'currency': 'CFA Franc BCEAO',
        'code': 'XOF',
        'num': 952,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Serbia',
        'currency': 'Serbian Dinar',
        'code': 'RSD',
        'num': 941,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Seychelles',
        'currency': 'Seychelles Rupee',
        'code': 'SCR',
        'num': 690,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Sierra Leone',
        'currency': 'Leone',
        'code': 'SLL',
        'num': 694,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Singapore',
        'currency': 'Singapore Dollar',
        'code': 'SGD',
        'num': 702,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Sint Maarten (Dutch Part)',
        'currency': 'Netherlands Antillean Guilder',
        'code': 'ANG',
        'num': 532,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': "Sistema Unitario De Compensacion Regional De Pagos 'Sucre'",
        'currency': 'Sucre',
        'code': 'XSU',
        'num': 994,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Slovakia',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Slovenia',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Solomon Islands',
        'currency': 'Solomon Islands Dollar',
        'code': 'SBD',
        'num': 90,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Somalia',
        'currency': 'Somali Shilling',
        'code': 'SOS',
        'num': 706,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'South Africa',
        'currency': 'Rand',
        'code': 'ZAR',
        'num': 710,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'South Georgia And The South Sandwich Islands',
        'currency': 'No universal currency',
        'code': '',
        'num': None,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'South Sudan',
        'currency': 'South Sudanese Pound',
        'code': 'SSP',
        'num': 728,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Spain',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Sri Lanka',
        'currency': 'Sri Lanka Rupee',
        'code': 'LKR',
        'num': 144,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Sudan (The)',
        'currency': 'Sudanese Pound',
        'code': 'SDG',
        'num': 938,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Suriname',
        'currency': 'Surinam Dollar',
        'code': 'SRD',
        'num': 968,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Svalbard And Jan Mayen',
        'currency': 'Norwegian Krone',
        'code': 'NOK',
        'num': 578,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Sweden',
        'currency': 'Swedish Krona',
        'code': 'SEK',
        'num': 752,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Switzerland',
        'currency': 'Swiss Franc',
        'code': 'CHF',
        'num': 756,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Switzerland',
        'currency': 'WIR Euro',
        'code': 'CHE',
        'num': 947,
        'minors': 2,
        'fund': True,
    },
    {
        'entity': 'Switzerland',
        'currency': 'WIR Franc',
        'code': 'CHW',
        'num': 948,
        'minors': 2,
        'fund': True,
    },
    {
        'entity': 'Syrian Arab Republic',
        'currency': 'Syrian Pound',
        'code': 'SYP',
        'num': 760,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Taiwan (Province Of China)',
        'currency': 'New Taiwan Dollar',
        'code': 'TWD',
        'num': 901,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Tajikistan',
        'currency': 'Somoni',
        'code': 'TJS',
        'num': 972,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Tanzania, United Republic Of',
        'currency': 'Tanzanian Shilling',
        'code': 'TZS',
        'num': 834,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Thailand',
        'currency': 'Baht',
        'code': 'THB',
        'num': 764,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Timor-leste',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Togo',
        'currency': 'CFA Franc BCEAO',
        'code': 'XOF',
        'num': 952,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Tokelau',
        'currency': 'New Zealand Dollar',
        'code': 'NZD',
        'num': 554,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Tonga',
        'currency': 'Pa’anga',
        'code': 'TOP',
        'num': 776,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Trinidad And Tobago',
        'currency': 'Trinidad and Tobago Dollar',
        'code': 'TTD',
        'num': 780,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Tunisia',
        'currency': 'Tunisian Dinar',
        'code': 'TND',
        'num': 788,
        'minors': 3,
        'fund': False,
    },
    {
        'entity': 'Turkey',
        'currency': 'Turkish Lira',
        'code': 'TRY',
        'num': 949,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Turkmenistan',
        'currency': 'Turkmenistan New Manat',
        'code': 'TMT',
        'num': 934,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Turks And Caicos Islands (The)',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Tuvalu',
        'currency': 'Australian Dollar',
        'code': 'AUD',
        'num': 36,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Uganda',
        'currency': 'Uganda Shilling',
        'code': 'UGX',
        'num': 800,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Ukraine',
        'currency': 'Hryvnia',
        'code': 'UAH',
        'num': 980,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'United Arab Emirates (The)',
        'currency': 'UAE Dirham',
        'code': 'AED',
        'num': 784,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'United Kingdom Of Great Britain And Northern Ireland (The)',
        'currency': 'Pound Sterling',
        'code': 'GBP',
        'num': 826,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'United States Minor Outlying Islands (The)',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'United States Of America (The)',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'United States Of America (The)',
        'currency': 'US Dollar (Next day)',
        'code': 'USN',
        'num': 997,
        'minors': 2,
        'fund': True,
    },
    {
        'entity': 'Uruguay',
        'currency': 'Peso Uruguayo',
        'code': 'UYU',
        'num': 858,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Uruguay',
        'currency': 'Uruguay Peso en Unidades Indexadas (UI)',
        'code': 'UYI',
        'num': 940,
        'minors': 0,
        'fund': True,
    },
    {
        'entity': 'Uruguay',
        'currency': 'Unidad Previsional',
        'code': 'UYW',
        'num': 927,
        'minors': 4,
        'fund': False,
    },
    {
        'entity': 'Uzbekistan',
        'currency': 'Uzbekistan Sum',
        'code': 'UZS',
        'num': 860,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Vanuatu',
        'currency': 'Vatu',
        'code': 'VUV',
        'num': 548,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Venezuela (Bolivarian Republic Of)',
        'currency': 'Bolívar Soberano',
        'code': 'VES',
        'num': 928,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Venezuela (Bolivarian Republic Of)',
        'currency': 'Bolívar Soberano',
        'code': 'VED',
        'num': 926,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Viet Nam',
        'currency': 'Dong',
        'code': 'VND',
        'num': 704,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Virgin Islands (British)',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Virgin Islands (U.s.)',
        'currency': 'US Dollar',
        'code': 'USD',
        'num': 840,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Wallis And Futuna',
        'currency': 'CFP Franc',
        'code': 'XPF',
        'num': 953,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Western Sahara',
        'currency': 'Moroccan Dirham',
        'code': 'MAD',
        'num': 504,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Yemen',
        'currency': 'Yemeni Rial',
        'code': 'YER',
        'num': 886,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Zambia',
        'currency': 'Zambian Kwacha',
        'code': 'ZMW',
        'num': 967,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Zimbabwe',
        'currency': 'Zimbabwe Dollar',
        'code': 'ZWL',
        'num': 932,
        'minors': 2,
        'fund': False,
    },
    {
        'entity': 'Zz01_bond Markets Unit European_eurco',
        'currency': 'Bond Markets Unit European Composite Unit (EURCO)',
        'code': 'XBA',
        'num': 955,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Zz02_bond Markets Unit European_emu-6',
        'currency': 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
        'code': 'XBB',
        'num': 956,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Zz03_bond Markets Unit European_eua-9',
        'currency': 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
        'code': 'XBC',
        'num': 957,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Zz04_bond Markets Unit European_eua-17',
        'currency': 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
        'code': 'XBD',
        'num': 958,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Zz06_testing_code',
        'currency': 'Codes specifically reserved for testing purposes',
        'code': 'XTS',
        'num': 963,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Zz07_no_currency',
        'currency': 'The codes assigned for transactions where no currency is involved',
        'code': 'XXX',
        'num': 999,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Zz08_gold',
        'currency': 'Gold',
        'code': 'XAU',
        'num': 959,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Zz09_palladium',
        'currency': 'Palladium',
        'code': 'XPD',
        'num': 964,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Zz10_platinum',
        'currency': 'Platinum',
        'code': 'XPT',
        'num': 962,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'Zz11_silver',
        'currency': 'Silver',
        'code': 'XAG',
        'num': 961,
        'minors': 0,
        'fund': False,
    },
    {
        'entity': 'ÅLand Islands',
        'currency': 'Euro',
        'code': 'EUR',
        'num': 978,
        'minors': 2,
        'fund': False,
    },
]
