# pylint: disable=too-many-lines
__all__ = [
    'CurrencyCode',
    'CurrencyNum',
    'CurrencyCodeNum',
    'CurrencyEntity',
    'CurrencyName',
]

from dataclasses import dataclass
from enum import Enum, IntEnum, StrEnum


class CurrencyCode(StrEnum):
    """A three-letter currency codes according to ISO 4217."""

    AED = 'AED'
    AFN = 'AFN'
    ALL = 'ALL'
    AMD = 'AMD'
    ANG = 'ANG'
    AOA = 'AOA'
    ARS = 'ARS'
    AUD = 'AUD'
    AWG = 'AWG'
    AZN = 'AZN'
    BAM = 'BAM'
    BBD = 'BBD'
    BDT = 'BDT'
    BGN = 'BGN'
    BHD = 'BHD'
    BIF = 'BIF'
    BMD = 'BMD'
    BND = 'BND'
    BOB = 'BOB'
    BOV = 'BOV'
    BRL = 'BRL'
    BSD = 'BSD'
    BTN = 'BTN'
    BWP = 'BWP'
    BYN = 'BYN'
    BZD = 'BZD'
    CAD = 'CAD'
    CDF = 'CDF'
    CHE = 'CHE'
    CHF = 'CHF'
    CHW = 'CHW'
    CLF = 'CLF'
    CLP = 'CLP'
    CNY = 'CNY'
    COP = 'COP'
    COU = 'COU'
    CRC = 'CRC'
    CUC = 'CUC'
    CUP = 'CUP'
    CVE = 'CVE'
    CZK = 'CZK'
    DJF = 'DJF'
    DKK = 'DKK'
    DOP = 'DOP'
    DZD = 'DZD'
    EGP = 'EGP'
    ERN = 'ERN'
    ETB = 'ETB'
    EUR = 'EUR'
    FJD = 'FJD'
    FKP = 'FKP'
    GBP = 'GBP'
    GEL = 'GEL'
    GHS = 'GHS'
    GIP = 'GIP'
    GMD = 'GMD'
    GNF = 'GNF'
    GTQ = 'GTQ'
    GYD = 'GYD'
    HKD = 'HKD'
    HNL = 'HNL'
    HRK = 'HRK'
    HTG = 'HTG'
    HUF = 'HUF'
    IDR = 'IDR'
    ILS = 'ILS'
    INR = 'INR'
    IQD = 'IQD'
    IRR = 'IRR'
    ISK = 'ISK'
    JMD = 'JMD'
    JOD = 'JOD'
    JPY = 'JPY'
    KES = 'KES'
    KGS = 'KGS'
    KHR = 'KHR'
    KMF = 'KMF'
    KPW = 'KPW'
    KRW = 'KRW'
    KWD = 'KWD'
    KYD = 'KYD'
    KZT = 'KZT'
    LAK = 'LAK'
    LBP = 'LBP'
    LKR = 'LKR'
    LRD = 'LRD'
    LSL = 'LSL'
    LYD = 'LYD'
    MAD = 'MAD'
    MDL = 'MDL'
    MGA = 'MGA'
    MKD = 'MKD'
    MMK = 'MMK'
    MNT = 'MNT'
    MOP = 'MOP'
    MRU = 'MRU'
    MUR = 'MUR'
    MVR = 'MVR'
    MWK = 'MWK'
    MXN = 'MXN'
    MXV = 'MXV'
    MYR = 'MYR'
    MZN = 'MZN'
    NAD = 'NAD'
    NGN = 'NGN'
    NIO = 'NIO'
    NOK = 'NOK'
    NPR = 'NPR'
    NZD = 'NZD'
    OMR = 'OMR'
    PAB = 'PAB'
    PEN = 'PEN'
    PGK = 'PGK'
    PHP = 'PHP'
    PKR = 'PKR'
    PLN = 'PLN'
    PYG = 'PYG'
    QAR = 'QAR'
    RON = 'RON'
    RSD = 'RSD'
    RUB = 'RUB'
    RWF = 'RWF'
    SAR = 'SAR'
    SBD = 'SBD'
    SCR = 'SCR'
    SDG = 'SDG'
    SEK = 'SEK'
    SGD = 'SGD'
    SHP = 'SHP'
    SLL = 'SLL'
    SOS = 'SOS'
    SRD = 'SRD'
    SSP = 'SSP'
    STN = 'STN'
    SVC = 'SVC'
    SYP = 'SYP'
    SZL = 'SZL'
    THB = 'THB'
    TJS = 'TJS'
    TMT = 'TMT'
    TND = 'TND'
    TOP = 'TOP'
    TRY = 'TRY'
    TTD = 'TTD'
    TWD = 'TWD'
    TZS = 'TZS'
    UAH = 'UAH'
    UGX = 'UGX'
    USD = 'USD'
    USN = 'USN'
    UYI = 'UYI'
    UYU = 'UYU'
    UYW = 'UYW'
    UZS = 'UZS'
    VED = 'VED'
    VES = 'VES'
    VND = 'VND'
    VUV = 'VUV'
    WST = 'WST'
    XAF = 'XAF'
    XAG = 'XAG'
    XAU = 'XAU'
    XBA = 'XBA'
    XBB = 'XBB'
    XBC = 'XBC'
    XBD = 'XBD'
    XCD = 'XCD'
    XDR = 'XDR'
    XOF = 'XOF'
    XPD = 'XPD'
    XPF = 'XPF'
    XPT = 'XPT'
    XSU = 'XSU'
    XTS = 'XTS'
    XUA = 'XUA'
    XXX = 'XXX'
    YER = 'YER'
    ZAR = 'ZAR'
    ZMW = 'ZMW'
    ZWL = 'ZWL'


class CurrencyNum(IntEnum):
    """A numeric codes of currencies as `int` values."""

    AED = 784
    AFN = 971
    ALL = 8
    AMD = 51
    ANG = 532
    AOA = 973
    ARS = 32
    AUD = 36
    AWG = 533
    AZN = 944
    BAM = 977
    BBD = 52
    BDT = 50
    BGN = 975
    BHD = 48
    BIF = 108
    BMD = 60
    BND = 96
    BOB = 68
    BOV = 984
    BRL = 986
    BSD = 44
    BTN = 64
    BWP = 72
    BYN = 933
    BZD = 84
    CAD = 124
    CDF = 976
    CHE = 947
    CHF = 756
    CHW = 948
    CLF = 990
    CLP = 152
    CNY = 156
    COP = 170
    COU = 970
    CRC = 188
    CUC = 931
    CUP = 192
    CVE = 132
    CZK = 203
    DJF = 262
    DKK = 208
    DOP = 214
    DZD = 12
    EGP = 818
    ERN = 232
    ETB = 230
    EUR = 978
    FJD = 242
    FKP = 238
    GBP = 826
    GEL = 981
    GHS = 936
    GIP = 292
    GMD = 270
    GNF = 324
    GTQ = 320
    GYD = 328
    HKD = 344
    HNL = 340
    HRK = 191
    HTG = 332
    HUF = 348
    IDR = 360
    ILS = 376
    IQD = 368
    IRR = 364
    ISK = 352
    JMD = 388
    JOD = 400
    JPY = 392
    KES = 404
    KGS = 417
    KHR = 116
    KMF = 174
    KPW = 408
    KRW = 410
    KWD = 414
    KYD = 136
    KZT = 398
    LAK = 418
    LBP = 422
    LKR = 144
    LRD = 430
    LSL = 426
    LYD = 434
    MAD = 504
    MDL = 498
    MGA = 969
    MKD = 807
    MMK = 104
    MNT = 496
    MOP = 446
    MRU = 929
    MUR = 480
    MVR = 462
    MWK = 454
    MXN = 484
    MXV = 979
    MYR = 458
    MZN = 943
    NAD = 516
    NGN = 566
    NIO = 558
    NOK = 578
    NPR = 524
    NZD = 554
    OMR = 512
    PAB = 590
    PEN = 604
    PGK = 598
    PHP = 608
    PKR = 586
    PLN = 985
    PYG = 600
    QAR = 634
    RON = 946
    RSD = 941
    RUB = 643
    RWF = 646
    SAR = 682
    SBD = 90
    SCR = 690
    SDG = 938
    SEK = 752
    SGD = 702
    SHP = 654
    SLL = 694
    SOS = 706
    SRD = 968
    SSP = 728
    STN = 930
    SVC = 222
    SYP = 760
    SZL = 748
    THB = 764
    TJS = 972
    TMT = 934
    TND = 788
    TOP = 776
    TRY = 949
    TTD = 780
    TWD = 901
    TZS = 834
    UAH = 980
    UGX = 800
    USD = 840
    USN = 997
    UYI = 940
    UYU = 858
    UYW = 927
    UZS = 860
    VED = 926
    VES = 928
    VND = 704
    VUV = 548
    WST = 882
    XAF = 950
    XAG = 961
    XAU = 959
    XBA = 955
    XBB = 956
    XBC = 957
    XBD = 958
    XCD = 951
    XDR = 960
    XOF = 952
    XPD = 964
    XPF = 953
    XPT = 962
    XSU = 994
    XTS = 963
    XUA = 965
    XXX = 999
    YER = 886
    ZAR = 710
    ZMW = 967
    ZWL = 932


@dataclass
class CurrencyCodeNumModel:
    alphabetic_code: str
    numeric_code: int


class CurrencyCodeNum(CurrencyCodeNumModel, Enum):
    AED = ('AED', 784)
    AFN = ('AFN', 971)
    ALL = ('ALL', 8)
    AMD = ('AMD', 51)
    ANG = ('ANG', 532)
    AOA = ('AOA', 973)
    ARS = ('ARS', 32)
    AUD = ('AUD', 36)
    AWG = ('AWG', 533)
    AZN = ('AZN', 944)
    BAM = ('BAM', 977)
    BBD = ('BBD', 52)
    BDT = ('BDT', 50)
    BGN = ('BGN', 975)
    BHD = ('BHD', 48)
    BIF = ('BIF', 108)
    BMD = ('BMD', 60)
    BND = ('BND', 96)
    BOB = ('BOB', 68)
    BOV = ('BOV', 984)
    BRL = ('BRL', 986)
    BSD = ('BSD', 44)
    BTN = ('BTN', 64)
    BWP = ('BWP', 72)
    BYN = ('BYN', 933)
    BZD = ('BZD', 84)
    CAD = ('CAD', 124)
    CDF = ('CDF', 976)
    CHE = ('CHE', 947)
    CHF = ('CHF', 756)
    CHW = ('CHW', 948)
    CLF = ('CLF', 990)
    CLP = ('CLP', 152)
    CNY = ('CNY', 156)
    COP = ('COP', 170)
    COU = ('COU', 970)
    CRC = ('CRC', 188)
    CUC = ('CUC', 931)
    CUP = ('CUP', 192)
    CVE = ('CVE', 132)
    CZK = ('CZK', 203)
    DJF = ('DJF', 262)
    DKK = ('DKK', 208)
    DOP = ('DOP', 214)
    DZD = ('DZD', 12)
    EGP = ('EGP', 818)
    ERN = ('ERN', 232)
    ETB = ('ETB', 230)
    EUR = ('EUR', 978)
    FJD = ('FJD', 242)
    FKP = ('FKP', 238)
    GBP = ('GBP', 826)
    GEL = ('GEL', 981)
    GHS = ('GHS', 936)
    GIP = ('GIP', 292)
    GMD = ('GMD', 270)
    GNF = ('GNF', 324)
    GTQ = ('GTQ', 320)
    GYD = ('GYD', 328)
    HKD = ('HKD', 344)
    HNL = ('HNL', 340)
    HRK = ('HRK', 191)
    HTG = ('HTG', 332)
    HUF = ('HUF', 348)
    IDR = ('IDR', 360)
    ILS = ('ILS', 376)
    INR = ('INR', 356)
    IQD = ('IQD', 368)
    IRR = ('IRR', 364)
    ISK = ('ISK', 352)
    JMD = ('JMD', 388)
    JOD = ('JOD', 400)
    JPY = ('JPY', 392)
    KES = ('KES', 404)
    KGS = ('KGS', 417)
    KHR = ('KHR', 116)
    KMF = ('KMF', 174)
    KPW = ('KPW', 408)
    KRW = ('KRW', 410)
    KWD = ('KWD', 414)
    KYD = ('KYD', 136)
    KZT = ('KZT', 398)
    LAK = ('LAK', 418)
    LBP = ('LBP', 422)
    LKR = ('LKR', 144)
    LRD = ('LRD', 430)
    LSL = ('LSL', 426)
    LYD = ('LYD', 434)
    MAD = ('MAD', 504)
    MDL = ('MDL', 498)
    MGA = ('MGA', 969)
    MKD = ('MKD', 807)
    MMK = ('MMK', 104)
    MNT = ('MNT', 496)
    MOP = ('MOP', 446)
    MRU = ('MRU', 929)
    MUR = ('MUR', 480)
    MVR = ('MVR', 462)
    MWK = ('MWK', 454)
    MXN = ('MXN', 484)
    MXV = ('MXV', 979)
    MYR = ('MYR', 458)
    MZN = ('MZN', 943)
    NAD = ('NAD', 516)
    NGN = ('NGN', 566)
    NIO = ('NIO', 558)
    NOK = ('NOK', 578)
    NPR = ('NPR', 524)
    NZD = ('NZD', 554)
    OMR = ('OMR', 512)
    PAB = ('PAB', 590)
    PEN = ('PEN', 604)
    PGK = ('PGK', 598)
    PHP = ('PHP', 608)
    PKR = ('PKR', 586)
    PLN = ('PLN', 985)
    PYG = ('PYG', 600)
    QAR = ('QAR', 634)
    RON = ('RON', 946)
    RSD = ('RSD', 941)
    RUB = ('RUB', 643)
    RWF = ('RWF', 646)
    SAR = ('SAR', 682)
    SBD = ('SBD', 90)
    SCR = ('SCR', 690)
    SDG = ('SDG', 938)
    SEK = ('SEK', 752)
    SGD = ('SGD', 702)
    SHP = ('SHP', 654)
    SLL = ('SLL', 694)
    SOS = ('SOS', 706)
    SRD = ('SRD', 968)
    SSP = ('SSP', 728)
    STN = ('STN', 930)
    SVC = ('SVC', 222)
    SYP = ('SYP', 760)
    SZL = ('SZL', 748)
    THB = ('THB', 764)
    TJS = ('TJS', 972)
    TMT = ('TMT', 934)
    TND = ('TND', 788)
    TOP = ('TOP', 776)
    TRY = ('TRY', 949)
    TTD = ('TTD', 780)
    TWD = ('TWD', 901)
    TZS = ('TZS', 834)
    UAH = ('UAH', 980)
    UGX = ('UGX', 800)
    USD = ('USD', 840)
    USN = ('USN', 997)
    UYI = ('UYI', 940)
    UYU = ('UYU', 858)
    UYW = ('UYW', 927)
    UZS = ('UZS', 860)
    VED = ('VED', 926)
    VES = ('VES', 928)
    VND = ('VND', 704)
    VUV = ('VUV', 548)
    WST = ('WST', 882)
    XAF = ('XAF', 950)
    XAG = ('XAG', 961)
    XAU = ('XAU', 959)
    XBA = ('XBA', 955)
    XBB = ('XBB', 956)
    XBC = ('XBC', 957)
    XBD = ('XBD', 958)
    XCD = ('XCD', 951)
    XDR = ('XDR', 960)
    XOF = ('XOF', 952)
    XPD = ('XPD', 964)
    XPF = ('XPF', 953)
    XPT = ('XPT', 962)
    XSU = ('XSU', 994)
    XTS = ('XTS', 963)
    XUA = ('XUA', 965)
    XXX = ('XXX', 999)
    YER = ('YER', 886)
    ZAR = ('ZAR', 710)
    ZMW = ('ZMW', 967)
    ZWL = ('ZWL', 932)


class CurrencyEntity(StrEnum):
    AFGHANISTAN = 'AFN'
    ALAND_ISLANDS = 'EUR'
    ALBANIA = 'ALL'
    ALGERIA = 'DZD'
    AMERICAN_SAMOA = 'USD'
    ANDORRA = 'EUR'
    ANGOLA = 'AOA'
    ANGUILLA = 'XCD'
    ANTIGUA_AND_BARBUDA = 'XCD'
    ARGENTINA = 'ARS'
    ARMENIA = 'AMD'
    ARUBA = 'AWG'
    AUSTRALIA = 'AUD'
    AUSTRIA = 'EUR'
    AZERBAIJAN = 'AZN'
    BAHAMAS = 'BSD'
    BAHRAIN = 'BHD'
    BANGLADESH = 'BDT'
    BARBADOS = 'BBD'
    BELARUS = 'BYN'
    BELGIUM = 'EUR'
    BELIZE = 'BZD'
    BENIN = 'XOF'
    BERMUDA = 'BMD'
    BHUTAN_BTN = 'BTN'
    BHUTAN_INR = 'INR'
    BOLIVIA_BOB = 'BOB'
    BOLIVIA_BOV = 'BOV'
    BONAIRE_SINT_EUSTATIUS_AND_SABA = 'USD'
    BOSNIA_AND_HERZEGOVINA = 'BAM'
    BOTSWANA = 'BWP'
    BOUVET_ISLAND = 'NOK'
    BRAZIL = 'BRL'
    BRITISH_INDIAN_OCEAN_TERRITORY = 'USD'
    BRUNEI_DARUSSALAM = 'BND'
    BULGARIA = 'BGN'
    BURKINA_FASO = 'XOF'
    BURUNDI = 'BIF'
    CABO_VERDE = 'CVE'
    CAMBODIA = 'KHR'
    CAMEROON = 'XAF'
    CANADA = 'CAD'
    CAYMAN_ISLANDS = 'KYD'
    CENTRAL_AFRICAN_REPUBLIC = 'XAF'
    CHAD = 'XAF'
    CHILE_CLF = 'CLF'
    CHILE_CLP = 'CLP'
    CHINA = 'CNY'
    CHRISTMAS_ISLAND = 'AUD'
    COCOS_KEELING_ISLANDS = 'AUD'
    COLOMBIA_COP = 'COP'
    COLOMBIA_COU = 'COU'
    COMOROS = 'KMF'
    CONGO = 'XAF'
    CONGO_THE_DEMOCRATIC_REPUBLIC_OF = 'CDF'
    COOK_ISLANDS = 'NZD'
    COSTA_RICA = 'CRC'
    COTE_DIVOIRE = 'XOF'
    CROATIA = 'HRK'
    CUBA_CUC = 'CUC'
    CUBA_CUP = 'CUP'
    CURACAO = 'ANG'
    CYPRUS = 'EUR'
    CZECHIA = 'CZK'
    DENMARK = 'DKK'
    DJIBOUTI = 'DJF'
    DOMINICA = 'XCD'
    DOMINICAN_REPUBLIC = 'DOP'
    ECUADOR = 'USD'
    EGYPT = 'EGP'
    EL_SALVADOR_SVC = 'SVC'
    EL_SALVADOR_USD = 'USD'
    EQUATORIAL_GUINEA = 'XAF'
    ERITREA = 'ERN'
    ESTONIA = 'EUR'
    ESWATINI = 'SZL'
    ETHIOPIA = 'ETB'
    EUROPEAN_UNION = 'EUR'
    FALKLAND_ISLANDS_OR_MALVINAS = 'FKP'
    FAROE_ISLANDS = 'DKK'
    FIJI = 'FJD'
    FINLAND = 'EUR'
    FRANCE = 'EUR'
    FRENCH_GUIANA = 'EUR'
    FRENCH_POLYNESIA = 'XPF'
    FRENCH_SOUTHERN_TERRITORIES = 'EUR'
    GABON = 'XAF'
    GAMBIA = 'GMD'
    GEORGIA = 'GEL'
    GERMANY = 'EUR'
    GHANA = 'GHS'
    GIBRALTAR = 'GIP'
    GREECE = 'EUR'
    GREENLAND = 'DKK'
    GRENADA = 'XCD'
    GUADELOUPE = 'EUR'
    GUAM = 'USD'
    GUATEMALA = 'GTQ'
    GUERNSEY = 'GBP'
    GUINEA = 'GNF'
    GUINEA_BISSAU = 'XOF'
    GUYANA = 'GYD'
    HAITI_HTG = 'HTG'
    HAITI_USD = 'USD'
    HEARD_ISLAND_AND_MCDONALD_ISLANDS = 'AUD'
    HOLY_SEE = 'EUR'
    HONDURAS = 'HNL'
    HONG_KONG = 'HKD'
    HUNGARY = 'HUF'
    ICELAND = 'ISK'
    INDIA = 'INR'
    INDONESIA = 'IDR'
    INTERNATIONAL_MONETARY_FUND_IMF = 'XDR'
    IRAN_ISLAMIC_REPUBLIC_OF = 'IRR'
    IRAQ = 'IQD'
    IRELAND = 'EUR'
    ISLE_OF_MAN = 'GBP'
    ISRAEL = 'ILS'
    ITALY = 'EUR'
    JAMAICA = 'JMD'
    JAPAN = 'JPY'
    JERSEY = 'GBP'
    JORDAN = 'JOD'
    KAZAKHSTAN = 'KZT'
    KENYA = 'KES'
    KIRIBATI = 'AUD'
    KOREA_THE_DEMOCRATIC_PEOPLES_REPUBLIC_OF = 'KPW'
    KOREA_THE_REPUBLIC_OF = 'KRW'
    KUWAIT = 'KWD'
    KYRGYZSTAN = 'KGS'
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC = 'LAK'
    LATVIA = 'EUR'
    LEBANON = 'LBP'
    LESOTHO_LSL = 'LSL'
    LESOTHO_ZAR = 'ZAR'
    LIBERIA = 'LRD'
    LIBYA = 'LYD'
    LIECHTENSTEIN = 'CHF'
    LITHUANIA = 'EUR'
    LUXEMBOURG = 'EUR'
    MACAO = 'MOP'
    MADAGASCAR = 'MGA'
    MALAWI = 'MWK'
    MALAYSIA = 'MYR'
    MALDIVES = 'MVR'
    MALI = 'XOF'
    MALTA = 'EUR'
    MARSHALL_ISLANDS = 'USD'
    MARTINIQUE = 'EUR'
    MAURITANIA = 'MRU'
    MAURITIUS = 'MUR'
    MAYOTTE = 'EUR'
    MEMBER_COUNTRIES_OF_THE_AFRICAN_DEVELOPMENT_BANK_GROUP = 'XUA'
    MEXICO_MXN = 'MXN'
    MEXICO_MXV = 'MXV'
    MICRONESIA_FEDERATED_STATES_OF = 'USD'
    MOLDOVA_THE_REPUBLIC_OF = 'MDL'
    MONACO = 'EUR'
    MONGOLIA = 'MNT'
    MONTENEGRO = 'EUR'
    MONTSERRAT = 'XCD'
    MOROCCO = 'MAD'
    MOZAMBIQUE = 'MZN'
    MYANMAR = 'MMK'
    NAMIBIA_NAD = 'NAD'
    NAMIBIA_ZAR = 'ZAR'
    NAURU = 'AUD'
    NEPAL = 'NPR'
    NETHERLANDS = 'EUR'
    NEW_CALEDONIA = 'XPF'
    NEW_ZEALAND = 'NZD'
    NICARAGUA = 'NIO'
    NIGER = 'XOF'
    NIGERIA = 'NGN'
    NIUE = 'NZD'
    NORFOLK_ISLAND = 'AUD'
    NORTH_MACEDONIA = 'MKD'
    NORTHERN_MARIANA_ISLANDS = 'USD'
    NORWAY = 'NOK'
    OMAN = 'OMR'
    PAKISTAN = 'PKR'
    PALAU = 'USD'
    PALESTINE_STATE_OF = ''
    PANAMA_PAB = 'PAB'
    PANAMA_USD = 'USD'
    PAPUA_NEW_GUINEA = 'PGK'
    PARAGUAY = 'PYG'
    PERU = 'PEN'
    PHILIPPINES = 'PHP'
    PITCAIRN = 'NZD'
    POLAND = 'PLN'
    PORTUGAL = 'EUR'
    PUERTO_RICO = 'USD'
    QATAR = 'QAR'
    REUNION = 'EUR'
    ROMANIA = 'RON'
    RUSSIA = 'RUB'
    RWANDA = 'RWF'
    SAINT_BARTHELEMY = 'EUR'
    SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA = 'SHP'
    SAINT_KITTS_AND_NEVIS = 'XCD'
    SAINT_LUCIA = 'XCD'
    SAINT_MARTIN_FRENCH_PART = 'EUR'
    SAINT_PIERRE_AND_MIQUELON = 'EUR'
    SAINT_VINCENT_AND_THE_GRENADINES = 'XCD'
    SAMOA = 'WST'
    SAN_MARINO = 'EUR'
    SAO_TOME_AND_PRINCIPE = 'STN'
    SAUDI_ARABIA = 'SAR'
    SENEGAL = 'XOF'
    SERBIA = 'RSD'
    SEYCHELLES = 'SCR'
    SIERRA_LEONE = 'SLL'
    SINGAPORE = 'SGD'
    SINT_MAARTEN_DUTCH_PART = 'ANG'
    SISTEMA_UNITARIO_DE_COMPENSACION_REGIONAL_DE_PAGOS_SUCRE = 'XSU'
    SLOVAKIA = 'EUR'
    SLOVENIA = 'EUR'
    SOLOMON_ISLANDS = 'SBD'
    SOMALIA = 'SOS'
    SOUTH_AFRICA = 'ZAR'
    SOUTH_SUDAN = 'SSP'
    SPAIN = 'EUR'
    SRI_LANKA = 'LKR'
    SUDAN = 'SDG'
    SURINAME = 'SRD'
    SVALBARD_AND_JAN_MAYEN = 'NOK'
    SWEDEN = 'SEK'
    SWITZERLAND_CHE = 'CHE'
    SWITZERLAND_CHF = 'CHF'
    SWITZERLAND_CHW = 'CHW'
    SYRIAN_ARAB_REPUBLIC = 'SYP'
    TAIWAN_PROVINCE_OF_CHINA = 'TWD'
    TAJIKISTAN = 'TJS'
    TANZANIA_UNITED_REPUBLIC_OF = 'TZS'
    THAILAND = 'THB'
    TIMOR_LESTE = 'USD'
    TOGO = 'XOF'
    TOKELAU = 'NZD'
    TONGA = 'TOP'
    TRINIDAD_AND_TOBAGO = 'TTD'
    TUNISIA = 'TND'
    TURKEY = 'TRY'
    TURKMENISTAN = 'TMT'
    TURKS_AND_CAICOS_ISLANDS = 'USD'
    TUVALU = 'AUD'
    UGANDA = 'UGX'
    UKRAINE = 'UAH'
    UNITED_ARAB_EMIRATES = 'AED'
    UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND = 'GBP'
    UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'USD'
    USA_USD = 'USD'
    USA_USN = 'USN'
    URUGUAY_UYI = 'UYI'
    URUGUAY_UYU = 'UYU'
    URUGUAY_UYW = 'UYW'
    UZBEKISTAN = 'UZS'
    VANUATU = 'VUV'
    VENEZUELA_VED = 'VED'
    VENEZUELA_VES = 'VES'
    VIET_NAM = 'VND'
    VIRGIN_ISLANDS_BRITISH = 'USD'
    VIRGIN_ISLANDS_US = 'USD'
    WALLIS_AND_FUTUNA = 'XPF'
    WESTERN_SAHARA = 'MAD'
    YEMEN = 'YER'
    ZAMBIA = 'ZMW'
    ZIMBABWE = 'ZWL'
    BOND_MARKETS_UNIT_EUROPEAN_EURCO = 'XBA'
    BOND_MARKETS_UNIT_EUROPEAN_EMU_6 = 'XBB'
    BOND_MARKETS_UNIT_EUROPEAN_EUA_9 = 'XBC'
    BOND_MARKETS_UNIT_EUROPEAN_EUA_17 = 'XBD'
    TESTING_CODE = 'XTS'
    NO_CURRENCY = 'XXX'
    GOLD = 'XAU'
    PALLADIUM = 'XPD'
    PLATINUM = 'XPT'
    SILVER = 'XAG'


class CurrencyName(StrEnum):
    AFGHANI = 'AFN'
    ADB_UNIT_OF_ACCOUNT = 'XUA'
    ALGERIAN_DINAR = 'DZD'
    ARGENTINE_PESO = 'ARS'
    ARMENIAN_DRAM = 'AMD'
    ARUBAN_FLORIN = 'AWG'
    AUSTRALIAN_DOLLAR = 'AUD'
    AZERBAIJAN_MANAT = 'AZN'
    BAHAMIAN_DOLLAR = 'BSD'
    BAHRAINI_DINAR = 'BHD'
    BAHT = 'THB'
    BALBOA = 'PAB'
    BARBADOS_DOLLAR = 'BBD'
    BELARUSIAN_RUBLE = 'BYN'
    BELIZE_DOLLAR = 'BZD'
    BERMUDIAN_DOLLAR = 'BMD'
    BOLIVAR_SOBERANO_1 = 'VED'
    BOLIVAR_SOBERANO_2 = 'VES'
    BOLIVIANO = 'BOB'
    BOND_MARKETS_UNIT_EUROPEAN_COMPOSITE_UNIT_EURCO = 'XBA'
    BOND_MARKETS_UNIT_EUROPEAN_MONETARY_UNIT_EMU_6 = 'XBB'
    BOND_MARKETS_UNIT_EUROPEAN_UNIT_OF_ACCOUNT_17_EUA_17 = 'XBD'
    BOND_MARKETS_UNIT_EUROPEAN_UNIT_OF_ACCOUNT_9_EUA_9 = 'XBC'
    BRAZILIAN_REAL = 'BRL'
    BRUNEI_DOLLAR = 'BND'
    BULGARIAN_LEV = 'BGN'
    BURUNDI_FRANC = 'BIF'
    CABO_VERDE_ESCUDO = 'CVE'
    CANADIAN_DOLLAR = 'CAD'
    CAYMAN_ISLANDS_DOLLAR = 'KYD'
    CFA_FRANC_BCEAO = 'XOF'
    CFA_FRANC_BEAC = 'XAF'
    CFP_FRANC = 'XPF'
    CHILEAN_PESO = 'CLP'
    CODES_SPECIFICALLY_RESERVED_FOR_TESTING_PURPOSES = 'XTS'
    COLOMBIAN_PESO = 'COP'
    COMORIAN_FRANC_ = 'KMF'
    CONGOLESE_FRANC = 'CDF'
    CONVERTIBLE_MARK = 'BAM'
    CORDOBA_ORO = 'NIO'
    COSTA_RICAN_COLON = 'CRC'
    CUBAN_PESO = 'CUP'
    CZECH_KORUNA = 'CZK'
    DALASI = 'GMD'
    DANISH_KRONE = 'DKK'
    DENAR = 'MKD'
    DJIBOUTI_FRANC = 'DJF'
    DOBRA = 'STN'
    DOMINICAN_PESO = 'DOP'
    DONG = 'VND'
    EAST_CARIBBEAN_DOLLAR = 'XCD'
    EGYPTIAN_POUND = 'EGP'
    EL_SALVADOR_COLON = 'SVC'
    ETHIOPIAN_BIRR = 'ETB'
    EURO = 'EUR'
    FALKLAND_ISLANDS_POUND = 'FKP'
    FIJI_DOLLAR = 'FJD'
    FORINT = 'HUF'
    GHANA_CEDI = 'GHS'
    GIBRALTAR_POUND = 'GIP'
    GOLD = 'XAU'
    GOURDE = 'HTG'
    GUARANI = 'PYG'
    GUINEAN_FRANC = 'GNF'
    GUYANA_DOLLAR = 'GYD'
    HONG_KONG_DOLLAR = 'HKD'
    HRYVNIA = 'UAH'
    ICELAND_KRONA = 'ISK'
    INDIAN_RUPEE = 'INR'
    IRANIAN_RIAL = 'IRR'
    IRAQI_DINAR = 'IQD'
    JAMAICAN_DOLLAR = 'JMD'
    JORDANIAN_DINAR = 'JOD'
    KENYAN_SHILLING = 'KES'
    KINA = 'PGK'
    KUNA = 'HRK'
    KUWAITI_DINAR = 'KWD'
    KWANZA = 'AOA'
    KYAT = 'MMK'
    LAO_KIP = 'LAK'
    LARI = 'GEL'
    LEBANESE_POUND = 'LBP'
    LEK = 'ALL'
    LEMPIRA = 'HNL'
    LEONE = 'SLL'
    LIBERIAN_DOLLAR = 'LRD'
    LIBYAN_DINAR = 'LYD'
    LILANGENI = 'SZL'
    LOTI = 'LSL'
    MALAGASY_ARIARY = 'MGA'
    MALAWI_KWACHA = 'MWK'
    MALAYSIAN_RINGGIT = 'MYR'
    MAURITIUS_RUPEE = 'MUR'
    MEXICAN_PESO = 'MXN'
    MEXICAN_UNIDAD_DE_INVERSION_UDI = 'MXV'
    MOLDOVAN_LEU = 'MDL'
    MOROCCAN_DIRHAM = 'MAD'
    MOZAMBIQUE_METICAL = 'MZN'
    MVDOL = 'BOV'
    NAIRA = 'NGN'
    NAKFA = 'ERN'
    NAMIBIA_DOLLAR = 'NAD'
    NEPALESE_RUPEE = 'NPR'
    NETHERLANDS_ANTILLEAN_GUILDER = 'ANG'
    NEW_ISRAELI_SHEQEL = 'ILS'
    NEW_TAIWAN_DOLLAR = 'TWD'
    NEW_ZEALAND_DOLLAR = 'NZD'
    NGULTRUM = 'BTN'
    NO_UNIVERSAL_CURRENCY = ''
    NORTH_KOREAN_WON = 'KPW'
    NORWEGIAN_KRONE = 'NOK'
    OUGUIYA = 'MRU'
    PAANGA = 'TOP'
    PAKISTAN_RUPEE = 'PKR'
    PALLADIUM = 'XPD'
    PATACA = 'MOP'
    PESO_CONVERTIBLE = 'CUC'
    PESO_URUGUAYO = 'UYU'
    PHILIPPINE_PESO = 'PHP'
    PLATINUM = 'XPT'
    POUND_STERLING = 'GBP'
    PULA = 'BWP'
    QATARI_RIAL = 'QAR'
    QUETZAL = 'GTQ'
    RAND = 'ZAR'
    RIAL_OMANI = 'OMR'
    RIEL = 'KHR'
    ROMANIAN_LEU = 'RON'
    RUFIYAA = 'MVR'
    RUPIAH = 'IDR'
    RUSSIAN_RUBLE = 'RUB'
    RWANDA_FRANC = 'RWF'
    SAINT_HELENA_POUND = 'SHP'
    SAUDI_RIYAL = 'SAR'
    SDR_SPECIAL_DRAWING_RIGHT = 'XDR'
    SERBIAN_DINAR = 'RSD'
    SEYCHELLES_RUPEE = 'SCR'
    SILVER = 'XAG'
    SINGAPORE_DOLLAR = 'SGD'
    SOL = 'PEN'
    SOLOMON_ISLANDS_DOLLAR = 'SBD'
    SOM = 'KGS'
    SOMALI_SHILLING = 'SOS'
    SOMONI = 'TJS'
    SOUTH_SUDANESE_POUND = 'SSP'
    SRI_LANKA_RUPEE = 'LKR'
    SUCRE = 'XSU'
    SUDANESE_POUND = 'SDG'
    SURINAM_DOLLAR = 'SRD'
    SWEDISH_KRONA = 'SEK'
    SWISS_FRANC = 'CHF'
    SYRIAN_POUND = 'SYP'
    TAKA = 'BDT'
    TALA = 'WST'
    TANZANIAN_SHILLING = 'TZS'
    TENGE = 'KZT'
    THE_CODES_ASSIGNED_FOR_TRANSACTIONS_WHERE_NO_CURRENCY_IS_INVOLVED = 'XXX'
    TRINIDAD_AND_TOBAGO_DOLLAR = 'TTD'
    TUGRIK = 'MNT'
    TUNISIAN_DINAR = 'TND'
    TURKISH_LIRA = 'TRY'
    TURKMENISTAN_NEW_MANAT = 'TMT'
    UAE_DIRHAM = 'AED'
    UGANDA_SHILLING = 'UGX'
    UNIDAD_DE_FOMENTO = 'CLF'
    UNIDAD_DE_VALOR_REAL = 'COU'
    UNIDAD_PREVISIONAL = 'UYW'
    URUGUAY_PESO_EN_UNIDADES_INDEXADAS_UI = 'UYI'
    US_DOLLAR = 'USD'
    US_DOLLAR_NEXT_DAY = 'USN'
    UZBEKISTAN_SUM = 'UZS'
    VATU = 'VUV'
    WIR_EURO = 'CHE'
    WIR_FRANC = 'CHW'
    WON = 'KRW'
    YEMENI_RIAL = 'YER'
    YEN = 'JPY'
    YUAN_RENMINBI = 'CNY'
    ZAMBIAN_KWACHA = 'ZMW'
    ZIMBABWE_DOLLAR = 'ZWL'
    ZLOTY = 'PLN'
